unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Note__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLT_Notes_Test.cls
/*
 * Created by Israel Zygelboim on 11/02/2019.
 */
@IsTest
private class CLT_Notes_Test {

	@IsTest static void testOne() {
		Account account = new Account(Name = 'Name');
		insert  account;

		note__c note = new note__c(Client__c = account.Id);
		insert note;

		Store__c store = new Store__c(SourceStoreId__c = CLT_Utils.getMyUser().StoreCode__c);
		insert store;

		String jsonString  = '{"items" : [{"Id" : "' + note.Id + '", "sku" : "15X7707493001l", "client":"' + account.Id + '"}], "objectName" : "note__c"}';

		CLT_Notes cltNotes = new CLT_Notes();

		cltNotes.retrieveGet(new Map<String, String>());
		cltNotes.retrievePost(new Map<String, String>(),(Map<String,Object>) JSON.deserializeUntyped(jsonString));
		cltNotes.retrieveDelete(new Map<String, String>{'id' => note.Id});
	}
}