unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CLT_Notes.cls
public class CLT_Notes implements clt_retailInterface{
   
	public Object retrievePost(Map<String, String> params, Map<String, Object> body) {
		return upsertItems(body);
	}

	public Object retrieveGet(Map<String, String> params) {
		return null;
	}

	public Object retrieveDelete(Map<String, String> params) {
		string objName = params.get('objectName');

		sobject note = new Note__c();
		note.Id = params.get('id');

		delete note;
		return true;
    
	}

	public List<Map<String, Object>> upsertItems(Map<String,Object> body) {
		String objectName = (String) body.get('objectName');
		Store__c myStore = CLT_Utils.getMyStore();

		List<Object> items = (List<Object>) body.get('items');
		Set<String> itemIds = new Set<String>();

		List<Map<String, Object>> mapNotes = CLT_Utils_Mapping.getMapObjectsByWrapperItems(objectName, 'Note', items);
		List<Note__c> notes = (List<Note__c>) JSON.deserialize(JSON.serialize(mapNotes), List<Note__c>.class);

		for(Note__c note : notes){
            if(myStore != null ){
			note.Store__c = myStore.Id;
            }
		}

		upsert notes;

		for(Note__c item: notes) {
			itemIds.add(item.Id);
		}

		if(itemIds.size() > 0) {
			return CLT_Utils_Mapping.getStandardWrapperList('Note__c', 'Note',
							' FROM ' + objectName + ' WHERE Id IN ' + CLT_Utils.convertToString(itemIds) + ' ORDER BY CreatedDate DESC');
		}

		return null;

	}
}