unpackaged/main/default/objects/CommSubscriptionConsent/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <description>The product sku linked to this subscription</description>
    <label>sku</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CommSubscriptionConsent/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <description>The Warehouse linked to that Subscription</description>
    <label>Warehouse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <label>Product Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Inventory__c/fields/ATS__c.field-meta.xml
<CustomField>
    <fullName>ATS__c</fullName>
    <label>ATS</label>
    <precision>12</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product_Inventory__c/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>sku</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFMCAPISetting__c/SFMCAPISetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SFMC API Setting</label>
</CustomObject>

unpackaged/main/default/objects/SFMCAPISetting__c/fields/BackInStockAutomationObjectId__c.field-meta.xml
<CustomField>
    <fullName>BackInStockAutomationObjectId__c</fullName>
    <description>Back In Stock Automation Object Id. populated by Batch_BackInStock</description>
    <label>Back In Stock Automation Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFMCAPISetting__c/fields/LastSentEventId__c.field-meta.xml
<CustomField>
    <fullName>LastSentEventId__c</fullName>
    <label>Last Sent Event Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Batch_BackInStock.cls
/*
----------------------------------------------------------------------
-- - Name              :  Batch_BackInStock
-- - Author            :  Abdelaaziz Idaoumahmoud
-- - Description       :  Batch for BackInStock process SFCC
-- Maintenance History :    
--
-- Date                 Name                        Version          Remarks
-- -----------          -----------                 --------         ----------------------
-- 30-05-2022           Abdelaaziz Idaoumahmoud    	1.0              Initial version
-- 22-12-2022           Mohamed Abdelfadel         	2.0              Remove every hard coding, replaced by Custom Setting record fields and usage of a backInStockBatchHelper
---------------------------------------------------------------------------------------
*/
global class Batch_BackInStock implements Database.Batchable<sObject>,  Database.AllowsCallouts, Schedulable, Database.Stateful {

    private Map<String, BackInStockWrapper> productInventories;
    private Set<String> skuWarehouseToSendToSFMC;
    private Set<String> setSkuToGetConsent;
    private Set<String> setWarehouseToGetConsent;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        skuWarehouseToSendToSFMC = new Set<String>();
        setSkuToGetConsent = new Set<String>();
        setWarehouseToGetConsent = new Set<String>();
        productInventories = new Map<String, BackInStockWrapper>();
        for(Product_Inventory__c productInventory : [SELECT sku__c, Warehouse__c, ATS__c 
                                                        FROM Product_Inventory__c 
                                                        WHERE ATS__c > 0 order by sku__c]){

            BackInStockWrapper productLine = new BackInStockWrapper();
            productLine.sku = productInventory.sku__c;
            productLine.warehouse = productInventory.warehouse__c;
            productLine.ats = Integer.valueOf(productInventory.ATS__c);
            productInventories.put(productInventory.sku__c + '|;|' + productInventory.warehouse__c, productLine);
            //fill two new created sets
            //Add Sku to set
            setSkuToGetConsent.add(productInventory.sku__c);
            setWarehouseToGetConsent.add(productInventory.warehouse__c);
        }
       
        return Database.getQueryLocator([
            SELECT sku__c, Warehouse__c
            FROM CommSubscriptionConsent  
            WHERE Name = 'BackInStock' AND EffectiveToDate = null AND sku__c IN: setSkuToGetConsent AND Warehouse__c IN:setWarehouseToGetConsent order by sku__c]);
            
    }

    global void execute(Database.BatchableContext BC, List<CommSubscriptionConsent> scope) {
        for(CommSubscriptionConsent commSubscriptionConsent : scope){
            if(!skuWarehouseToSendToSFMC.contains(commSubscriptionConsent.sku__c +'|;|'+ commSubscriptionConsent.warehouse__c)){
                System.debug('---- sku-Warehouse added : '+commSubscriptionConsent.sku__c +'|;|'+ commSubscriptionConsent.warehouse__c);
                skuWarehouseToSendToSFMC.add(commSubscriptionConsent.sku__c +'|;|'+ commSubscriptionConsent.warehouse__c);
            }
        }
         
    }

    global void finish(Database.BatchableContext BC) {
        if(!skuWarehouseToSendToSFMC.isEmpty()){
            String oAUTHAccessToken = BackInStockBatchHelper.getSFMCAccessToken();
            if(oAUTHAccessToken != null && oAUTHAccessToken != 'Error'){
                Long lastSentEventId = BackInStockBatchHelper.postBackInStockEvent(
                    productInventories, 
                    skuWarehouseToSendToSFMC ,  
                    oAUTHAccessToken
                );
                if(lastSentEventId != null){
                    String backInStockAutomationObjectId = BackInStockBatchHelper.triggerSFMCBackInStockAutomation(oAUTHAccessToken);
                    SFMCAPISetting__c sfmcAPISetting = SFMCAPISetting__c.getOrgDefaults();
                    sfmcAPISetting.BackInStockAutomationObjectId__c = backInStockAutomationObjectId;
                    sfmcAPISetting.LastSentEventId__c = lastSentEventId;
                    update sfmcAPISetting;
                }
            }
        }
    }

    global void execute(SchedulableContext sc) {
        String backInStockAutomationStatus;
        SFMCAPISetting__c sfmcAPISetting = SFMCAPISetting__c.getOrgDefaults();
        if(! String.isBlank(sfmcAPISetting.BackInStockAutomationObjectId__c)){
            String oAUTHAccessToken = BackInStockBatchHelper.getSFMCAccessToken();
            if(oAUTHAccessToken != null && oAUTHAccessToken != 'Error') 
                backInStockAutomationStatus = BackInStockBatchHelper.getSFMCBackInStockAutomationStatus(
                    oAUTHAccessToken, 
                    sfmcAPISetting
                );
        }
        if(
            String.isBlank(sfmcAPISetting.BackInStockAutomationObjectId__c)
            || (!String.isBlank(backInStockAutomationStatus) && backInStockAutomationStatus != 'Executing')
        ){
            Database.executeBatch(new Batch_BackInStock(), 2000);
        }
    }
    
}