unpackaged/main/default/objects/AnonymizationField__mdt/AnonymizationField__mdt.object-meta.xml
<CustomObject>
    <label>AnonymizationField</label>
    <pluralLabel>AnonymizationFields</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AnonymizationField__mdt/fields/AnonymizationObject__c.field-meta.xml
<CustomField>
    <fullName>AnonymizationObject__c</fullName>
    <label>AnonymizationObject</label>
    <referenceTo>AnonymizationObject__mdt</referenceTo>
    <relationshipLabel>AnonymizationFields</relationshipLabel>
    <relationshipName>AnonymizationFields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationField__mdt/fields/isCustomField__c.field-meta.xml
<CustomField>
    <fullName>isCustomField__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCustomField</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationField__mdt/fields/Suffix__c.field-meta.xml
<CustomField>
    <fullName>Suffix__c</fullName>
    <label>Suffix</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationObject__mdt/AnonymizationObject__mdt.object-meta.xml
<CustomObject>
    <label>AnonymizationObject</label>
    <pluralLabel>AnonymizationObjects</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AnonymizationObject__mdt/fields/isCustomObject__c.field-meta.xml
<CustomField>
    <fullName>isCustomObject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCustomObject</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationSFProcess__mdt/AnonymizationSFProcess__mdt.object-meta.xml
<CustomObject>
    <label>AnonymizationSFProcess</label>
    <pluralLabel>AnonymizationSFProcesses</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AnonymizationSFProcess__mdt/fields/AnonymizationObject__c.field-meta.xml
<CustomField>
    <fullName>AnonymizationObject__c</fullName>
    <label>AnonymizationObject</label>
    <referenceTo>AnonymizationObject__mdt</referenceTo>
    <relationshipLabel>AnonymizationSFProcesses</relationshipLabel>
    <relationshipName>AnonymizationSFProcesses</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationSFProcess__mdt/fields/ExecutionOrder__c.field-meta.xml
<CustomField>
    <fullName>ExecutionOrder__c</fullName>
    <label>ExecutionOrder</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AnonymizationSFProcess__mdt/fields/LookupField__c.field-meta.xml
<CustomField>
    <fullName>LookupField__c</fullName>
    <label>Lookup Field Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SFAnonymizationProcess.cls
/**
* @author Ulrich Madder NDONG NGOMO
* @date June,3rd 2024
* @Type Apex Class
*****************************************************************************************************************************************************************
* @description This class contains an invocable method used to anonymize client data according to the business requirements
***************************************************************************************************************************************************************** 
* @Version : 
* Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
* 0.0		|2024/06/03			|.UNNM		|.					|Original version
* 1.0		|2024/06/03			|.UNNM		|.					|Original version
*/
public with sharing class SFAnonymizationProcess {
    
    @InvocableMethod(label='SF Anonymization Process')
    public static void initAnonymizationProcess(List<SFAnonymizationProcessWrapper> flowInputs) {
		SFAnonymizationProcessWrapper wrapper = flowInputs[0];
        List<String> objectList = wrapper.objectList.split(',');
        List<Id> clientIds = wrapper.clientIdStr.split(wrapper.separator);
        List<Id> confObjIdList = new List<Id>();
        List<sObject> updateObjList = new List<sObject>();
        Map<String, List<String>> mapObjectAndFields = new Map<String, List<String>>();
        List<AnonymizationSFProcess__mdt> retrievedConfig = [SELECT Id, AnonymizationObject__c, LookupField__c, AnonymizationObject__r.DeveloperName, ExecutionOrder__c, AnonymizationObject__r.isCustomObject__c
                                                             FROM AnonymizationSFProcess__mdt WHERE AnonymizationObject__r.DeveloperName IN: objectList];
        Map<String, String> mapObjLookupFieldName = new Map<String, String>();
        Map<String, String> mapObjLookupFieldNameTmp = new Map<String, String>();
        for(AnonymizationSFProcess__mdt config : retrievedConfig) {
            mapObjLookupFieldNameTmp.put(config.AnonymizationObject__r.DeveloperName, config.LookupField__c);
            
            if(config.AnonymizationObject__r.isCustomObject__c){
                mapObjLookupFieldName.put(config.AnonymizationObject__r.DeveloperName+'__c', config.LookupField__c);                
            }else {
                mapObjLookupFieldName.put(config.AnonymizationObject__r.DeveloperName, config.LookupField__c);
            }
        }
        for(AnonymizationField__mdt field : [SELECT Id, AnonymizationObject__c, DeveloperName, AnonymizationObject__r.DeveloperName, AnonymizationObject__r.isCustomObject__c, isCustomField__c, Suffix__c
                                              FROM AnonymizationField__mdt 
                                              WHERE AnonymizationObject__r.DeveloperName IN: mapObjLookupFieldNameTmp.keySet()]) {
            String suffix = field.Suffix__c<>null?field.Suffix__c: '';
			String fieldName = field.DeveloperName.split('_')[1] + suffix;
            String objectName = field.AnonymizationObject__r.isCustomObject__c?field.AnonymizationObject__r.DeveloperName+'__c':field.AnonymizationObject__r.DeveloperName;
        	if(mapObjectAndFields.containsKey(objectName)){
            	mapObjectAndFields.get(objectName).add(fieldName);                                       
            }else {
            	List<String> fieldList = new List<String>();
                fieldList.add(fieldName);
                mapObjectAndFields.put(objectName, fieldList);
            }                                 
        }
        Map<String, String> retrievedSOQLQueriesMap = SOQLBuilder.buildSOQLQueriesMap(mapObjectAndFields, mapObjLookupFieldName, clientIds);
        List<sObject> objectRecordsMap = SOQLBuilder.getClientDataToBeAnonymized(retrievedSOQLQueriesMap);
        SFAnonymizationPushInQueueWrapper pushQWrapper = new SFAnonymizationPushInQueueWrapper();
		pushQWrapper.mapObjectAndFields = mapObjectAndFields;   
        pushQWrapper.globalList = objectRecordsMap;
        pushQWrapper.mapObjLookupFieldName = mapObjLookupFieldName;
        
        if(wrapper.timeStamp<>null) {
            pushQWrapper.timeStamp = wrapper.timeStamp;
            updateObjList = SOQLBuilder.pushInQueue(pushQWrapper);
        }else {
            updateObjList = SOQLBuilder.pushInQueueWithUsualVal(pushQWrapper);
        }
        System.enqueueJob(new SFAnonymizationProcessJob(updateObjList));
    }

}