unpackaged/main/default/objects/Order/fields/BillingContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactFirstName__c</fullName>
    <label>Billing Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/BillingContactLastName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactLastName__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/RI_Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>RI_Neighborhood__c</fullName>
    <label>Neighborhood</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderDeliveryGroupSummary/fields/Complementary__c.field-meta.xml
<CustomField>
    <fullName>Complementary__c</fullName>
    <label>Complementary</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderDeliveryMethod/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OrderDeliveryMethod/fields/isHomeDelivery__c.field-meta.xml
<CustomField>
    <fullName>isHomeDelivery__c</fullName>
    <formula>ISPICKVAL(  Delivery_Type__c , &quot;Home Delivery&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Home Delivery</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactFirstName__c</fullName>
    <label>Billing Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactLastName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactLastName__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_LWC_ExchangeOrderController.cls
/**************************************************************************************

-- - Author        : Fatima-Ezzahra LAFTOUMI

-- - Description   : A Controller for the LWC som_ExchangeOrderCreation_Component to get Order Summary, Order Delievry Method and Order Delievry Group Data

--

-- Maintenance History:

--

-- Date         Name    Version      Remarks

-- -----------  ----    -------  -------------------------------------------------------

-- 05-08-2022    FEL    1.0          Initial version

***************************************************************************************/
public with sharing class SOM_LWC_ExchangeOrderController {
    @AuraEnabled(cacheable=true)
    public static OrderSummary getOSDetails(String OsId){
        return [SELECT Id,(SELECT OrderDeliveryMethodId, OrderDeliveryMethod.Name FROM OrderDeliveryGroupSummaries), OriginalOrderId, BillingStreet, BillingPostalCode, BillingCity, BillingCountry,Complementary__c,RI_Neighborhood__c,StreetNumber__c, BillingEmailAddress, BillingPhoneNumber, BillingContactFirstName__c, BillingContactLastName__c,BillingState, AccountId, Pricebook2Id FROM OrderSummary WHERE Id =: OsId];
    }

    @AuraEnabled(cacheable=true)
    public static OrderDeliveryGroupSummary getOrderDelievryGroupDetails(String OsId){
        return [SELECT Description, EmailAddress, PhoneNumber, DeliverToName, DeliverToStreet, DeliverToPostalCode, DeliverToCity, DeliverToCountry,Complementary__c,RI_Neighborhood__c,StreetNumber__c,DeliverToState FROM OrderDeliveryGroupSummary WHERE OrderSummaryId =: OsId];
    }

    @AuraEnabled(cacheable=true)
    public static List<OrderDeliveryMethod> getOrderDelievryMethods(String country){
        if (country.equalsIgnoreCase('UK')) country='GB';
        return [SELECT Id, Name FROM OrderDeliveryMethod WHERE Country__c =: country and isHomeDelivery__c = true];
    }

    @AuraEnabled(cacheable=true)
    public static OrderDeliveryMethod getOrderDelievryMethodName(String mId){
        return [SELECT Id, Name FROM OrderDeliveryMethod WHERE Id =: mId];
    }
}