unpackaged/main/default/objects/TriggerBypass__mdt/TriggerBypass__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Bypass</label>
    <pluralLabel>Triggers Bypass</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/TriggerBypass__mdt/fields/ApexBypass__c.field-meta.xml
<CustomField>
    <fullName>ApexBypass__c</fullName>
    <inlineHelpText>Contain all the names of the classes separated by semicolons ;</inlineHelpText>
    <label>Apex Bypass</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/BypassTrigger.cls
/**
 * @author Paul-Louis Mony
 * @date 
 * @Type Apex Class
 *****************************************************************************************************************************************************************
 * @description The primary function of this class is to either activate or deactivate a trigger
 ***************************************************************************************************************************************************************** 
 * @Version : 
 * Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
 * 0.0		|29062023			|.PLM		|.					|.
*/
public class BypassTrigger {
	
    /*
    * @description Check if the class either bypassed or not by the current user
    *
    * @param className name of the class to be checked
    * @return a boolean value indicating whether the class has been bypassed by the user (true) or not (false).
    */
    public static Boolean checkBypassClass(String className) {

        TriggerBypass__mdt bypass = TriggerBypass__mdt.getInstance(UserInfo.getName().replace(' ', '_'));
        if (bypass != null) {
            return bypass.ApexBypass__c?.split(';')?.contains(className);
        }
      	return false;
    }
    
}