unpackaged/main/default/objects/OrderSummary/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/tech_PE_Fulfillment_Count__c.field-meta.xml
<CustomField>
    <fullName>tech_PE_Fulfillment_Count__c</fullName>
    <label>tech PE Fulfillment Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SOM_Batch_RetryAllocation.cls
global class SOM_Batch_RetryAllocation implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id FROM OrderSummary WHERE tech_PE_Fulfillment_Count__c > 0 AND On_Hold__c = false Order by CreatedDate desc';
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<OrderSummary> scope){
        SOM_GetAvailability_BatchSubClass sub = new SOM_GetAvailability_BatchSubClass(scope);
    } 

    global void finish(Database.BatchableContext BC){

    }
}