unpackaged/main/default/objects/OrderSummary/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/TransactionalEmail__c.object-meta.xml
<CustomObject>
    <label>Transactional Email</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Transactional Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactional Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactional Emails</relationshipLabel>
    <relationshipName>Transactional_Emails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Transactional Emails</relationshipLabel>
    <relationshipName>TransactionalEmails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShipmentConfirmation</fullName>
                <label>Shipment Confirmation</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>OrderCreated</fullName>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>ReturnReceived</fullName>
                <label>Return Received</label>
            </value>
            <value>
                <fullName>OrderReadyForPickup</fullName>
                <label>Order Ready For Pick-up</label>
            </value>
            <value>
                <fullName>ReturnCreated</fullName>
                <label>Return Request</label>
            </value>
            <value>
                <fullName>RefundConfirmation</fullName>
                <label>Refund (with Credit Memo)</label>
            </value>
            <value>
                <fullName>RefundValidationMissingProduct</fullName>
                <label>Refund (without Credit Memo)</label>
            </value>
            <value>
                <fullName>OrderCanceled</fullName>
                <label>Order Canceled</label>
            </value>
            <value>
                <fullName>CCAutomaticOrderCancellation</fullName>
                <label>CC Automatic  Order Cancellation</label>
            </value>
            <value>
                <fullName>CCReminder</fullName>
                <label>CC Reminder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SOM_UpdateTEQueueableTest.cls
@isTest
public class SOM_UpdateTEQueueableTest {

    @isTest
    static void testExecuteQueueable() {
        List<OrderSummary> orderList = SOM_testDataFactory.createOrderSummaryBulk(false, SOM_testDataFactory.OrderType.Standard, 1);
        OrderSummary os = orderList[0];
        
        Account accTest = new Account(PersonEmail = 'test@test.com', LastName = 'test');
        insert accTest;
        
        List<TransactionalEmail__c> testEmails = new List<TransactionalEmail__c>{
            new TransactionalEmail__c(
                Client__c = accTest.Id,
                OrderSummary__c = os.Id,
                Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_TO_SEND,
                Template__c = SOM_Constants.TRANSACTIONAL_EMAIL_TEMPLATE_NAME_ORDER_CREATED
            ),
            new TransactionalEmail__c(
                Client__c = accTest.Id,
                OrderSummary__c = os.Id,
                Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_TO_SEND,
                Template__c = SOM_Constants.TRANSACTIONAL_EMAIL_TEMPLATE_NAME_SHIPPING_CONFIRMATION
            )
        };
        insert testEmails;

        for (TransactionalEmail__c te : testEmails) {
            te.Status__c = 'Draft';
        }

        Test.startTest();
        SOM_UpdateTransactionalEmailsQueueable queueable = new SOM_UpdateTransactionalEmailsQueueable(testEmails);
        System.enqueueJob(queueable);
        Test.stopTest();

        List<TransactionalEmail__c> updatedEmails = [
            SELECT Id, Status__c FROM TransactionalEmail__c WHERE Id IN :testEmails
        ];

        for (TransactionalEmail__c updatedEmail : updatedEmails) {
            System.assertEquals('Draft', updatedEmail.Status__c, 'Status should be updated to Draft');
        }
    }

    @isTest
    static void testExecuteQueueableWithEmptyList() {
        List<TransactionalEmail__c> emptyList = new List<TransactionalEmail__c>();

        Test.startTest();
        SOM_UpdateTransactionalEmailsQueueable queueable = new SOM_UpdateTransactionalEmailsQueueable(emptyList);
        System.enqueueJob(queueable);
        Test.stopTest();

        System.assert(true);
    } 
}