unpackaged/main/default/objects/OrderSummary/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/recoveryHourTE__mdt/recoveryHourTE__mdt.object-meta.xml
<CustomObject>
    <label>recoveryHourTE</label>
    <pluralLabel>recoveryHoursTE</pluralLabel>
</CustomObject> 

unpackaged/main/default/objects/recoveryHourTE__mdt/fields/RecoveryHour__c.field-meta.xml
<CustomField>
    <fullName>RecoveryHour__c</fullName>
    <label>RecoveryHour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/TransactionalEmail__c.object-meta.xml
<CustomObject>
    <label>Transactional Email</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Transactional Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactional Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionalEmail__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Transactional Emails</relationshipLabel>
    <relationshipName>TransactionalEmails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/TECH_CustomerKey__c.field-meta.xml
<CustomField>
    <fullName>TECH_CustomerKey__c</fullName>
    <label>TECH_CustomerKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/TECH_GenerateInvoice__c.field-meta.xml
<CustomField>
    <fullName>TECH_GenerateInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_GenerateInvoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShipmentConfirmation</fullName>
                <label>Shipment Confirmation</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>OrderCreated</fullName>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>ReturnReceived</fullName>
                <label>Return Received</label>
            </value>
            <value>
                <fullName>OrderReadyForPickup</fullName>
                <label>Order Ready For Pick-up</label>
            </value>
            <value>
                <fullName>ReturnCreated</fullName>
                <label>Return Request</label>
            </value>
            <value>
                <fullName>RefundConfirmation</fullName>
                <label>Refund (with Credit Memo)</label>
            </value>
            <value>
                <fullName>RefundValidationMissingProduct</fullName>
                <label>Refund (without Credit Memo)</label>
            </value>
            <value>
                <fullName>OrderCanceled</fullName>
                <label>Order Canceled</label>
            </value>
            <value>
                <fullName>CCAutomaticOrderCancellation</fullName>
                <label>CC Automatic  Order Cancellation</label>
            </value>
            <value>
                <fullName>CCReminder</fullName>
                <label>CC Reminder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SOM_TransactionalEmailBatch.cls
global class SOM_TransactionalEmailBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    private Integer recoveryHour;
    Map<Id, TransactionalEmail__c> emailsToUpdate = new Map<Id, TransactionalEmail__c>();
    private List<TransactionalEmail__c> emailsToResend = new List<TransactionalEmail__c>();
    private List<TransactionalEmail__c> invoicesToDelete = new List<TransactionalEmail__c>();
    Map<Id, String> deletionResults = new Map<Id, String>();
    private List<String> TransactionalId;

    public SOM_TransactionalEmailBatch() {
        recoveryHour = (Integer) [SELECT RecoveryHour__c FROM recoveryHourTE__mdt WHERE DeveloperName = 'recoveryHour' LIMIT 1].RecoveryHour__c;
    }

    public SOM_TransactionalEmailBatch(List<String> TransactionalIds) {
        recoveryHour = (Integer) [SELECT RecoveryHour__c FROM recoveryHourTE__mdt WHERE DeveloperName = 'recoveryHour' LIMIT 1].RecoveryHour__c;
        TransactionalId = TransactionalIds;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Datetime recoveryDatetime = System.now().addHours(-recoveryHour);
        Datetime timeMinus10Minutes = System.now().addMinutes(-10);
        String query;

        if (Test.isRunningTest()) {
            query = 'SELECT Id, Template__c, Status__c, TECH_CustomerKey__c FROM TransactionalEmail__c WHERE Id IN :TransactionalId';
        } else {
            query = 'SELECT Id, Template__c, Status__c, TECH_CustomerKey__c FROM TransactionalEmail__c ' +
                    'WHERE Status__c = \'To send\' ' +
                    'AND OrderSummary__r.Status != \'Canceled\' ' +
                    'AND CreatedDate > :recoveryDatetime ' +
                    'AND CreatedDate < :timeMinus10Minutes';
        }

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<TransactionalEmail__c> records) {
        Set<Id> emailsToResendIds = new Set<Id>(); // Track IDs to avoid duplicates

        for (TransactionalEmail__c email : records) {
            email.Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_DRAFT;
            emailsToUpdate.put(email.Id, email);

            if (email.Template__c == SOM_Constants.TRANSACTIONAL_EMAIL_TEMPLATE_NAME_INVOICE) {
                invoicesToDelete.add(email);
            }


            if (!emailsToResendIds.contains(email.Id)) {
                emailsToResend.add(new TransactionalEmail__c(Id = email.Id, Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_TO_SEND));
                emailsToResendIds.add(email.Id);
            }
        }

        if (!invoicesToDelete.isEmpty() && !Test.isRunningTest()) {
            String oAUTHAccessToken = BackInStockBatchHelper.getSFMCAccessToken();
            deletionResults = AP2_SOMInvoiceManagement.SOM_DeleteInvoicesFromSFMC2(invoicesToDelete, oAUTHAccessToken);
        }

        for (Id EmailId : deletionResults.keySet()) {
            if (deletionResults.get(EmailId) == 'OK' && emailsToUpdate.containsKey(EmailId)) {
                emailsToUpdate.get(EmailId).TECH_GenerateInvoice__c = false;
                emailsToUpdate.get(EmailId).TECH_CustomerKey__c = null;
            }
        }
        if (!emailsToUpdate.isEmpty()) {
            update emailsToUpdate.values();
            System.enqueueJob(new SOM_UpdateTransactionalEmailsQueueable(emailsToUpdate.values()));
        }
    }

    global void finish(Database.BatchableContext BC) {



        if (!emailsToResend.isEmpty()) {
            System.enqueueJob(new SOM_UpdateTransactionalEmailsQueueable(emailsToResend));
           // update emailsToResend;
        }
        system.debug('emailsToResend'  + emailsToResend) ;
    }
}