unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log__c/fields/Debug_message__c.field-meta.xml
<CustomField>
    <fullName>Debug_message__c</fullName>
    <label>Debug message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/relatedToId__c.field-meta.xml
<CustomField>
    <fullName>relatedToId__c</fullName>
    <label>Related To Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/recordTypes/Log.recordType-meta.xml
<RecordType>
    <fullName>Log</fullName>
    <active>true</active>
    <label>Log</label>
</RecordType>

unpackaged/main/default/objects/LogLevel__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>error</fullName>
                <default>true</default>
                <label>error</label>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Logs.cls
public class Logs {
    
    public static void error(Exception e, String LOG_CLASS_NAME,String Method, String Request, String Response, String relatedToId ){
        
        Log__c log = new Log__c();
        
        log.Class_Name__c       = 'Class: '+LOG_CLASS_NAME+', Method: '+Method;
        log.Has_Error__c        = true;
        log.Error_Message__c    = e.getMessage();
        log.LineNumber__c    	= e.getLineNumber();
        log.LogLevel__c    		= 'error';
        log.Request__c    		= Request;
        log.Response__c    		= Response;
        log.relatedToId__c      = relatedToId;
        insert log;
    }
    
    public static void debug(String message, String LOG_CLASS_NAME, String Method, String Request, String Response , String relatedToId){
        List <LogLevel__mdt> LogLevel = [SELECT Id, Level__c FROM LogLevel__mdt];
        if (LogLevel[0].Level__c == 'debug' || Test.isRunningTest() ){
            
            Log__c log = new Log__c();
            log.Class_Name__c       = 'Class: '+LOG_CLASS_NAME+', Method: '+Method;
            log.Has_Error__c        = false;
            log.Debug_message__c    = message; 
            log.LogLevel__c    		= 'debug';
            log.Request__c    		= Request;
            log.Response__c    		= Response;
            log.relatedToId__c      = relatedToId;
            
            insert log;
        }
    }
    
    public static void info(String message, String LOG_CLASS_NAME, String Method, String Request, String Response , String relatedToId){
        List <LogLevel__mdt> LogLevel = [SELECT Id, Level__c FROM LogLevel__mdt];
        if (LogLevel[0].Level__c == 'info' || Test.isRunningTest() ){
            Log__c log = new Log__c();
            log.Class_Name__c       = 'Class: '+LOG_CLASS_NAME+', Method: '+Method;
            log.Has_Error__c        = false;
            log.Debug_message__c    = message; 
            log.LogLevel__c    		= 'info';
            log.Request__c    		= Request;
            log.Response__c    		= Response;
            log.relatedToId__c      = relatedToId;
            
            insert log;
        }
    }
    
    
}