unpackaged/main/default/objects/BL_App_Setting__mdt/BL_App_Setting__mdt.object-meta.xml
<CustomObject>
    <label>BL App Setting</label>
    <pluralLabel>BL App Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WeChat</fullName>
                <default>true</default>
                <label>WeChat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/Custom_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Custom_Parameters__c</fullName>
    <label>Custom Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/Immediate_Log__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Log__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Immediate Log</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/LogHistoryDays__c.field-meta.xml
<CustomField>
    <fullName>LogHistoryDays__c</fullName>
    <label>Log History Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/ProfilesManager__c.field-meta.xml
<CustomField>
    <fullName>ProfilesManager__c</fullName>
    <label>Profiles Manager</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/ProfilesSA__c.field-meta.xml
<CustomField>
    <fullName>ProfilesSA__c</fullName>
    <label>Profile SA</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_App_Setting__mdt/fields/Return_Full_Error__c.field-meta.xml
<CustomField>
    <fullName>Return_Full_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Full Error</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/BL_FieldsMapping__mdt.object-meta.xml
<CustomObject>
    <label>BL FieldsMapping</label>
    <pluralLabel>BL FieldsMappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/GetPicklistLabel__c.field-meta.xml
<CustomField>
    <fullName>GetPicklistLabel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get Picklist Label</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/InnerSelect_UseCase__c.field-meta.xml
<CustomField>
    <fullName>InnerSelect_UseCase__c</fullName>
    <label>InnerSelect UseCase</label>
    <referenceTo>BL_UseCase__mdt</referenceTo>
    <relationshipLabel>BL FieldsMappings (InnerSelect UseCase)</relationshipLabel>
    <relationshipName>BL_FieldsMappingsInnerSelect</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/Is_InnerSelect__c.field-meta.xml
<CustomField>
    <fullName>Is_InnerSelect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is InnerSelect</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/IsCurrency__c.field-meta.xml
<CustomField>
    <fullName>IsCurrency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCurrency</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/Save_to_SF__c.field-meta.xml
<CustomField>
    <fullName>Save_to_SF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Save to SF</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/Send_to_Clienteling_App__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Clienteling_App__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Clienteling App</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/SFFieldPath__c.field-meta.xml
<CustomField>
    <fullName>SFFieldPath__c</fullName>
    <label>SFFieldPath</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/UseCase__c.field-meta.xml
<CustomField>
    <fullName>UseCase__c</fullName>
    <label>Use Case</label>
    <referenceTo>BL_UseCase__mdt</referenceTo>
    <relationshipLabel>L FieldsMappings (Use Case)</relationshipLabel>
    <relationshipName>BL_FieldsMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/BL_FieldsMapping__mdt/fields/Wrapper_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Wrapper_Field_Name__c</fullName>
    <label>Wrapper Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BL_Translation__c/BL_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation Element for each Language</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BL_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>the language to be translated the source text</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar</fullName>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
            <value>
                <fullName>pt new</fullName>
                <label>Brazilian Portuguese new</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>nl</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>en_SG</fullName>
                <label>English (Singapore)</label>
            </value>
            <value>
                <fullName>en_GB</fullName>
                <label>English (United Kingdom)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BL_UseCase__mdt/BL_UseCase__mdt.object-meta.xml
<CustomObject>
    <label>BL Use Case</label>
    <pluralLabel>BL Use Cases</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/BL_UseCase__mdt/fields/FieldsMappingJson__c.field-meta.xml
<CustomField>
    <fullName>FieldsMappingJson__c</fullName>
    <label>Fields Mapping Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_UseCase__mdt/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_UseCase__mdt/fields/QueryCondition__c.field-meta.xml
<CustomField>
    <fullName>QueryCondition__c</fullName>
    <label>Query Condition</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BL_UseCase__mdt/fields/QueryConditionJson__c.field-meta.xml
<CustomField>
    <fullName>QueryConditionJson__c</fullName>
    <label>QueryConditionJson</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration (Seconds)</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Mobile_Language__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Language__c</fullName>
    <label>Mobile Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Mobile_Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Time_Zone__c</fullName>
    <label>Mobile Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <label>Query (SOQL)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Query_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Query_Parameters__c</fullName>
    <label>Query Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Request_Size__c.field-meta.xml
<CustomField>
    <fullName>Request_Size__c</fullName>
    <label>Request Size (KB)</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Request_URI__c.field-meta.xml
<CustomField>
    <fullName>Request_URI__c</fullName>
    <label>Request URI</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Response_Size__c.field-meta.xml
<CustomField>
    <fullName>Response_Size__c</fullName>
    <label>Response Size (KB)</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/SFDC_Limits__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Limits__c</fullName>
    <label>Salesforce Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/User_Agent__c.field-meta.xml
<CustomField>
    <fullName>User_Agent__c</fullName>
    <label>User Agent</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/recordTypes/Log.recordType-meta.xml
<RecordType>
    <fullName>Log</fullName>
    <active>true</active>
    <label>Log</label>
</RecordType>

unpackaged/main/default/classes/BL_Constants.cls
/**
 * @File Name          : BL_Constants.cls
 * @Description        : 
 * @Author             : Aliza Reishtein
 * @group     balink WS General
 * @Last Modified By   : Aliza Reishtein
 * @Last Modified On   : 23/03/2020, 9:04:48
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    22/03/2020   Aliza Reishtein     Initial Version
**/
public class BL_Constants {
    /**
     * Global Constants
     */
    public static final String BL_MULTIFIELD_SEPARATOR      = '/';
    public static final String BL_EMPTY_FIELD_VALUE         = 'field.emptyValue';
    
    /**
     * Objects name
     */
    public static final String BL_PICKLIST_MDT_NAME         = 'BL_Picklist__mdt';
    public static final String BL_APP_SETTING_MDT_NAME      = 'BL_App_Setting__mdt';
    public static final String BL_FIELD_MAPPING_MDT_NAME    = 'BL_FieldsMapping__mdt';
    public static final String BL_USECASE_MDT_NAME          = 'BL_UseCase__mdt';
    public static final String BL_TRANSLATION_NAME          = 'BL_Translation__c';
    //public static final String BL_LOG_NAME                = 'BL_Log__c';
    public static final String BL_LOG_NAME                  = 'Log__c';
    public static final String BL_USECASE_MDT_PREFIX        = 'BL_UseCase.';

    /**
     * App Settings
     */
    public static final String BL_AS_APPLICATION            = 'Application__c';
    public static final String BL_AS_CUSTOM_PARAMS          = 'Custom_Parameters__c';
    public static final String BL_AS_IMMEDIATE_LOG          = 'Immediate_Log__c';
    public static final String BL_AS_LOG_ACTIVE             = 'Is_LogActive__c';
    public static final String BL_AS_LOG_HISTORY_DAYS       = 'LogHistoryDays__c';
    public static final String BL_AS_FULL_ERROR             = 'Return_Full_Error__c';
    public static final String BL_AS_PROFILES_MANAGER       = 'ProfilesManager__c';
    public static final String BL_AS_PROFILES_SA            = 'ProfilesSA__c';

    /**
     * UseCase fields
     */
    public static final String BL_UC_OBJECT_NAME            = 'ObjectName__c';
    public static final String BL_UC_NOTES                  = 'Notes__c';
    public static final String BL_UC_QUERY_CONDITION        = 'QueryCondition__c';
    public static final String BL_UC_QUERY_CONDITION_JSON   = 'QueryConditionJson__c';
    public static final String BL_UC_LABEL                  = 'Label';
    public static final String BL_UC_DEVELOPER_NAME         = 'DeveloperName';
    public static final String BL_UC_FIELDS_MAPPING_JSON    = 'FieldsMappingJson__c';
    public static final String BL_UC_FIELDS_MAPPING_CHILDS  = 'BL_FieldsMappings__r';

    /**
     * FieldsMapping fields
     */
    public static final String BL_FM_SF_FIELDPATH           = 'SFFieldPath__c';
    public static final String BL_FM_WRAPPER_FIELD_NAME     = 'Wrapper_Field_Name__c';
    public static final String BL_FM_USECASE                = 'UseCase__c';
    public static final String BL_FM_USECASE_NAME           = 'UseCase__r.DeveloperName';
    public static final String BL_FM_SAVE_TO_SF             = 'Save_to_SF__c';
    public static final String BL_FM_SEND_TO_CLIENTELING    = 'Send_to_Clienteling_App__c';
    public static final String BL_FM_GET_PICKLIST_LABEL     = 'GetPicklistLabel__c';
    public static final String BL_FM_IS_CURRENCY            = 'IsCurrency__c';
    public static final String BL_FM_INNER_SELECT_UC        = 'InnerSelect_UseCase__c';
    public static final String BL_FM_INNER_SELECT_UC_NAME   = 'InnerSelect_UseCase__r.DeveloperName';
    public static final String BL_FM_IS_INNER_SELECT        = 'Is_InnerSelect__c';
    public static final String BL_FM_USECASE_LABEL          = 'UseCase__r.Label';
    public static final String BL_FM_INNER_SELECT_UC_LABEL  = 'InnerSelect_UseCase__r.Label';
    public static final String BL_FM_DEVELOPER_NAME         = 'DeveloperName';
    public static final String BL_FM_FORMAT                 = 'Format';
    public static final String BL_FM_TRANSLATIONKEY         = 'TranslationKey';

    /**
     * Translations fields
     */
    public static final String BL_TL_LANGUAGE               = 'Language__c';

    /**
     * Log fields
     */
    public static final String BL_LOG_MOBILE_TZ             = 'Mobile_Time_Zone__c';
    public static final String BL_LOG_MOBILE_LANG           = 'Mobile_Language__c';
    public static final String BL_LOG_REQUEST_SIZE          = 'Request_Size__c';
    public static final String BL_LOG_CLASSNAME             = 'Class_Name__c';
    public static final String BL_LOG_METHOD                = 'Method__c';
    public static final String BL_LOG_USER_AGENT            = 'User_Agent__c';
    public static final String BL_LOG_QUERY_PARAMS          = 'Query_Parameters__c';
    public static final String BL_LOG_REQUEST               = 'Request__c';
    public static final String BL_LOG_REQUEST_HEADERS       = 'Request_Headers__c';
    public static final String BL_LOG_REQUEST_URI           = 'Request_URI__c';
    public static final String BL_LOG_APPLICATION           = 'Application__c';
    public static final String BL_LOG_HAS_ERROR             = 'Has_Error__c';
    public static final String BL_LOG_STACK_TRACE           = 'Stack_Trace__c';
    public static final String BL_LOG_ERROR_MESSAGE         = 'Error_Message__c';
    public static final String BL_LOG_QUERY                 = 'Query__c';
    public static final String BL_LOG_NOTES                 = 'Notes__c';
    public static final String BL_LOG_RESPONSE_SIZE         = 'Response_Size__c';
    public static final String BL_LOG_RESPONSE              = 'Response__c';
    public static final String BL_LOG_SFDC_LIMITS           = 'SFDC_Limits__c';
    public static final String BL_LOG_DURATION              = 'Duration__c';

    /**
     * Error messages
     */
    public static final String BL_AS_INSTANTIATION_ERROR    = System.Label.BL_AppSettings_Instantiation_Error;
}