unpackaged/main/default/objects/BL_WECHAT_Configurations__c/BL_WECHAT_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BL_WECHAT_Configurations</label>
</CustomObject>

unpackaged/main/default/objects/BL_WECHAT_Configurations__c/fields/Default_Creation_SA__c.field-meta.xml
<CustomField>
    <fullName>Default_Creation_SA__c</fullName>
    <label>Default Creation SA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BL_WECHAT_Configurations__c/fields/Default_Creation_Store__c.field-meta.xml
<CustomField>
    <fullName>Default_Creation_Store__c</fullName>
    <label>Default Creation Store</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BL_WECHAT_Configurations__c/fields/Default_Lastname__c.field-meta.xml
<CustomField>
    <fullName>Default_Lastname__c</fullName>
    <label>Default Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BL_WECHAT_CustomSettingsMgr.cls
public with sharing class BL_WECHAT_CustomSettingsMgr { 
    /**
     * The SINGLETON handle to the instance
     */
    private static BL_WECHAT_CustomSettingsMgr self;

    /**
     * Initialize the SINGLETON instance or return it if already exists
     *
     * @returns {SSCSiteCustomSettingHelper}
     */
    public static BL_WECHAT_CustomSettingsMgr self() {
        if (self != null) {
            return self;
        }

        // To create org wide defaults in new org automatically. This will prevent NPE's in future.
        if (BL_WECHAT_Configurations__c.getInstance() == null) {
            upsert new BL_WECHAT_Configurations__c(SetupOwnerId = Userinfo.getOrganizationId());
        }

        self = new BL_WECHAT_CustomSettingsMgr();
        return self;
    }

    /**
    * BL_WECHAT_CustomSettingsMgr: private constructor of singleton 
    * to disable class standard instantiation
    */
    private BL_WECHAT_CustomSettingsMgr() {}

    /**
    * getDefaultCreationStore: return String defalt lastname
    * @return {String}
    */
    public String getDefaultLastname() {
        return String.valueOf(BL_WECHAT_Configurations__c.getInstance().default_lastname__c);
    }
    
    /**
    * getDefaultCreationSA: return String code of the default sa
    * @return {String}
    */
    public String getDefaultCreationSA() {
        return String.valueOf(BL_WECHAT_Configurations__c.getInstance().default_creation_sa__c);
    }

    /**
    * getDefaultCreationStore: return String code of the wechat store
    * @return {String}
    */
    public String getDefaultCreationStore() {
        return String.valueOf(BL_WECHAT_Configurations__c.getInstance().default_creation_store__c);
    }
}