unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Wishlist__c/Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <label>Wishlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Wishlist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wishlists</relationshipLabel>
    <relationshipName>Wishlists</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/TECH_uniqueKey__c.field-meta.xml
<CustomField>
    <fullName>TECH_uniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TECH_uniqueKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CLT_Wishlist.cls
public with sharing class CLT_Wishlist implements clt_retailInterface{
    
    public Object retrieveDelete(Map<String, String> params){
        return null;
    }
    
    public Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return upsertItems(body);
    }

    public Object retrieveGet(Map<String, String> params){
        return null;
    }

    public List<Object> upsertItems(Map<String,Object> body) {
        String clientId = (String) body.get('clientId');
        String wishlistType = (String) body.get('wishlistType');
        String externalId = wishlistType + '_' + clientId;
       
        List<Object> modelIds = new List<Object>();
        if (body.get('modelIds') != null ){
            modelIds  = (list<Object>)body.get('modelIds');
        }

        Wishlist__c wishlist = new Wishlist__c( Account__c = clientId, ExternalId__c = externalId);
        Schema.SObjectField f = Wishlist__c.Fields.ExternalId__c;
        Database.upsert(wishlist, f, false);

        insertWishlistItems(wishlist, modelIds, externalId);

        return null;
    }

    public void insertWishlistItems(Wishlist__c wishlist, List<Object> modelIds, string wishlistExternalId){
//     TODO   String userStoreId = CLT_User.getUserStoreId();
//        List<WishlistItem__c> wiToInsert = new List<WishlistItem__c>();
//
//        for(Object modelIdItem : modelIds){
//            string modelId = String.valueOf(modelIdItem);
//            WishlistItem__c wi = new WishlistItem__c(Model__c = modelId, Wishlist__c = wishlist.Id, TECH_uniqueKey__c = wishlistExternalId + modelId);
//            wi.Store__c = userStoreId;
//            wiToInsert.add(wi);
//        }
//
//        if (wiToInsert.size()>0){
//            Database.insert(wiToInsert, false);
//        }
    }


}