unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Sales_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Batch_UpdateLastStoreAndSA.cls
global class Batch_UpdateLastStoreAndSA implements Database.Batchable<sObject>, Schedulable {

    String query;

    public Batch_UpdateLastStoreAndSA() {
        query = 'SELECT Id FROM Account WHERE Id != NULL AND Id IN (SELECT Client__c FROM TransactionItem__c) ORDER BY Id';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) { 
        Set<Id> clientIds = (new Map<Id,Account> (scope)).keySet();
        Map<Id, TransactionItem__c> clientsTransactionsMap = new Map<Id, TransactionItem__c>();
        List<Account> clientsToUpdate = new List<Account>();

        for(TransactionItem__c t : [SELECT TransactionDate__c, Sales_Advisor__c, Store__c,Client__c
                                FROM TransactionItem__c 
                                WHERE Client__c IN: clientIds
                                ORDER BY TransactionDate__c]) {
            if(!clientsTransactionsMap.containsKey(t.Client__c) || (clientsTransactionsMap.containsKey(t.Client__c) && clientsTransactionsMap.get(t.Client__c).TransactionDate__c < t.TransactionDate__c)) {
                clientsTransactionsMap.put(t.Client__c, t);
            }
        }

        for(TransactionItem__c t : clientsTransactionsMap.values()) {
            Account acc = new Account(Id = t.Client__c);
            acc.Last_Transaction_SA__pc = t.Sales_Advisor__c;
            acc.Last_Transaction_Store__pc = t.Store__c;
            acc.LastPurchaseDate__pc = t.TransactionDate__c;
            clientsToUpdate.add(acc);
        }

        update clientsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {}

    global void execute(SchedulableContext sc) {
        Batch_UpdateLastStoreAndSA b = new Batch_UpdateLastStoreAndSA();
        Database.executeBatch(b);
    }

    // String query;

    // public Batch_UpdateLastStoreAndSA() {
    //     query = 'SELECT Id FROM Account WHERE Id != NULL AND Id IN (SELECT Client__c FROM Transaction__c)';
    // }

    // global Database.QueryLocator start(Database.BatchableContext BC) {
    //     return Database.getQueryLocator(query);
    // }

    // global void execute(Database.BatchableContext BC, List<Account> scope) { 
    //     Set<Id> clientIds = (new Map<Id,Account> (scope)).keySet();
    //     Map<Id, Transaction__c> clientsTransactionsMap = new Map<Id, Transaction__c>();
    //     List<Account> clientsToUpdate = new List<Account>();

    //     for(Transaction__c t : [SELECT TransactionDate__c, Vendor__c, Store__c,Client__c
    //                             FROM Transaction__c 
    //                             WHERE Client__c IN: clientIds
    //                             ORDER BY TransactionDate__c]) {
    //         if(!clientsTransactionsMap.containsKey(t.Client__c) || (clientsTransactionsMap.containsKey(t.Client__c) && clientsTransactionsMap.get(t.Client__c).TransactionDate__c < t.TransactionDate__c)) {
    //             clientsTransactionsMap.put(t.Client__c, t);
    //         }
    //     }

    //     for(Transaction__c t : clientsTransactionsMap.values()) {
    //         Account acc = new Account(Id = t.Client__c);
    //         acc.Last_Transaction_SA__pc = t.Vendor__c;
    //         acc.Last_Transaction_Store__pc = t.Store__c;
    //         clientsToUpdate.add(acc);
    //     }

    //     update clientsToUpdate;
    // }

    // global void finish(Database.BatchableContext BC) {}

    // global void execute(SchedulableContext sc) {
    //     Batch_UpdateLastStoreAndSA b = new Batch_UpdateLastStoreAndSA();
    //     Database.executeBatch(b);
    // }
}