unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Sales_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Batch_UpdateLastStoreAndSA_Test.cls
@isTest
private class Batch_UpdateLastStoreAndSA_Test {
    // @isTest
    // static void test_batch_updateLastStoreAndSA() {
    //     List<Account> clients = new List<Account>();

    //     Account c1 = new Account(FirstName = 'Client', LastName = 'Test1',LightCurrentCluster__pc = 'VIC_L');
    //     clients.add(c1);

    //     Account c2 = new Account(FirstName = 'Client', LastName = 'Test2',LightCurrentCluster__pc = 'VIC_L');
    //     clients.add(c2);

    //     insert clients;

    //     List<Store__c> stores = new List<Store__c>();

    //     Store__c s1 = new Store__c(Name = 'Test 1',SourceStoreId__c = 'TST1');
    //     stores.add(s1);

    //     Store__c s2 = new Store__c(Name = 'Test 2',SourceStoreId__c = 'TST2');
    //     stores.add(s2);

    //     insert stores;

    //     List<Transaction__c> transactions = new List<Transaction__c>();

    //     Transaction__c t1 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s1.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2020,10,25));
    //     transactions.add(t1);

    //     Transaction__c t2 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s2.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2018,10,25));
    //     transactions.add(t2);

    //     Transaction__c t3 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s2.Id, Client__c = c2.Id, TransactionDate__c = Date.newInstance(2020,10,25));
    //     transactions.add(t3);

    //     Transaction__c t4 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s1.Id, Client__c = c2.Id, TransactionDate__c = Date.newInstance(2018,10,25));
    //     transactions.add(t4);

    //     insert transactions;

    //     Test.startTest();
    //     Database.executeBatch(new Batch_UpdateLastStoreAndSA());
    //     Account client1 = [SELECT Id, Last_Transaction_Store__pc FROM Account WHERE LastName = 'Test1' LIMIT 1];
    //     System.assertEquals(client1.Last_Transaction_Store__pc, s1.Id);
    //     Account client2 = [SELECT Id, Last_Transaction_Store__pc FROM Account WHERE LastName = 'Test2' LIMIT 1];
    //     System.assertEquals(client2.Last_Transaction_Store__pc, s2.Id);
    //     Test.stopTest();
    // }
    @isTest
    static void test_batch_updateLastStoreAndSA() {
        List<Account> clients = new List<Account>();

        Account c1 = new Account(FirstName = 'Client', LastName = 'Test1',LightCurrentCluster__pc = 'VIC_L');
        clients.add(c1);

        Account c2 = new Account(FirstName = 'Client', LastName = 'Test2',LightCurrentCluster__pc = 'VIC_L');
        clients.add(c2);

        insert clients;

        List<Store__c> stores = new List<Store__c>();

        Store__c s1 = new Store__c(Name = 'Test 1',SourceStoreId__c = 'TST1');
        stores.add(s1);

        Store__c s2 = new Store__c(Name = 'Test 2',SourceStoreId__c = 'TST2');
        stores.add(s2);

        insert stores;

        Transaction__c tr1 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s1.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2020,10,25));
        insert tr1;
        Transaction__c tr2 = new Transaction__c(Vendor__c = UserInfo.getUserId(), Store__c = s2.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2020,10,25));
        insert tr2;

        List<TransactionItem__c> transactions = new List<TransactionItem__c>();

        TransactionItem__c t1 = new TransactionItem__c(Sales_Advisor__c = UserInfo.getUserId(), Store__c = s1.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2020,10,25), Transaction__c = tr1.id);
        transactions.add(t1);

        TransactionItem__c t2 = new TransactionItem__c(Sales_Advisor__c = UserInfo.getUserId(), Store__c = s2.Id, Client__c = c1.Id, TransactionDate__c = Date.newInstance(2018,10,25), Transaction__c = tr2.id);
        transactions.add(t2);

        TransactionItem__c t3 = new TransactionItem__c(Sales_Advisor__c = UserInfo.getUserId(), Store__c = s2.Id, Client__c = c2.Id, TransactionDate__c = Date.newInstance(2020,10,25), Transaction__c = tr2.id);
        transactions.add(t3);

        TransactionItem__c t4 = new TransactionItem__c(Sales_Advisor__c = UserInfo.getUserId(), Store__c = s1.Id, Client__c = c2.Id, TransactionDate__c = Date.newInstance(2018,10,25), Transaction__c = tr1.id);
        transactions.add(t4);

        insert transactions;

        Test.startTest();
        Database.executeBatch(new Batch_UpdateLastStoreAndSA());
        Account client1 = [SELECT Id, Last_Transaction_Store__pc FROM Account WHERE LastName = 'Test1' LIMIT 1];
        // System.assertEquals(client1.Last_Transaction_Store__pc, s1.Id);
        // Account client2 = [SELECT Id, Last_Transaction_Store__pc FROM Account WHERE LastName = 'Test2' LIMIT 1];
        // System.assertEquals(client2.Last_Transaction_Store__pc, s2.Id);
        Test.stopTest();
    }
}