unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/removedItem__c.field-meta.xml
<CustomField>
    <fullName>removedItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>keep track of deleted items =&gt; instead of deleting the item of the wishlit when the user delete this item from the app, this checbox turns to true and we don&#39;t send it to the app anymore</description>
    <label>removedItem</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/TECH_uniqueKey__c.field-meta.xml
<CustomField>
    <fullName>TECH_uniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TECH_uniqueKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CLT_WishlistItem.cls
public with sharing class CLT_WishlistItem implements clt_retailInterface {

    public Object retrieveDelete(Map < String, String > params) {
        // WishlistItem__c wishlistItem = new WishlistItem__c();
        // wishlistItem.Id = params.get('id');
        // wishlistItem.removedItem__c = true;
        // update wishlistItem;
        // delete wishlistItem;
        return true;
    }

    public Object retrievePost(Map < String, String > params, Map < String, Object > body) {
        return upsertItems(body);
    }

    public Object retrieveGet(Map < String, String > params) {
        String clientId = (String) params.get('clientId'); 
        return getWishListItems(clientId);
    }

    public List<Object> upsertItems(Map<String,Object> body) {
        String clientId = (String) body.get('clientId'); 
        List<Object> items = new List<Object> {body};
        Set<String> itemIds = new Set<String>();

        List<Map<String, Object>> mapWishlistItems = CLT_Utils_Mapping.getMapObjectsByWrapperItems('WishlistItem__c', 'WishListItem', items);
        List<WishlistItem__c> wishlistItems = (List<WishlistItem__c>) JSON.deserialize(JSON.serialize(mapWishlistItems), List<WishlistItem__c>.class);
        System.debug('wishlistItems => '+wishlistItems);

        User currentUser = CLT_Utils_Query.getUserInfos();
        Store__c userStore = [SELECT Id FROM Store__c WHERE SourceStoreId__c =: currentUser.StoreCode__c];

        // for(WishlistItem__c item: wishlistItems) {
        //    item.TECH_uniqueKey__c = item.Client__c + '-' + item.Product__c;
        //    item.Store__c = userStore.Id;
        // }
        List<WishlistItem__c> clientWishlistItems = [SELECT id, Name, Product__c, removedItem__c FROM WishlistItem__c WHERE Client__c =: clientId];

        for(WishlistItem__c item: wishlistItems) {
            System.debug('item 0 ===>>> '+ item );
           for(WishlistItem__c clientItem: clientWishlistItems){
               if(item.Product__c == clientItem.Product__c){
                   System.debug('old product');
                   System.debug('item 1 ===>>> '+ item + ' clientItem ===>>> '+clientItem);
                   if(clientItem.removedItem__c == true){
                       System.debug('old product inactiv');
                       item.removedItem__c = false;
                    }
                    if(clientItem.removedItem__c == false){
                       System.debug('old product activ');
                       item.removedItem__c = true;
                   }
                }
           } 
            System.debug('new product ===>>> ' +item);
            item.TECH_uniqueKey__c = item.Client__c + '-' + item.Product__c;
            item.Store__c = userStore.Id;
            System.debug('item end else ===>>> '+item);
       
        }

        Database.upsert(wishlistItems, WishlistItem__c.TECH_uniqueKey__c, false);

        for(WishlistItem__c item: wishlistItems) {
            System.debug('item id => '+item.Id);
            itemIds.add(item.Id);
        }
        System.debug('itemids => '+itemIds);

        return CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishListItem',
                        ' FROM WishlistItem__c WHERE Id IN ' + CLT_Utils.convertToString(itemIds) + ' ORDER BY CreatedDate DESC');

    }

    public static  List<Map<String, Object>> getWishListItems(String clientId){
        return CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishListItem',
                        'FROM WishlistItem__c WHERE Client__c =  \''+ clientId + '\' AND removedItem__c = FALSE ORDER BY CreatedDate DESC');
    }
}