unpackaged/main/default/objects/Start_Fulfillment_Process__e/Start_Fulfillment_Process__e.object-meta.xml
<CustomObject>
    <description>Used to break the SFCC transaction from Platform Integration User (unable to call OCI) to Automated Process User.
This Platform Event is caught by an Apex Trigger.
The Apex Trigger launches from SOM 201 that orchestrates FO creation.</description>
    <label>Start Fulfillment Process</label>
    <pluralLabel>Start Fulfillment Processes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Start_Fulfillment_Process__e/fields/OrderSummaryId__c.field-meta.xml
<CustomField>
    <fullName>OrderSummaryId__c</fullName>
    <label>OrderSummaryId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_StartFulfillmentProcessHelper.cls
public class SOM_StartFulfillmentProcessHelper {
    public static void startFulfillmentProcess( List<Start_Fulfillment_Process__e> FulfillmentEventList) {
        for ( Start_Fulfillment_Process__e FulfillmentEvent : FulfillmentEventList){
            if(!Test.isrunningtest()) {
                Map<String, Object> params = new Map<String, Object>();
                params.put('OrderSummaryID',FulfillmentEvent.OrderSummaryID__c);
                Flow.Interview.SOM_203_Invokable_FO_Orchestration OrchestrationFlow = new Flow.Interview.SOM_203_Invokable_FO_Orchestration (params);
                OrchestrationFlow.start();
            }
        }
    }
}