unpackaged/main/default/objects/Start_Fulfillment_Process__e/Start_Fulfillment_Process__e.object-meta.xml
<CustomObject>
    <description>Used to break the SFCC transaction from Platform Integration User (unable to call OCI) to Automated Process User.
This Platform Event is caught by an Apex Trigger.
The Apex Trigger launches from SOM 201 that orchestrates FO creation.</description>
    <label>Start Fulfillment Process</label>
    <pluralLabel>Start Fulfillment Processes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Start_Fulfillment_Process__e/fields/OrderSummaryId__c.field-meta.xml
<CustomField>
    <fullName>OrderSummaryId__c</fullName>
    <label>OrderSummaryId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_StartFulfillmentProcessTest.cls
@isTest
public with sharing class SOM_StartFulfillmentProcessTest {

@isTest
    static void TestPushEvent() {
     
      test.enablechangedatacapture();
      test.starttest ();
      Start_Fulfillment_Process__e fulfillmentEvent = new Start_Fulfillment_Process__e (OrderSummaryID__c = 'TEST' );
	  list<Database.SaveResult> sr = eventbus.publish (new List< Start_Fulfillment_Process__e > {FulfillmentEvent} );
      test.geteventbus().deliver();
      test.stoptest ();
      system.assertEquals(1, sr.size(),'Expected one fulfillmentEvent to be published') ;
      system.assertEquals(true, sr[0].isSuccess(),'FulfillmentEvent has not been published') ;
      
    }
}