unpackaged/main/default/objects/Accessory_Type__c/Accessory_Type__c.object-meta.xml
<CustomObject>
    <label>Accessory Type</label>
    <nameField>
        <label>Accessory-type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Accessory Types</relationshipLabel>
    <relationshipName>Accessory_Types_del</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Catalog_Product__c/fields/Accessory_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Type</label>
    <referenceTo>Accessory_Type__c</referenceTo>
    <relationshipLabel>Products (Catalog)</relationshipLabel>
    <relationshipName>Products_Catalog</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Catalog_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Products (Catalog)</relationshipLabel>
    <relationshipName>Products_Catalog</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLT_ProductDetails.cls
global with sharing class CLT_ProductDetails implements CLT_RetailInterface {
    public Object retrieveDelete(Map<String, String> params){
        return null;    
    }
     
    public Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    public Object retrieveGet(Map<String, String> params){
        User user = [SELECT Id, StoreCode__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];

        String productId = params.get('productId');
        Catalog_Product__c product = [SELECT Id,Name,Category__r.Name,Accessory_Type__r.Name FROM Catalog_Product__c WHERE Id = :productId LIMIT 1];
        

        Map<String, Object> result = new Map<String, Object>();

        if(!String.isEmpty(productId)) {
            result.put('myClientsRelatedWishlist', CLT_Utils_ProductDetails.GetMyClientsRelatedWishlist(productId, user.Id));
            result.put('storeClientsRelatedWishlist', CLT_Utils_ProductDetails.GetStoreClientsRelatedWishlist(productId, user.StoreCode__c));
            result.put('myClientsRelatedFamilyWishlist', 
                CLT_Utils_ProductDetails.GetMyClientsRelatedFamilyWishlist(product.Name, product.Category__r.Name, product.Accessory_Type__r.Name, product.Id, user.Id));
            result.put('storeClientsRelatedFamilyWishlist', 
                CLT_Utils_ProductDetails.GetStoreClientsRelatedFamilyWishlist(product.Name, product.Category__r.Name, product.Accessory_Type__r.Name, product.Id, user.StoreCode__c));
            result.put('myRelatedTasks',CLT_Utils_ProductDetails.GetRelatedTasks(productId, user.Id));
            result.put('storeRelatedTasks',CLT_Utils_ProductDetails.GetStoreRelatedTasks(productId, user.StoreCode__c));
        }

        return result;  
    }
}