unpackaged/main/default/objects/DDC_Config__mdt/DDC_Config__mdt.object-meta.xml
<CustomObject>
    <label>DDC Config</label>
    <pluralLabel>DDC Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/DDC_Config__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOOLEAN</fullName>
                <default>true</default>
                <label>BOOLEAN</label>
            </value>
            <value>
                <fullName>STRING</fullName>
            </value>
            <value>
                <fullName>NUMBER</fullName>
            </value>
            <value>
                <fullName>BASE64</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DDC_Config__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/DDC_Config_WS.cls
//@RestResource(urlMapping='/ddc/config')
public with sharing class DDC_Config_WS implements BL_Rest_Router_Factory.DispatchableGET {
    
    public Object executeGET(Map<String, String> pathParameters, Map<String, String> queryParams) {
        return getAllConfig(null);
    }

    /**
     * Get all config data
     */
    private static Map<String, Object> getAllConfig(Map<String, String> pathParams){
        List<DDC_Config__mdt> configs = [
            SELECT Key__c, Value__c, Type__c
            FROM DDC_Config__mdt
        ];

        Map<String,Object> mapConfigs = new Map<String,Object>();
        for(DDC_Config__mdt config : configs){

            Object value = convert(config.Type__c, config.Value__c);

            // sub object in wrapper
            if (config.Key__c.contains('.')) {
                getChild(config.Key__c, value, mapConfigs);
            }
            else {
                mapConfigs.put(config.Key__c, value);
            }
        }

        return mapConfigs;
    }

    /**
     * Recursive function to build JSON child object
     */
    private static void getChild(String key, Object value, Map<String,Object> parent){
        String childName = key.substringBefore('.');
        Object child = parent.get(childName);

        Map<String,Object> childMap;
        if(child == null){
            childMap = new Map<String,Object>();
        }
        else {
            childMap = (Map<String,Object>) child;
        }

        // RECURSSION
        String childAttribute = key.substringAfter('.');
        if(childAttribute.contains('.')){
            getChild(childAttribute, value, childMap);
        }
        else {
            childMap.put(childAttribute, value);
        }

        parent.put(childName, childMap);
    }

    /**
     * Convert string to defined type
     */
    private static Object convert(String fieldType, Object value) {
        if(fieldType != null){
            String lowFieldType = fieldType.ToLowerCase();
            if (lowFieldType.ToLowerCase() == 'date')
                value = Date.valueOf(String.valueOf(value));

            else if (lowFieldType == 'double')
                value = Double.valueOf(value);

            else if (lowFieldType == 'integer')
                value = Integer.valueOf(value);

            else if (lowFieldType == 'base64')
                value = Blob.valueOf(String.valueOf(value));

            else if (lowFieldType == 'boolean')
                value = Boolean.valueOf(value);

            else if (lowFieldType == 'json') {
                value = JSON.deserializeUntyped(String.valueOf(value));
            }
        }

        return value;
    }
}