unpackaged/main/default/objects/CreditMemo/fields/Credit_Memo_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Date__c</fullName>
    <label>Credit Memo Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/Sales_Channel_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Sales Channel Mapping</label>
    <pluralLabel>Sales Channel Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <inlineHelpText>Please enter the timezone from the following list : https://help.salesforce.com/s/articleView?id=sf.admin_supported_timezone.htm&amp;type=5</inlineHelpText>
    <label>Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_Update_Credit_Memo_Date_Helper.cls
public class SOM_Update_Credit_Memo_Date_Helper {
    public static void updateCreditMemoDate(List<CreditMemo> newMap){
         Map<String, Id> CreditMemoIds = new Map<String, Id>(); // Map<Order Summary Id, Credit Mamo Id>
        for(CreditMemo singleCM : newMap){
            CreditMemoIds.put(singleCM.ReferenceEntityId, singleCM.Id);
        }
        List<OrderSummary> relatedOrderSummary = [SELECT Id, BillingCountry FROM OrderSummary WHERE Id IN :CreditMemoIds.KeySet()];
        List<String> orderSummaryCountryList = new List<String>(); 
        for(OrderSummary singleOS : relatedOrderSummary){
            orderSummaryCountryList.add(singleOS.BillingCountry);
        }
        List<Sales_Channel_Mapping__mdt> salesChannelMDT = [SELECT Zone__c, Timezone__c FROM Sales_Channel_Mapping__mdt WHERE Zone__c IN :orderSummaryCountryList];
        Map<Id, String> CreditMemoTimeZonesMap = new Map<Id, String>(); // Map<Credit Mamo Id, TimeZone>
        for(OrderSummary os : relatedOrderSummary){
            for(Sales_Channel_Mapping__mdt singleMDT : salesChannelMDT){
                if(os.BillingCountry == singleMDT.Zone__c){
                    CreditMemoTimeZonesMap.put(CreditMemoIds.get(os.Id), singleMDT.Timezone__c);
                }
            }
        }
        for(CreditMemo singleCredit : newMap){
            SOM_DateConvertionInput dateinput   = new SOM_DateConvertionInput();
            dateinput.targetTimeZone            = CreditMemoTimeZonesMap.get(singleCredit.Id);
            dateinput.dateToConvert             = singleCredit.CreatedDate;
            singleCredit.Credit_Memo_Date__c    = SOM_DateTimeHelper.convertDateTimeByTimeZone(new List<SOM_DateConvertionInput>{dateinput})[0].date();
        }
    }
}