unpackaged/main/default/objects/CreditMemo/fields/Credit_Memo_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Date__c</fullName>
    <label>Credit Memo Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CreditMemo/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund</label>
    <referenceTo>Refund</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditMemo/fields/ReturnOrder__c.field-meta.xml
<CustomField>
    <fullName>ReturnOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return Order</label>
    <referenceTo>ReturnOrder</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CreditMemoLine/fields/ReturnOrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>ReturnOrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return Order Line Item</label>
    <referenceTo>ReturnOrderLineItem</referenceTo>
    <relationshipLabel>Credit Memo Lines</relationshipLabel>
    <relationshipName>Credit_Memo_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <formula>Product2.COO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COO</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/hsCode__c.field-meta.xml
<CustomField>
    <fullName>hsCode__c</fullName>
    <formula>Product2.hsCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hsCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/hsCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>hsCodeDescription__c</fullName>
    <formula>Product2.hsCodeDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HsCode Description</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <label>Tax Rate</label>
    <summarizedField>OrderItemTaxLineItemSummary.Rate</summarizedField>
    <summaryForeignKey>OrderItemTaxLineItemSummary.OrderItemSummaryId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactFirstName__c</fullName>
    <label>Billing Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactLastName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactLastName__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <label>COO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/hsCode__c.field-meta.xml
<CustomField>
    <fullName>hsCode__c</fullName>
    <label>hsCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/hsCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>hsCodeDescription__c</fullName>
    <label>hsCode Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Refund/fields/RefundOrigin__c.field-meta.xml
<CustomField>
    <fullName>RefundOrigin__c</fullName>
    <label>Refund Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial Cancelation</fullName>
            </value>
            <value>
                <fullName>Full Cancelation</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Appeasement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ReturnOrderLineItem/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <description>Concatenation of serial numbers.</description>
    <label>SerialNumber</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/SOM_CreditMemoHelperTest.cls
@isTest
public class SOM_CreditMemoHelperTest {
    public static Id creditMemoId;
    public static Boolean attachedToRO = false ;
    public static Boolean discount = false ;
    public static List<CreditMemo> creditmemo = new List<CreditMemo>();
    
    @isTest(seeAllData=true)
    public static void makeData() {
        List<OrderSummary> los = SOM_testDataFactory.createOrderSummaryBulk(false,SOM_testDataFactory.OrderType.Standard,1);
        FulfillmentOrder fo = SOM_testDataFactory.createFO(los[0]);
        Map<Id,FulfillmentOrder> mapFO = new Map<Id,FulfillmentOrder>();
        mapFO.put(fo.Id,fo);
        Map<Id, Shipment> shipmentMap = SOM_testDataFactory.createShipments(mapFO);
        Refund refund = SOM_testDataFactory.createRefundWithCreditMemo(los[0] ,attachedToRO,discount);
        creditmemo = [SELECT ID, ReturnOrder__c, Credit_Memo_Date__c, CreatedDate,Refund__r.RefundOrigin__c, TYPEOF ReferenceEntity WHEN OrderSummary THEN Id, CurrencyIsoCode, Account.Name, OrderNumber, BillingCity, BillingPostalCode, BillingState, BillingContactFirstName__c, 
                      BillingContactLastName__c, BillingCountry, BillingStreet END, CreditDate, CreditMemoNumber, DocumentNumber, TotalAmount, TotalAmountWithTax, TotalTaxAmount,
                      (SELECT ID, Type, RelatedLineId, Product2.Description, AdjustmentAmountWithTax, AdjustmentAmount, AdjustmentTaxAmount, ChargeTaxAmount, ChargeAmount, ChargeAmountWithTax, ReturnOrderLineItem__c, ReturnOrderLineItem__r.QuantityReturned, ReturnOrderLineItem__r.SerialNumber__c,  
                       TYPEOF ReferenceEntityItem WHEN OrderItemSummary THEN TaxRate__c, hsCode__c, hsCodeDescription__c, COO__c END FROM CreditMemoLines) FROM CreditMemo WHERE Refund__c = :refund.Id];
        List<CreditMemoLine> credMemoLines = [select Id , ReturnOrderLineItem__c , Type from CreditMemoLine where CreditMemoId =: creditmemo[0].Id];
        creditMemoId = creditmemo[0].Id;
    }
    
    @isTest(seeAllData=true)
    public static void callConstructorAttachedToRO() {
        attachedToRO = true ;
        makeData();
        attachedToRO = false ;
        SOM_CreditMemoHelper.updateCreditMemoDate(creditmemo);        
        System.assertNotEquals(creditmemo[0].Credit_Memo_Date__c,null, 'Credit_Memo_Date__c Updated');
    }
    
    
    
}