unpackaged/main/default/objects/Invoice/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/isSerialized__c.field-meta.xml
<CustomField>
    <fullName>isSerialized__c</fullName>
    <formula>Product2.isSerialized__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Serialized</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/isSerialized__c.field-meta.xml
<CustomField>
    <fullName>isSerialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Serialized</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/recoveryHourTE__mdt/recoveryHourTE__mdt.object-meta.xml
<CustomObject>
    <label>recoveryHourTE</label>
    <pluralLabel>recoveryHoursTE</pluralLabel>
</CustomObject> 

unpackaged/main/default/objects/recoveryHourTE__mdt/fields/RecoveryHour__c.field-meta.xml
<CustomField>
    <fullName>RecoveryHour__c</fullName>
    <label>RecoveryHour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/TransactionalEmail__c.object-meta.xml
<CustomObject>
    <label>Transactional Email</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Transactional Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactional Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactional Emails</relationshipLabel>
    <relationshipName>Transactional_Emails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Transactional Emails</relationshipLabel>
    <relationshipName>TransactionalEmails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TransactionalEmail__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShipmentConfirmation</fullName>
                <label>Shipment Confirmation</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>OrderCreated</fullName>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>ReturnReceived</fullName>
                <label>Return Received</label>
            </value>
            <value>
                <fullName>OrderReadyForPickup</fullName>
                <label>Order Ready For Pick-up</label>
            </value>
            <value>
                <fullName>ReturnCreated</fullName>
                <label>Return Request</label>
            </value>
            <value>
                <fullName>RefundConfirmation</fullName>
                <label>Refund (with Credit Memo)</label>
            </value>
            <value>
                <fullName>RefundValidationMissingProduct</fullName>
                <label>Refund (without Credit Memo)</label>
            </value>
            <value>
                <fullName>OrderCanceled</fullName>
                <label>Order Canceled</label>
            </value>
            <value>
                <fullName>CCAutomaticOrderCancellation</fullName>
                <label>CC Automatic  Order Cancellation</label>
            </value>
            <value>
                <fullName>CCReminder</fullName>
                <label>CC Reminder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SOM_TransactionalEmailBatchTest.cls
@isTest
private class SOM_TransactionalEmailBatchTest {
    private static List<String> TransactionalEmailIds ;
    @isTest(SeeAllData=true)
    static void setupData() {
        Integer recoveryHour = (Integer)[SELECT RecoveryHour__c FROM recoveryHourTE__mdt WHERE DeveloperName = 'recoveryHour' LIMIT 1].RecoveryHour__c;
        
        List<OrderSummary> orderList = SOM_testDataFactory.createOrderSummaryBulk(false, SOM_testDataFactory.OrderType.Standard, 1);
        OrderSummary os = orderList[0];
        FulfillmentOrder fo = SOM_testDataFactory.createFO(os);
        List<FulfillmentOrder> foList = [
            SELECT Id, DeliveryMethodId, OrderSummaryId, Type, FulfilledFromLocationId,
                   FulfilledFromLocation.VisitorAddress.City,
                   FulfilledFromLocation.VisitorAddress.Street,
                   FulfilledFromLocation.VisitorAddress.PostalCode,
                   FulfilledFromLocation.VisitorAddress.State,
                   FulfilledFromLocation.VisitorAddress.Country,
                   FulfilledToName, FulfilledToCity, FulfilledToStreet, FulfilledToPostalCode,
                   FulfilledToState, FulfilledToCountry,
                   (SELECT Id, FulfillmentOrderLineItemNumber, FulfillmentOrderId, Product2.StockKeepingUnit,
                           OrderItemSummaryId, Quantity, Product2Id, OrderItemSummary.isSerialized__c 
                    FROM FulfillmentOrderLineItems 
                    WHERE Type != :SOM_Constants.DELIVERY_CHARGE)
            FROM FulfillmentOrder 
            WHERE Id = :fo.Id
        ];
        Map<Id, FulfillmentOrder> mapFO = new Map<Id, FulfillmentOrder>(foList);
        System.debug('FulfillmentOrder Map: ' + mapFO);
        Map<Id, Shipment> shipments = SOM_testDataFactory.createShipments(mapFO);
        
        List<Invoice> invList = [SELECT Id FROM Invoice WHERE ReferenceEntityId = :os.Id];
        if (!invList.isEmpty()) {
            invList[0].InvoiceNumber__c = 'invtest1';
            update invList;
        }
        
        Account accTest = new Account(personEmail = 'test@test.com', lastName = 'test');
        insert accTest;
        
        List<TransactionalEmail__c> testEmails = new List<TransactionalEmail__c>{
            new TransactionalEmail__c(
                Client__c = accTest.Id,
                OrderSummary__c = os.Id,
                Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_TO_SEND,
                Template__c = SOM_Constants.TRANSACTIONAL_EMAIL_TEMPLATE_NAME_ORDER_CREATED
            ),
            new TransactionalEmail__c(
                Client__c = accTest.Id,
                OrderSummary__c = os.Id,
                Status__c = SOM_Constants.TRANSACTIONAL_EMAIL_STATUS_TO_SEND,
                Template__c = SOM_Constants.TRANSACTIONAL_EMAIL_TEMPLATE_NAME_SHIPPING_CONFIRMATION
            )
        };
        insert testEmails;
        
        List<String> Emails = new List<String>();
        for (TransactionalEmail__c te : testEmails) {
            Emails.add(te.Id);
        }
        TransactionalEmailIds = Emails ;    }
    
    @isTest(SeeAllData=true)
    static void testBatchProcess() {
        setupData();
        Test.startTest();
        Database.executeBatch(new SOM_TransactionalEmailBatch(TransactionalEmailIds));
        Test.stopTest();
        
        List<TransactionalEmail__c> emails = [SELECT Id, Status__c, Template__c FROM TransactionalEmail__c where Id IN :TransactionalEmailIds];
        System.assertEquals(2, emails.size(), 'There should be two transactional emails.');
         
    }
}