unpackaged/main/default/objects/Invoice/fields/Invoice_Timezone_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Timezone_Date__c</fullName>
    <label>Invoice Timezone Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_InvoiceTriggerTest.cls
@isTest
public class SOM_InvoiceTriggerTest {
    public static List<Invoice> invoices = new List<Invoice>();
    @isTest(seeAllData = true)
    static void makeData(){
        List<OrderSummary> los = SOM_testDataFactory.createOrderSummaryBulk(false,SOM_testDataFactory.OrderType.Standard,1);
        FulfillmentOrder fo = SOM_testDataFactory.createFO(los[0]);
        Map<Id, FulfillmentOrder> fotest = SOM_testDataFactory.prepareFulfillmentOrderMap(los[0].id);
        Map<Id,Shipment> test = SOM_testDataFactory.createShipments(fotest);
        Invoice invoice = [SELECT Id , Invoice_Timezone_Date__c,CreatedDate, ReferenceEntityId , InvoiceNumber__c , CurrencyIsoCode from Invoice where ReferenceEntity.type =: SOM_Constants.ORDER_SUMMARY_NAME AND ReferenceEntityId = :los[0].Id];
        invoices.add(invoice);
    }

    @isTest(seeAllData = true)
    public static void callConstructor() {
        makeData();
        System.assertNotEquals(invoices[0].Invoice_Timezone_Date__c,null, 'Invoice_Timezone_Date__c Updated');
    }
}