unpackaged/main/default/objects/Invoice/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/InvoiceCreated__e/InvoiceCreated__e.object-meta.xml
<CustomObject>
    <label>Invoice Created</label>
    <pluralLabel>Invoices Created</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/InvoiceCreated__e/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <label>Invoice Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/isSerialized__c.field-meta.xml
<CustomField>
    <fullName>isSerialized__c</fullName>
    <formula>Product2.isSerialized__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Serialized</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/isSerialized__c.field-meta.xml
<CustomField>
    <fullName>isSerialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Serialized</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SOM_StartCreateInvoicePDFFile_Test.cls
@isTest
public class SOM_StartCreateInvoicePDFFile_Test {
    public static OrderSummary os = new OrderSummary();
    public static List<Invoice> listeInvoice = new List<Invoice>();
    
    public static void setup() {
        List<OrderSummary> los = SOM_testDataFactory.createOrderSummaryBulk(false,SOM_testDataFactory.OrderType.Standard,3);
        os = los[0];
        FulfillmentOrder fo = SOM_testDataFactory.createFO(los[0]);
        List<FulfillmentOrder> lFO = [SELECT Id,DeliveryMethodId,OrderSummaryId,Type,FulfilledFromLocationId,FulfilledFromLocation.VisitorAddress.City,FulfilledFromLocation.VisitorAddress.Street,FulfilledFromLocation.VisitorAddress.PostalCode,
                                      FulfilledFromLocation.VisitorAddress.State,FulfilledFromLocation.VisitorAddress.Country,
                                      FulfilledToName,FulfilledToCity,FulfilledToStreet,FulfilledToPostalCode,FulfilledToState,FulfilledToCountry,
                                      (SELECT Id, FulfillmentOrderLineItemNumber, FulfillmentOrderId, Product2.StockKeepingUnit,
                                       OrderItemSummaryId, Quantity, Product2Id, OrderItemSummary.isSerialized__c FROM FulfillmentOrderLineItems WHERE Type !=: SOM_Constants.DELIVERY_CHARGE)
                                      FROM FulfillmentOrder where Id =: fo.Id];
        Map<Id, FulfillmentOrder> mapIDFO = new Map<Id, FulfillmentOrder>(lFO);
        Map<Id, Shipment> ships = SOM_testDataFactory.createShipments(mapIDFO);
        List<Invoice> invs = [SELECT id, InvoiceNumber__c, CurrencyIsoCode FROM Invoice WHERE ReferenceEntityId =: los[0].Id];
        listeInvoice = invs;
        
    }
    @IsTest(SeeAllData=true)  
    static void TestPushEvent() {
        setup();
        test.enablechangedatacapture();
        test.starttest ();
        InvoiceCreated__e InvoiceEvent = new InvoiceCreated__e (Invoice_Id__c = listeInvoice[0].Id );
        list<Database.SaveResult> sr = eventbus.publish (new List< InvoiceCreated__e > {InvoiceEvent} );
        test.geteventbus().deliver();
        test.stoptest ();
        system.assertEquals(1, sr.size(),'Expected one InvoiceEvent to be published') ;
        system.assertEquals(true, sr[0].isSuccess(),'InvoiceEvent has not been published') ;
        
    }
    
}