unpackaged/main/default/objects/Invoice/fields/Invoice_Timezone_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Timezone_Date__c</fullName>
    <label>Invoice Timezone Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/Sales_Channel_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Sales Channel Mapping</label>
    <pluralLabel>Sales Channel Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <inlineHelpText>Please enter the timezone from the following list : https://help.salesforce.com/s/articleView?id=sf.admin_supported_timezone.htm&amp;type=5</inlineHelpText>
    <label>Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOM_InvoiceHelper.cls
public class SOM_InvoiceHelper {
    public static void updateInvoiceTimezoneDate(List<Invoice> newMap){
        Map<String, Id> InvoiceIds = new Map<String, Id>(); // Map<Invoice Id, Order Summary Id>
        for(Invoice singleInv : newMap){
            InvoiceIds.put(singleInv.Id, singleInv.ReferenceEntityId);
        }
        List<OrderSummary> relatedOrderSummary = [SELECT Id, BillingCountry FROM OrderSummary WHERE Id IN :InvoiceIds.values()];
        Map<String, String> invoiceCountryMap = new Map<String, String>(); // Map<Invoice Id, BillingCountry>
        for(OrderSummary singleOS : relatedOrderSummary){
            for(String singleIn : InvoiceIds.KeySet()){
                if(singleOS.Id == InvoiceIds.get(singleIn)){
                	invoiceCountryMap.put(singleIn, singleOS.BillingCountry);
                }
            }
        }
        List<Sales_Channel_Mapping__mdt> salesChannelMDT = [SELECT Zone__c, Timezone__c FROM Sales_Channel_Mapping__mdt WHERE Zone__c IN :invoiceCountryMap.values()];
        Map<Id, String> invoiceTimeZonesMap = new Map<Id, String>(); // Map<Invoice Id, TimeZone>
        for(String invo : invoiceCountryMap.KeySet()){
            for(Sales_Channel_Mapping__mdt singleMDT : salesChannelMDT){
                if(invoiceCountryMap.get(invo) == singleMDT.Zone__c){
                    invoiceTimeZonesMap.put(invo, singleMDT.Timezone__c);
                }
            }
        }
        for(Invoice singleInvoice : newMap){
            SOM_DateConvertionInput dateinput          = new SOM_DateConvertionInput();
            dateinput.targetTimeZone                   = invoiceTimeZonesMap.get(singleInvoice.Id);
            dateinput.dateToConvert                    = singleInvoice.CreatedDate;
            singleInvoice.Invoice_Timezone_Date__c     = SOM_DateTimeHelper.convertDateTimeByTimeZone(new List<SOM_DateConvertionInput>{dateinput})[0].date();
        }
    }
}