unpackaged/main/default/objects/B2CCustomInput__c/B2CCustomInput__c.object-meta.xml
<CustomObject>
    <description>Buffer object, which is used for create Consent in a trigger context.

When an account is after insert/update, by the B2CContactProcess Flow, a Custom Input is created and trigger the creation of the wanted consent.</description>
    <label>B2CCustomInput</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2CCustomInputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerSettings</label>
</CustomObject>

unpackaged/main/default/objects/TriggerSettings__c/fields/B2CCustomInput__c.field-meta.xml
<CustomField>
    <fullName>B2CCustomInput__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2CCustomInput</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/B2CCustomInput_TDF_TST.cls
/**
 * @author Ulrich M
 * @date 
 * @Type Apex Class
 *****************************************************************************************************************************************************************
 * @description  this class conducts comprehensive testing for the class B2CCustomInput_TDF
 ***************************************************************************************************************************************************************** 
 * @Version : 
 * Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
 * 0.0		|12062023			|.UMNN		|.					|.
*/
@isTest(SeeAllData=false)
public with sharing class B2CCustomInput_TDF_TST {

    @isTest static void testCaseCreateB2CCustomInput() {
        TriggerSettings__c BypassTrigger = new TriggerSettings__c(B2CCustomInput__c = true,
                                               SetupOwnerId = UserInfo.getUserId());
        
        insert BypassTrigger;
        User testUser = [SELECT Id, Name, ProfileId, Profile.Name, isActive//NOPMD
                         FROM User WHERE ID =:UserInfo.getUserId()];
        System.runAs(testUser){
            Test.startTest();
            List<B2CCustomInput__c> b2CCustomInputList = B2CCustomInput_TDF.buildB2CCustomInput(5, true);
            List<B2CCustomInput__c> retrievedB2CCustomInputList = [SELECT Id FROM B2CCustomInput__c];
            Test.stopTest();
            System.assertEquals(b2CCustomInputList.size(), retrievedB2CCustomInputList.size());
        }
    }


    @isTest static void testCaseWithoutCreateB2CCustomInput() {
        TriggerSettings__c BypassTrigger = new TriggerSettings__c(B2CCustomInput__c = true,
                                               SetupOwnerId = UserInfo.getUserId());
        
        insert BypassTrigger;
        User testUser = [SELECT Id, Name, ProfileId, Profile.Name, isActive//NOPMD
                         FROM User WHERE ID =:UserInfo.getUserId()];
        System.runAs(testUser){
            Test.startTest();
            List<B2CCustomInput__c> b2CCustomInputList = B2CCustomInput_TDF.buildB2CCustomInput(5, false);
            List<B2CCustomInput__c> retrievedB2CCustomInputList = [SELECT Id FROM B2CCustomInput__c];
            Test.stopTest();
            System.assertNotEquals(b2CCustomInputList.size(), retrievedB2CCustomInputList.size());
        }
    }
}