unpackaged/main/default/objects/B2CCustomInput__c/B2CCustomInput__c.object-meta.xml
<CustomObject>
    <description>Buffer object, which is used for create Consent in a trigger context.

When an account is after insert/update, by the B2CContactProcess Flow, a Custom Input is created and trigger the creation of the wanted consent.</description>
    <label>B2CCustomInput</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2CCustomInputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2CCustomInput__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2CCustomInputs</relationshipLabel>
    <relationshipName>B2CCustomInputs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CaptureSource__c.field-meta.xml
<CustomField>
    <fullName>CaptureSource__c</fullName>
    <label>CaptureSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BypassTrigger__c/BypassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in order to assign a bypass trigger to any user - Done by</description>
    <label>BypassTrigger</label>
</CustomObject>

unpackaged/main/default/objects/BypassTrigger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bypass Trigger on Account</description>
    <label>Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientAddress__c/fields/AddressTypology__c.field-meta.xml
<CustomField>
    <fullName>AddressTypology__c</fullName>
    <label>Address Typology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>BILLING</fullName>
            </value>
            <value>
                <fullName>DELIVERY</fullName>
            </value>
            <value>
                <fullName>TEMPORARY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Addresses</relationshipLabel>
    <relationshipName>ClientAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AFG</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AGO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AIA</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>ALA</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>ALB</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AND</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>ANT</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>ARE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>ARG</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>ARM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>ASM</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>ATA</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>ATF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>ATG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AUS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AUT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZE</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BDI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BEL</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BEN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BFA</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BGD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BGR</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BHR</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BHS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BIH</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BLM</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BLR</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BLZ</fullName>
                <label>Belize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/SourceLastUpdateDate__c.field-meta.xml
<CustomField>
    <fullName>SourceLastUpdateDate__c</fullName>
    <label>Source Last Update Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Cegid</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Ecommerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCreationDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreationDate__c</fullName>
    <label>Source Creation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ContactPointTypeConsent/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Account Id</description>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Point Type Consents</relationshipLabel>
    <relationshipName>ContactPointTypeConsents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EmailMessage/fields/ToSME__c.field-meta.xml
<CustomField>
    <fullName>ToSME__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define if the email is send for SME</description>
    <label>To SME</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SFSuppressionProcessTest.cls
@isTest(seeAllData=false)
public class SFSuppressionProcessTest {
    
    @TestSetup
    public static void initDate() {
        
        Individual individual = new Individual();
        individual.LastName='individual';
        insert individual;
        
        Account testAcc = new Account();
        testAcc.LastName = 'test';
        testAcc.PersonEmail = 'test@email.com';
        testAcc.PersonIndividualId = individual.Id;
        insert testAcc;
        
        B2CCustomInput__c input = ConsentManagement_TestDataFactory.createB2CCustomInput(true, testAcc.Id);
        input.CaptureSource__c = 'capture';
        update input;
        Case testCase = DataFactoryForTests.createCase();
        testCase.AccountId = testAcc.Id;
        update testCase;
        
        ClientSource__c source1 = new ClientSource__c(
            Source__c = 'SF',
            SourceCode__c = testAcc.Id,
            SourceCreationDate__c = Date.valueOf('2021-05-17'),
            SourceLastUpdateDate__c = DateTime.valueOf('2021-10-16 15:20:41.990679+00:00'),
            Client__c = testAcc.Id
        );
        
        insert source1;
        
        ClientAddress__c address1 = new ClientAddress__c(
            Address1__c = '7007 FRIARS RD STE 513',
            City__c = 'SAN DIEGO',
            Country__c = 'US',
            PostalCode__c = '92108-1142',
            State__c = 'CA',
            AddressTypology__c = 'STANDARD',
            IsValid__c = false,
            Client__c = testAcc.Id
        );
        
        insert address1;
        
        ContactPointTypeConsent conpointtypecons1 = new ContactPointTypeConsent();
        conpointtypecons1.Name = 'EmailConsent1';
        conpointtypecons1.PartyId = testAcc.PersonIndividualId;
        conpointtypecons1.ContactPointType = 'Email';
        conpointtypecons1.PrivacyConsentStatus = 'OptIn';
        conpointtypecons1.EffectiveFrom = System.now().addDays(-10);
        conpointtypecons1.EffectiveTo = null;
        conpointtypecons1.CaptureDate = System.now().addDays(-10);
        conpointtypecons1.CaptureContactPointType = 'Web';
        conpointtypecons1.CaptureSource = 'Test source';
        conpointtypecons1.DoubleConsentCaptureDate = null;
        conpointtypecons1.AccountId__c = testAcc.Id;
        insert conpointtypecons1;
        
        EmailMessage emailWithAllowedDomain = new EmailMessage();
        emailWithAllowedDomain.FromAddress = 'user1@example.com';
        emailWithAllowedDomain.ToSme__c = true;
        emailWithAllowedDomain.RelatedToId = testAcc.Id;
        insert emailWithAllowedDomain;
    }
    
    @isTest
    static void testSuppression() {
        BypassTrigger__c BypassTrigger = new BypassTrigger__c(Account__c = true,
                                               SetupOwnerId = UserInfo.getUserId());
        insert BypassTrigger;
        Account acc = [SELECT Id, LastName, PersonEmail FROM Account LIMIT 1];
        List<SFAnonymizationProcessWrapper> wrapperList = new List<SFAnonymizationProcessWrapper>();
        SFAnonymizationProcessWrapper wrapper = new SFAnonymizationProcessWrapper();
        wrapper.clientIdStr = acc.Id;
        wrapper.objectList = 'Account,Case,ClientAddress,ClientSource,ContactPointTypeConsent,EmailMessage,B2CCustomInput,Entitlement';
        wrapper.timeStamp = '122342452343';
        wrapper.separator = ';';
        wrapperList.add(wrapper);
        Test.StartTest();
        SuppressionSFProcess.initSuppressionProcess(wrapperList);
        Test.StopTest();
        List<ClientSource__c> csList = [SELECT Id FROM ClientSource__c WHERE Client__c =:acc.Id];
        System.assertEquals(true, csList.isEmpty(), 'client source records have been deleted');
    }

}