unpackaged/main/default/objects/Account/fields/Contactable__c.field-meta.xml
<CustomField>
    <fullName>Contactable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contact is contactable on at least 1 channel</description>
    <label>Contactable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FAI__c.field-meta.xml
<CustomField>
    <fullName>FAI__c</fullName>
    <formula>SUBSTITUTE(PersonEmail, LEFT(PersonEmail, FIND(&quot;@&quot;,PersonEmail)),NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FAI</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Is_in_My_Clients__c.field-meta.xml
<CustomField>
    <fullName>Is_in_My_Clients__c</fullName>
    <formula>ClientAdvisor__pc   =  $User.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is in My Clients</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Itelios_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Itelios_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Itelios External Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Local_equals_Main_CA__c.field-meta.xml
<CustomField>
    <fullName>Local_equals_Main_CA__c</fullName>
    <formula>IF( Local_Main_CA__c =  ClientAdvisor__pc, &#39;true&#39;, &#39;false&#39;)</formula>
    <label>Local = Main CA</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Local_equals_Main_Store__c.field-meta.xml
<CustomField>
    <fullName>Local_equals_Main_Store__c</fullName>
    <formula>IF(Local_Main_Store__c =  MainStore__pc, &#39;true&#39;, &#39;false&#39;)</formula>
    <label>Local = Main Store</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Local_Main_CA__c.field-meta.xml
<CustomField>
    <fullName>Local_Main_CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reconnect with locals</description>
    <label>Local Main CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Local_Main_Store__c.field-meta.xml
<CustomField>
    <fullName>Local_Main_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reconnect with locals</description>
    <label>Local Main Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Local_Main_Store_Code__c.field-meta.xml
<CustomField>
    <fullName>Local_Main_Store_Code__c</fullName>
    <formula>Local_Main_Store__r.SourceStoreId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Main Store Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/MainBoutiqueCode__c.field-meta.xml
<CustomField>
    <fullName>MainBoutiqueCode__c</fullName>
    <formula>MainStore__pr.SourceStoreId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Boutique Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/nb_Client_Sources__c.field-meta.xml
<CustomField>
    <fullName>nb_Client_Sources__c</fullName>
    <description>Calculate the number of client source records associated to this client Recourd</description>
    <label># Client Sources</label>
    <summaryForeignKey>ClientSource__c.Client__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NbOfClientAddresses__c.field-meta.xml
<CustomField>
    <fullName>NbOfClientAddresses__c</fullName>
    <label># of Client Addresses</label>
    <summaryForeignKey>ClientAddress__c.Client__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/OriginStoreCode__c.field-meta.xml
<CustomField>
    <fullName>OriginStoreCode__c</fullName>
    <formula>OriginStore__pr.SourceStoreId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Store Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Other_sources_ID__c.field-meta.xml
<CustomField>
    <fullName>Other_sources_ID__c</fullName>
    <description>For DDC / WeChat</description>
    <label>Other sources ID</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PDUE_InternalId__c.field-meta.xml
<CustomField>
    <fullName>PDUE_InternalId__c</fullName>
    <label>PDUE InternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <description>18 digits Salesforce Core ID</description>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Super_Main_CA_SFID__c.field-meta.xml
<CustomField>
    <fullName>Super_Main_CA_SFID__c</fullName>
    <formula>IF( ISBLANK( Local_Main_CA__c ) ,  ClientAdvisor__pc ,  Local_Main_CA__c )</formula>
    <label>Super Main CA SFID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_CAreattribution__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_CAreattribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers CAreattribution</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_HP__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_HP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers HP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/UCRInternalId__c.field-meta.xml
<CustomField>
    <fullName>UCRInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Client UCR Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/UnionId__c.field-meta.xml
<CustomField>
    <fullName>UnionId__c</fullName>
    <label>UnionId</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/What_are_you_interested_in__c.field-meta.xml
<CustomField>
    <fullName>What_are_you_interested_in__c</fullName>
    <label>What are you interested in ?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Brand heritage</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>New launch</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Personalization</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Collaboration</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TNP001_DM_Account.cls
/*     
-------------------------------------------------------------------------------------------
-- - Name               : TNP001_DM_Account  
-- - Author             : Ilhem Zraiga
-- - Description        : Data Managment Account Object
--    
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------------
-- 01/04/2023    IZR    1.0      Intitial version
-------------------------------------------------------------------------------------------
*/
public class TNP001_DM_Account {
    public Static Account getAccountById (Id AccountId){
          Account acc = [SELECT AccountNumber,AccountSource,AllChannelBlocked__pc,AnnualRevenue,Audit_OCAPI_API_Response__pc,B2C_Company_Name__pc,B2C_CustomerList_ID__pc,B2C_CustomerList__pc,B2C_Customer_ID__pc,B2C_Customer_No__pc,B2C_Date_Created__pc,B2C_Date_Last_Modified__pc,B2C_Date_Last_Visited__pc,B2C_Date_Previous_Visit__pc,
                         B2C_Disable_Integration__pc,B2C_Gender_ID__pc,B2C_Instance__pc,B2C_Integration_Status__pc,B2C_Is_Enabled__pc,
                         B2C_Is_Locked__pc,B2C_Job_Title__pc,B2C_Preferred_Locale__pc,B2C_Salutation__pc,B2C_Second_Name__pc,B2C_Site_ID__pc,
                         B2C_Suffix__pc,B2C_Title__pc,B2C_UserName__pc,BillingAddress,BillingCity,BillingCountry,BillingGeocodeAccuracy,
                         BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,Birthday__pc,Birthmonth__pc,Birthyear__pc,
                         Buyer__pc,ClientAdvisorFullName__pc,ClientAdvisorId__pc,ClientAdvisor__pc,ClientType__pc,Comments__pc,Compagny__pc,
                         ContactableByEmail__pc,ContactableByInstantMessaging__pc,ContactableByMailing__pc,ContactableByPhone__pc,Contactable__c,Contactable__pc,CountryIso2__pc,Country__pc,CreatedById,CreatedDate,CurrencyIsoCode,CurrentCluster__pc,Description,EmailValid__pc,
                         Email_Bounce__pc,EReceipt__pc,et4ae5__HasOptedOutOfMobile__pc,et4ae5__Mobile_Country_Code__pc,FAI__c,Fax,FirstName,
                         FirstPurchaseDate__pc,FirstSecondTransactionInterval__pc,FiscalIdentificationNumber__pc,FraudDetection__pc,
                         FullAccount__pc,Gender__pc,Gifter__pc,HardBounce__pc,Id,Industry,IsDeleted,IsPersonAccount,Is_in_My_Clients__c,
                         Itelios_External_Id__c,Jigsaw,JigsawCompanyId,JobTitle__pc,Language__pc,LastActivityDate,LastContactDate__pc,
                         LastModifiedById,LastModifiedDate,LastName,LastPreviousTransactionInterval__pc,LastPurchaseDate__pc,LastReferencedDate,
                         LastUpdateHardBounce__pc,LastUpdateNewsletterSubscription__pc,LastUpdateOptinCalling__pc,LastUpdateOptinEmailing__pc,
                         LastUpdateOptinInstantMessaging__pc,LastUpdateOptinMailing__pc,LastUpdateOptoutCalling__pc,LastUpdateOptoutEmailing__pc,
                         LastUpdateOptoutInstantMessaging__pc,LastUpdateOptoutMailing__pc,LastViewedDate,Last_Platform_Event_Applied_Updates__pc,
                         Last_Platform_Event_Processed_Date__pc,Last_Transaction_SA__pc,Last_Transaction_Store__pc,Last_Update_Pushed_to_B2C_Commerce__pc,
                         LifetimePurchaseAmountAccessories__pc,LifetimePurchaseAmountLuggage__pc,LifetimePurchaseAmountProducts__pc,
                         LifetimePurchaseAmountRepairs__pc,LifetimePurchaseAmountServices__pc,LifeTimePurchaseAmount__pc,LightCurrentCluster__pc,
                         LightPreviousCluster__pc,LINE_Channel_ID__pc,LINE_UID__pc,LocalOrTourist__pc,Local_equals_Main_CA__c,
                         Local_equals_Main_Store__c,Local_Main_CA__c,Local_Main_Store_Code__c,Local_Main_Store__c,Local__pc,MainBoutiqueCode__c,
                         MainStoreId__pc,MainStore__pc,Market__c,MasterRecordId,Name,Nationality__pc,NbOfClientAddresses__c,nb_Client_Sources__c,
                         NewsletterSubscription__pc,NumberOfEmployees,NumberOfVisit__pc,OneTimer__pc,OptinCalling__pc,OptinEmailing__pc,
                         OptinInstantMessaging__pc,OptinMailing__pc,OptoutCalling__pc,OptoutEmailing__pc,OptoutInstantMessaging__pc,
                         OptoutMailing__pc,OriginStoreCode__c,OriginStoreId__pc,OriginStore__pc,OtherEmailValid__pc,OtherEmail__pc,
                         Other_sources_ID__c,OwnerId,Ownership,Owner__pc,ParentId,PassportNumber__pc,PDUE_InternalId__c,PersonAssistantName,
                         PersonAssistantPhone,PersonBirthdate,PersonContactId,PersonDepartment,PersonDoNotCall,PersonEmail,
                         PersonEmailBouncedDate,PersonEmailBouncedReason,PersonHasOptedOutOfEmail,PersonHasOptedOutOfFax,PersonHomePhone,
                         PersonIndividualId,PersonLastCURequestDate,PersonLastCUUpdateDate,PersonLeadSource,PersonMailingAddress,
                         PersonMailingCity,PersonMailingCountry,PersonMailingGeocodeAccuracy,PersonMailingLatitude,PersonMailingLongitude,
                         PersonMailingPostalCode,PersonMailingState,PersonMailingStreet,PersonMobilePhone,PersonOtherAddress,PersonOtherCity,
                         PersonOtherCountry,PersonOtherGeocodeAccuracy,PersonOtherLatitude,PersonOtherLongitude,PersonOtherPhone,
                         PersonOtherPostalCode,PersonOtherState,PersonOtherStreet,PersonTitle,Phone,Phone1Type__pc,Phone1Valid__pc,
                         Phone2Type__pc,Phone2Valid__pc,Phone2__pc,Phone3Type__pc,Phone3Valid__pc,Phone3__pc,PhoneticFullName__pc,PhotoUrl,
                         PreferredStoreId__pc,PreferredStore__pc,PreferredTransactionChannel__pc,PreviousCluster__pc,ProfilCompletionGraph__pc,
                         ProfileCompletion__pc,ProspectA__pc,PurchaserBehaviorMethod__pc,PurchaserStatusSubCategory__pc,PurchaserStatus__pc,
                         Rating,RecordTypeId,Record_ID__c,Repair__pc,Re_Crafted_Seller__pc,RomanizedFirstname__pc,RomanizedLastname__pc,
                         Salutation,SecondAlphabetFirstname__pc,SecondAlphabetLastname__pc,SecondName__pc,SFSC_Contact_Key__pc,ShippingAddress,
                         ShippingCity,ShippingCountry,ShippingGeocodeAccuracy,ShippingLatitude,ShippingLongitude,ShippingPostalCode,
                         ShippingState,ShippingStreet,Sic,SicDesc,Site,Super_Main_CA_SFID__c,Synchronized_SFMC__pc,SystemModstamp,
                         Targeted_Customers_CAreattribution__c,Targeted_Customers_HP__c,Targeted_Customers__c,TickerSymbol,Title__pc,
                         ToDelete__pc,Total_Updates_From_B2C_Commerce__pc,Total_Updates_to_B2C_Commerce__pc,Tourist__pc,Type,UCRCreationDate__pc,
                         UCRInternalId__c,UCRLastUpdateDate__pc,UnionId__c,UnionId__pc,Updated_by_B2C_Platform_Event__pc,ValidityAddress__pc,
                         ValidityAllChannels__pc,ValidityEmail__pc,ValidityInstantMessaging__pc,ValidityPhone__pc,VIP__pc,Website,
                         WebsiteCountry__pc,WebsiteLanguage__pc,WebsiteLocale__pc,WeChat__pc,What_are_you_interested_in__c 
                         FROM Account 
                         Where id =: AccountId];
        return acc;
    }
}