unpackaged/main/default/objects/Account/fields/Local_Main_CA__c.field-meta.xml
<CustomField>
    <fullName>Local_Main_CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reconnect with locals</description>
    <label>Local Main CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_CAreattribution__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_CAreattribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers CAreattribution</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CLT_BatchReattributedClientsNotif_Test.cls
@isTest
private class CLT_BatchReattributedClientsNotif_Test {
    @TestSetup
    static void reattributedClientsBatchPrepareData(){
        CLT_TestDateFactory.createTestRClientConfigurations(true);
        
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);

        Account client = CLT_TestDateFactory.createTestClient('Test client 1', 'Test Last Name1', sa.Id, store.Id, false);
        client.Local_Main_CA__c = sa.Id;
        client.Targeted_Customers_CAreattribution__c = true;
		insert client;
    }

    @isTest
    static void CLT_BatchReattributedClientsNotifTest() {
        Test.startTest();
        CLT_BatchReattributedClientsNotif b = new CLT_BatchReattributedClientsNotif();
        Database.executeBatch(b);
        Test.stopTest();

        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        List<Notification__c> notificationsListAfterBatch = [SELECT Id FROM Notification__c WHERE User__c = :sa.Id];
        System.assertEquals(1, notificationsListAfterBatch.size(), 'Notifications list size is not 1 after batch run');
    }

    @isTest
    static void CLT_SchedBatchReattributedClientsNotifTest() {
        Test.startTest();
        CLT_BatchReattributedClientsNotif schedBatch = new CLT_BatchReattributedClientsNotif();
        String sch = '0 0 23 * * ?'; 
        Id jobId = System.schedule('Test CLT_BatchReattributedClientsNotif Sched', sch, schedBatch);
        CronTrigger cronTrig = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(sch, cronTrig.CronExpression);
        Test.stopTest();
    }
}