unpackaged/main/default/objects/Account/fields/Local_Main_CA__c.field-meta.xml
<CustomField>
    <fullName>Local_Main_CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reconnect with locals</description>
    <label>Local Main CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/MainBoutiqueCode__c.field-meta.xml
<CustomField>
    <fullName>MainBoutiqueCode__c</fullName>
    <formula>MainStore__pr.SourceStoreId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Boutique Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientList__c/fields/AlwaysLimitedList__c.field-meta.xml
<CustomField>
    <fullName>AlwaysLimitedList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Always Limited List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Ascendant__c.field-meta.xml
<CustomField>
    <fullName>Ascendant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ascendant</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ClientListQuery__c.field-meta.xml
<CustomField>
    <fullName>ClientListQuery__c</fullName>
    <label>ClientListQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ContactedSectionDisplayPeriod__c.field-meta.xml
<CustomField>
    <fullName>ContactedSectionDisplayPeriod__c</fullName>
    <label>Contacted Section Display Period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/DisplayToReachOutContactedSection__c.field-meta.xml
<CustomField>
    <fullName>DisplayToReachOutContactedSection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display To Reach Out/Contacted Section</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/DisplayType__c.field-meta.xml
<CustomField>
    <fullName>DisplayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Total Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/InMyStore__c.field-meta.xml
<CustomField>
    <fullName>InMyStore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In My Store</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/IsDarkText__c.field-meta.xml
<CustomField>
    <fullName>IsDarkText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dark Text</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>Order By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>totalTurnover</fullName>
                <label>Total Amount Of Client Purchase</label>
            </value>
            <value>
                <fullName>lastPurchaseDate</fullName>
                <label>Last Purchase Date</label>
            </value>
            <value>
                <fullName>firstName</fullName>
                <label>First Name</label>
            </value>
            <value>
                <fullName>lastName</fullName>
                <label>Last Name</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplay__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplay__c</fullName>
    <label>Specific Field Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplayLabel__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplayLabel__c</fullName>
    <label>Specific Field Display Label</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/StaticList__c.field-meta.xml
<CustomField>
    <fullName>StaticList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Static List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membered</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/VisibilityBasedOnField__c.field-meta.xml
<CustomField>
    <fullName>VisibilityBasedOnField__c</fullName>
    <label>Visibility Based On Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local_Main_CA__c</fullName>
            </value>
            <value>
                <fullName>Last_Transaction_SA__pc</fullName>
            </value>
            <value>
                <fullName>ClientAdvisor__pc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>ClientListMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUT</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>FSS</fullName>
                <label>Free Standing Store</label>
            </value>
            <value>
                <fullName>CCC</fullName>
                <label>Customer Care Center</label>
            </value>
            <value>
                <fullName>SIS</fullName>
                <label>Shop-in-shop</label>
            </value>
            <value>
                <fullName>SUB</fullName>
                <label>Subsidiary Head Quarter</label>
            </value>
            <value>
                <fullName>WHS</fullName>
                <label>Wharehouse</label>
            </value>
            <value>
                <fullName>HDQ</fullName>
                <label>Heardquarter</label>
            </value>
            <value>
                <fullName>POP</fullName>
                <label>Pop Up Store</label>
            </value>
            <value>
                <fullName>ECO</fullName>
                <label>eCommerce store</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ClientLists_Test.cls
/**
 * @author Sarah AYOUN (Balink)
 * @date January,13 2025
 * @Type Apex Test Class
 *****************************************************************************************************************************************************************
 * @description This Test class contains the methods to test those method from CLT_Utils_ClientLists :
 * testSetup : Creation of test user and store
 * TEST METHOD				        		|	DESCRIPTION
 * testBuildDynamicQueryNonSpecific       	|	Test buildDynamicQuery function when client list is not specific
 * testBuildDynamicQuerySpecific       		|	Test buildDynamicQuery function when client list is a specific one
 * testBuildDynamicQueryStoreNoLimit    	|	Test buildDynamicQuery function when client list returned with no limit
 * testBuildDynamicQuerySpecificField       |	Test buildDynamicQuery function when client list is calculated with a specific field
 * testBuildDynamicQueryMemberedList        |	Test buildDynamicQuery function when client list is a membered list
 * 
 * ****************************************************************************************************************************************************************
 * @Version : 
 * Version	|Date of modication	|Modified By	|Related Jira Ticket	|Description of changes			
 * 0.0		|2025/01/13			|.Sarah A.		|.						|.original version
*/
@isTest
private class CLT_Utils_ClientLists_Test {
    @TestSetup
	static void prepareTestData(){
		CLT_TestDateFactory.createTestRClientConfigurations(true);
		User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);

        List<ClientList__c> clientLists = new List<ClientList__c>();

		clientLists.add(CLT_TestDateFactory.createTestClientList('TEST MY VIP', 'AND VIP__pc = \'Yes\' LIMIT 1', false));

        ClientList__c clientList2 = CLT_TestDateFactory.createTestClientList('TEST Client List 2', 'AND FirstName = \'Test client 2\'', false);
		clientList2.InMyStore__c = true;
		clientLists.add(clientList2);

		ClientList__c clientList3 = CLT_TestDateFactory.createTestClientList('TEST Client List 3', 'AND FirstName = \'Test client%\' ORDER BY FirstName DESC LIMIT 1', false);
		clientList3.VisibilityBasedOnField__c = 'Local_Main_CA__c';
		clientLists.add(clientList3);

        insert clientLists;
	}

    @isTest
    static void testBuildDynamicQueryNonSpecific() {
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;
        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        ClientList__c cl = [SELECT Id,OwnerId,Owner.FirstName,CreatedDate,LastModifiedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,
                                    IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c,
                                    DisplayToReachOutContactedSection__c,ContactedSectionDisplayPeriod__c,AlwaysLimitedList__c
                            FROM ClientList__c 
                            WHERE Name = 'TEST MY VIP' LIMIT 1];
        
        String dynamicQuery = CLT_Utils_ClientLists.buildDynamicQuery(cl, sa.Id, 'TST123', false, false);
        System.assertEquals(' AND ClientAdvisor__pc = \'' + sa.Id + '\' AND VIP__pc = \'Yes\'  ORDER BY CreatedDate DESC LIMIT 1', dynamicQuery, 'CLT_Utils_ClientLists_Test:testBuildDynamicQueryNonSpecific: dynamic query not calculated as expected');
    }

    @isTest                                                                     
    static void testBuildDynamicQuerySpecific() {
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;
        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        ClientList__c cl = [SELECT Id,OwnerId,Owner.FirstName,CreatedDate,LastModifiedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,
                                    IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c,
                                    DisplayToReachOutContactedSection__c,ContactedSectionDisplayPeriod__c,AlwaysLimitedList__c
                            FROM ClientList__c 
                            WHERE Name = 'TEST MY VIP' LIMIT 1];
        
        String dynamicQuery = CLT_Utils_ClientLists.buildDynamicQuery(cl, sa.Id, 'TST123', true, true);
        System.assertEquals(' AND ClientAdvisor__pc = \'' + sa.Id + '\' AND VIP__pc = \'Yes\'  ORDER BY CreatedDate DESC ', dynamicQuery, 'CLT_Utils_ClientLists_Test:testBuildDynamicQuerySpecific: dynamic query not calculated as expected');
    }

    @isTest
    static void testBuildDynamicQueryStoreNoLimit() {
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;
        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        ClientList__c cl = [SELECT Id,OwnerId,Owner.FirstName,CreatedDate,LastModifiedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,
                                    IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c,
                                    DisplayToReachOutContactedSection__c,ContactedSectionDisplayPeriod__c,AlwaysLimitedList__c
                            FROM ClientList__c 
                            WHERE Name = 'TEST Client List 2' LIMIT 1];
        
        String dynamicQuery = CLT_Utils_ClientLists.buildDynamicQuery(cl, sa.Id, 'TST123', false, true);
        System.assertEquals(' AND MainBoutiqueCode__c = \'TST123\' AND FirstName = \'Test client 2\' ORDER BY CreatedDate DESC LIMIT 200', dynamicQuery, 'CLT_Utils_ClientLists_Test:testBuildDynamicQueryStoreNoLimit: dynamic query not calculated as expected');
    }

    @isTest
    static void testBuildDynamicQuerySpecificField() {
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;
        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        ClientList__c cl = [SELECT Id,OwnerId,Owner.FirstName,CreatedDate,LastModifiedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,
                                    IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c,
                                    DisplayToReachOutContactedSection__c,ContactedSectionDisplayPeriod__c,AlwaysLimitedList__c
                            FROM ClientList__c 
                            WHERE Name = 'TEST Client List 3' LIMIT 1];
        
        String dynamicQuery = CLT_Utils_ClientLists.buildDynamicQuery(cl, sa.Id, 'TST123', false, true);
        System.assertEquals(' AND Local_Main_CA__c = \'' + sa.Id + '\' AND FirstName = \'Test client%\' ORDER BY FirstName DESC , CreatedDate DESC LIMIT 1', dynamicQuery, 'CLT_Utils_ClientLists_Test:testBuildDynamicQuerySpecificField: dynamic query not calculated as expected');
    }

    @isTest
    static void testBuildDynamicQueryMemberedList() {
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;
        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        Store__c store = [SELECT Id FROM Store__c WHERE SourceStoreId__c = :'TST123'];
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);

        CLT_ClientList cltClientList = new CLT_ClientList();
		System.runAs(sa) {
			ClientList__c clientList = new ClientList__c (
            Name = 'test membered client list',
            Type__c = 'Membered'
			);
            insert clientList;

			ClientListMember__c clm = new ClientListMember__c(
				ClientList__c = clientList.Id,
				Client__c = client.Id
			);
			insert clm;

			Test.startTest();

			String memberedUnreachedQuery = CLT_Utils_ClientLists.buildDynamicQuery(clientList, sa.Id, 'TST123', true, true);
			List<Account> queriedMembersList = Database.query('SELECT Id FROM Account WHERE IsPersonAccount = TRUE ' + memberedUnreachedQuery); 
			System.assertEquals(1, queriedMembersList.size(), 'queried membbers list is not 1');
		
			Test.stopTest();
        }
    }
}