unpackaged/main/default/objects/Account/fields/NewWeChatClient__c.field-meta.xml
<CustomField>
    <fullName>NewWeChatClient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New WeChat Client</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/wechat_digitalcard__c.field-meta.xml
<CustomField>
    <fullName>wechat_digitalcard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WeChat DigitalCard</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
    
    
        
</RecordType>

unpackaged/main/default/classes/BL_WECHAT_Register.cls
global class BL_WECHAT_Register extends BL_WS_Request implements BL_WS_Interfaces.DispatchablePOST {
    /*
        Merge according the CellPhone: phone + indicator
        Search the Basic WeChat Account according the union id and merge / delete it
    */
    global Object executePOST() {       
        Savepoint sp = Database.setSavepoint();
        Id rtId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

        try 
        {
            Account client;
            client = BL_WECHAT_Utils.createWeChatAccount(requestBody);
            
            // Fields
            client.wechat_digitalcard__c = true;
            client.NewWeChatClient__c = false;
            
            // Upsert
            BL_WECHAT_Utils.upsertClient(client);
            //Create and upsert the address
            BL_WECHAT_Utils.createWeChatClientAddress(requestBody, client.Id);

            return BL_WECHAT_Utils.getClient(client.Id);
        }
        catch(Exception ex){
            Database.rollback(sp);
            throw new BL_Exceptions.CLTException(ex.getMessage(), ex.getMessage());
        }
    }  
}