unpackaged/main/default/objects/Account/fields/OptinCGI__c.field-meta.xml
<CustomField>
    <fullName>OptinCGI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Optin CGI</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/B2CCustomInput__c.object-meta.xml
<CustomObject>
    <description>Buffer object, which is used for create Consent in a trigger context.

When an account is after insert/update, by the B2CContactProcess Flow, a Custom Input is created and trigger the creation of the wanted consent.</description>
    <label>B2CCustomInput</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2CCustomInputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2CCustomInput__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2CCustomInputs</relationshipLabel>
    <relationshipName>B2CCustomInputs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CaptureContactPointType__c.field-meta.xml
<CustomField>
    <fullName>CaptureContactPointType__c</fullName>
    <label>CaptureContactPointType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CaptureSource__c.field-meta.xml
<CustomField>
    <fullName>CaptureSource__c</fullName>
    <label>CaptureSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CustomContactPointType__c.field-meta.xml
<CustomField>
    <fullName>CustomContactPointType__c</fullName>
    <label>CustomContactPointType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/EmailConsent__c.field-meta.xml
<CustomField>
    <fullName>EmailConsent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EmailConsent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/OptinCGI__c.field-meta.xml
<CustomField>
    <fullName>OptinCGI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OptinCGI</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>SubscriptionName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/B2CCustomInput_TDF.cls
/**
 * @author Ulrich M
 * @date 
 * @Type Apex Class
 *****************************************************************************************************************************************************************
 * @description 
 ***************************************************************************************************************************************************************** 
 * @Version : 
 * Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
 * 0.0		|12062023			|.UMNN		|.					|.
*/
public with sharing class B2CCustomInput_TDF {

    public static List<B2CCustomInput__c> buildB2CCustomInput(Integer numRecords, Boolean shouldBeInserted) {
        List<B2CCustomInput__c> b2ccustomInputToBeCreated = new List<B2CCustomInput__c>();
        for(Integer i=0; i<numRecords; i++) {
            Account acc = (Account)TestDataFactory.createSObject('Account');
            B2CCustomInput__c customInput = new B2CCustomInput__c(
                CaptureContactPointType__c = 'Web',
                CaptureSource__c = 'Account Creation'+i,
                EmailConsent__c = false,
                OptinCGI__c = true,
                SubscriptionName__c = '',
                CustomContactPointType__c = '0021',
                AccountId__c = acc.Id
            );
            b2ccustomInputToBeCreated.add(customInput);
        }
        
        if(!b2ccustomInputToBeCreated.isEmpty() && shouldBeInserted) {
            insert b2ccustomInputToBeCreated;
        }

        return b2ccustomInputToBeCreated;
    }
}