unpackaged/main/default/objects/Account/fields/OptinCGI__c.field-meta.xml
<CustomField>
    <fullName>OptinCGI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Optin CGI</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/B2CCustomInput__c.object-meta.xml
<CustomObject>
    <description>Buffer object, which is used for create Consent in a trigger context.

When an account is after insert/update, by the B2CContactProcess Flow, a Custom Input is created and trigger the creation of the wanted consent.</description>
    <label>B2CCustomInput</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2CCustomInputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2CCustomInput__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>B2CCustomInputs</relationshipLabel>
    <relationshipName>B2CCustomInputs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CaptureContactPointType__c.field-meta.xml
<CustomField>
    <fullName>CaptureContactPointType__c</fullName>
    <label>CaptureContactPointType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CaptureSource__c.field-meta.xml
<CustomField>
    <fullName>CaptureSource__c</fullName>
    <label>CaptureSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/CustomContactPointType__c.field-meta.xml
<CustomField>
    <fullName>CustomContactPointType__c</fullName>
    <label>CustomContactPointType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/EmailConsent__c.field-meta.xml
<CustomField>
    <fullName>EmailConsent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EmailConsent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/OptinCGI__c.field-meta.xml
<CustomField>
    <fullName>OptinCGI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OptinCGI</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCustomInput__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>SubscriptionName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
    
    
        
</RecordType>

unpackaged/main/default/classes/B2CCustomInput_UTL_TST.cls
/**
 * @author Ulrich M
 * @date 
 * @Type Apex Class
 *****************************************************************************************************************************************************************
 * @description this class conducts comprehensive testing for the class B2CCustomInput_UTL
 ***************************************************************************************************************************************************************** 
 * @Version : 
 * Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
 * 0.0		|12062023			|.UMNN		|.					|.
*/
@IsTest(SeeAllData=false)
public with sharing class B2CCustomInput_UTL_TST {

    @TestSetup
    static void makeData(){

        Individual currentIndividual = Individual_TDF.buildIndividual(1, true)[0];
        RecordType personAccount = [Select Id, Name from recordType where IsPersonType = true limit 1];//NOPMD
        Account acc = (Account)TestDataFactory.createSObject('Account');
        acc.LastName='acc';
		acc.PersonEmail = 'Account.test3@gmail.com';
        acc.B2C_Customer_ID__pc = 'abKveEa2dsfdsnfksd4s00';
		acc.B2C_Customer_No__pc = '000175465456d000';
        acc.RecordTypeId  = personAccount.Id;
        acc.OptinCGI__c = true;
        update acc;

        B2CCustomInput__c customInput = B2CCustomInput_TDF.buildB2CCustomInput(1, false)[0];
        customInput.AccountId__c = acc.Id;
        insert customInput;   
    }


    @isTest
    static void testCreateCustomer() {
        User testUser = [SELECT Id, Name, ProfileId, Profile.Name, isActive //NOPMD
                         FROM User WHERE ID =:UserInfo.getUserId()];
        System.runAs(testUser){
            Test.startTest();
            List<B2CCustomInput__c> customInputList = [SELECT Id, CustomContactPointType__c, SubscriptionName__c, AccountId__c, //NOPMD
                                                       OptinCGI__c, EmailConsent__c, CaptureSource__c, CaptureContactPointType__c 
                                                       FROM B2CCustomInput__c];
            B2CCustomInput_UTL utils = new B2CCustomInput_UTL(customInputList);
            Test.stopTest();
            System.assertEquals(true, !utils.authFormList.isEmpty());
            System.assertEquals(true, !utils.authFormTextList.isEmpty());
            System.assertEquals(true, !utils.authFormConsentList.isEmpty());
            System.assertEquals(true, !utils.individualIdList.isEmpty());
            System.assertEquals(true, !utils.accs.isEmpty());
        }
    }

    @isTest
    static void testUpdateCustomer() {
        User testUser = [SELECT Id, Name, ProfileId, Profile.Name, isActive //NOPMD
                         FROM User WHERE ID =:UserInfo.getUserId()];
        System.runAs(testUser){
            Test.startTest();
            Account retrievedAccount = [SELECT Id, PersonIndividualId, OptinCGI__c FROM Account][0];//NOPMD
            B2CCustomInput__c customInput = B2CCustomInput_TDF.buildB2CCustomInput(1, false)[0];
            customInput.AccountId__c = retrievedAccount.Id;
            customInput.OptinCGI__c = true;
            insert customInput;  
            List<B2CCustomInput__c> customInputList = new List<B2CCustomInput__c>();
            customInputList.add(customInput);
            B2CCustomInput_UTL utils = new B2CCustomInput_UTL(customInputList);
            Test.stopTest();
            System.assert(true, true);
        }
    }
}