unpackaged/main/default/objects/Account/fields/Targeted_CAreattribution_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Targeted_CAreattribution_Contact_Date__c</fullName>
    <label>Targeted CAreattribution Contact Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_CAreattribution__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_CAreattribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers CAreattribution</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_CAreattribution_Date__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_CAreattribution_Date__c</fullName>
    <label>Targeted Customers CAreattribution Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Targeted_Customers_CAreattribution_Notif__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Customers_CAreattribution_Notif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Targeted Customers CAreattribution Notif</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ClientTrigger.cls
public class CLT_Utils_ClientTrigger {
    public static void updateTargetedCustomersCAreattributionDateAndNotify(List<Account> newClients, Map<Id, Account> oldClientsMap) {
        for(Account client : newClients) {
            if(client.Targeted_Customers_CAreattribution__c && (!oldClientsMap.containsKey(client.Id) ||
                (oldClientsMap.containsKey(client.Id) && !oldClientsMap.get(Client.Id).Targeted_Customers_CAreattribution__c))) {
                client.Targeted_Customers_CAreattribution_Date__c = Date.today();
                client.Targeted_Customers_CAreattribution_Notif__c = true;
            }
        }
    }

    public static void updateTargetedCAreattributionContactDate(List<Account> newClients, Map<Id, Account> oldClientsMap) {
        for(Account client : newClients) {
            if(client.Targeted_Customers_CAreattribution__c && client.Targeted_Customers_CAreattribution_Date__c != null && client.LastContactDate__pc != null && 
                (client.Targeted_CAreattribution_Contact_Date__c == null || client.Targeted_CAreattribution_Contact_Date__c <= client.Targeted_Customers_CAreattribution_Date__c) && 
                (!oldClientsMap.containsKey(client.Id) || (oldClientsMap.containsKey(client.Id) && (oldClientsMap.get(Client.Id).LastContactDate__pc == null || oldClientsMap.get(Client.Id).LastContactDate__pc < client.LastContactDate__pc)))) {
                client.Targeted_CAreattribution_Contact_Date__c = client.LastContactDate__pc;
            }
        }
    }
}