unpackaged/main/default/objects/Account/fields/UCRInternalId__c.field-meta.xml
<CustomField>
    <fullName>UCRInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Client UCR Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/AppointmentService__c.object-meta.xml
<CustomObject>
    <label>Appointment Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointment Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AppointmentService__c/fields/BookingMethod__c.field-meta.xml
<CustomField>
    <fullName>BookingMethod__c</fullName>
    <label>Booking Method</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/fields/BooxiId__c.field-meta.xml
<CustomField>
    <fullName>BooxiId__c</fullName>
    <externalId>true</externalId>
    <label>Booxi Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/fields/MerchantId__c.field-meta.xml
<CustomField>
    <fullName>MerchantId__c</fullName>
    <label>Merchant Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AppointmentService__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Appointment Services</relationshipLabel>
    <relationshipName>AppointmentServices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/ClientBooking__c.object-meta.xml
<CustomObject>
    <label>Client Booking</label>
    <nameField>
        <displayFormat>CB-{00000}</displayFormat>
        <label>Client Booking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientBooking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Bookings</relationshipLabel>
    <relationshipName>ClientBookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expecting</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
            </value>
            <value>
                <fullName>NoShow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/BookingMethod__c.field-meta.xml
<CustomField>
    <fullName>BookingMethod__c</fullName>
    <label>Booking Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/ClientCommunication__c.field-meta.xml
<CustomField>
    <fullName>ClientCommunication__c</fullName>
    <description>This variable describes how client communications should be managed.
- DoNotSend
Do not send any message to the client or attendee of this booking.

- ClientOnly
Only send messages to the client of the booking.</description>
    <label>Client Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DoNotSend</fullName>
            </value>
            <value>
                <fullName>ClientOnly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/ConfirmationNumber__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationNumber__c</fullName>
    <description>Contains a booking&#39;s confirmation number</description>
    <externalId>true</externalId>
    <label>Confirmation Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/CreatedBy__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy__c</fullName>
    <label>CreatedBy</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/CreatedOn__c.field-meta.xml
<CustomField>
    <fullName>CreatedOn__c</fullName>
    <label>CreatedOn</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
    
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/isCompleted__c.field-meta.xml
<CustomField>
    <fullName>isCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCompleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/isScheduled__c.field-meta.xml
<CustomField>
    <fullName>isScheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isScheduled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/MerchantId__c.field-meta.xml
<CustomField>
    <fullName>MerchantId__c</fullName>
    <label>MerchantId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>AppointmentService__c</referenceTo>
    <relationshipLabel>Client Bookings</relationshipLabel>
    <relationshipName>ClientBookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/StaffCode__c.field-meta.xml
<CustomField>
    <fullName>StaffCode__c</fullName>
    <formula>User__r.StaffCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StaffCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientBooking__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Client Bookings</relationshipLabel>
    <relationshipName>Client_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>TF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the store</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/StoreLabel__c.field-meta.xml
<CustomField>
    <fullName>StoreLabel__c</fullName>
    <label>Store Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/UCRInternalId__c.field-meta.xml
<CustomField>
    <fullName>UCRInternalId__c</fullName>
    <externalId>true</externalId>
    <label>UCR Internal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/booxiId__c.field-meta.xml
<CustomField>
    <fullName>booxiId__c</fullName>
    <description>Id of Booxi Staff</description>
    <externalId>true</externalId>
    <inlineHelpText>Id of Booxi Staff</inlineHelpText>
    <label>booxi Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StaffCode__c.field-meta.xml
<CustomField>
    <fullName>StaffCode__c</fullName>
    <label>Staff Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/UCRInternalId__c.field-meta.xml
<CustomField>
    <fullName>UCRInternalId__c</fullName>
    <externalId>true</externalId>
    <label>UCR Internal Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ClientBooking_TestDataFactory.cls
/* @author Paul Louis MONY
 * @date May,15th 2024
 * @Type Apex Test Class 
 *****************************************************************************************************************************************************************
 * @description : This class is responsible for creating instances of data objects for all test classes, 
 * 				in order to improve readability and reusability of code components 
 * 
 ***************************************************************************************************************************************************************** 
 * 0.0      |2024/05/17         |.PLM       |..SFMC-425         |.Original Version
*/
@isTest
public class ClientBooking_TestDataFactory {
	@testSetup
    static void testData(){
        ClientBooking_TestDataFactory.createTestSetupData();
    }
    
    public static void createTestSetupData(){
        //Create Account
        Account testAccount = new Account(
            Firstname = 'test',
            LastName = 'Test Account',
            personEmail = 'test@test.com',
			RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
        );
        insert testAccount;
        
        //Create User
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];

        // Create the user
        User u = new User(
            FirstName = 'Test',
            LastName = 'User',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com' + System.currentTimeMillis(), // Ensure unique username
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            BooxiId__c = '1111',
            StaffCode__c = 'US01'
        );
        insert u;

        //Create Store
        Store__c s = new Store__c(
            BooxiId__c = '1111',
            Country__c = 'US',
            Name = 'RimowaStore',
            StoreLabel__c= 'RimowaStore',
            UCRInternalId__c = '1111'
        );
        insert s;

        //Create Service
        AppointmentService__c service = new AppointmentService__c(
            BookingMethod__c = 'Appointment',
            BooxiId__c = '1111',
            Duration__c = 30,
            MerchantId__c = '1111',
            Name = 'Product',
            Status__c = 'Online',
            Store__c = s.id
        );
        insert service;
    }
    public static Account getTestAccount(){
        return [Select Id 
        from Account 
        where personEmail ='test@test.com' 
        and firstname = 'test' 
        and lastname = 'Test Account' Limit 1];
    }
    public static User getTestUser(){
        return [Select Id 
        From User 
        where email = 'testuser@example.com' Limit 1];
    }
    public static Store__c getTestStore(){
        return [Select Id 
        From Store__c 
        Where booxiId__c = '1111' Limit 1];
    }
    public static AppointmentService__c getTestService(){
        return[Select Id
        From AppointmentService__c
        Where booxiId__c = '1111' Limit 1];
    }
    
    public static ClientBooking__c createClientBooking(DateTime AppointmentDateTime){
        Account acc = ClientBooking_TestDataFactory.getTestAccount();
        User us = ClientBooking_TestDataFactory.getTestUser();
        Store__c st = ClientBooking_TestDataFactory.getTestStore();
        AppointmentService__c service = ClientBooking_TestDataFactory.getTestService();
        ClientBooking__c cb = new ClientBooking__c(
            Account__c=acc.id,
            AccountId__c = acc.Id,
            Attendance__c = 'Expecting',
            BookingMethod__c = 'Appointment',
            ClientCommunication__c = 'ClientOnly',
            ConfirmationNumber__c = 'testClass01',
            CreatedBy__c = 'Staff',
            CreatedOn__c = datetime.now(),
            Duration__c = 30,
            Email__c = 'test@test.com',
            Firstname__c = 'test',
            isCompleted__c = false,
            isScheduled__c = false,
            Language__c = 'eng',
            Lastname__c = 'Test Account',
            MerchantAddressCity__c = 'test',
            MerchantAddressCountry__c = 'US',
            MerchantAddressPostalCode__c = '1111',
            MerchantAddressStreet__c = 'test street',
            MerchantId__c = '1111',
            Origin__c = 'InStore',
            PhoneNumber__c = '+33778676272',
            Service__c = service.id,
            ServiceId__c = '1111',
            StaffId__c = '1111',
            StartsOn__c = AppointmentDateTime,
            Status__c = 'Approved',
            Store__c = st.id,
            TimeZone__c = 'Europe/Paris',
            User__c = us.id
        );
		insert cb;
		return cb;        
    }
}