unpackaged/main/default/objects/Account/fields/wechat_external_id__c.field-meta.xml
<CustomField>
    <fullName>wechat_external_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Wechat External Id</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/wechat_union_id__c.field-meta.xml
<CustomField>
    <fullName>wechat_union_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Wechat Union Id</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/User/fields/StaffCode__c.field-meta.xml
<CustomField>
    <fullName>StaffCode__c</fullName>
    <label>Staff Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/WeChat_Work_User_Id__c.field-meta.xml
<CustomField>
    <fullName>WeChat_Work_User_Id__c</fullName>
    <label>WeChat Work User Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/wechat_sa_client__c/wechat_sa_client__c.object-meta.xml
<CustomObject>
    <label>WeChat SA Client</label>
    <nameField>
        <displayFormat>BIND-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat SA Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/wechat_sa_client__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WeChat SA Clients</relationshipLabel>
    <relationshipName>WeChat_SA_Clients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/wechat_sa_client__c/fields/SA__c.field-meta.xml
<CustomField>
    <fullName>SA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WeChat_SA_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BL_WECHAT_Bind_Test.cls
@isTest
public class BL_WECHAT_Bind_Test {

    @isTest
    static void test_bindExecutePost() {

        try{
            Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            User u = new User();
            u.UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@rimowa.com';
            u.Email ='test@rimowa.com';
            u.LastName = 'test';
            u.ProfileId = sysAdmin.Id;
            u.LocaleSidKey = 'en_US';
            u.LanguageLocaleKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.EmailEncodingKey = 'UTF-8';
            u.Alias = 'user4t_';
            u.StoreCode__c = 'FR01';
            u.StaffCode__c = '';
            u.WeChat_Work_User_Id__c = 'memberId1234';
            insert u;
    
            System.runAs(u){
                BL_WECHAT_Bind blRequest = new BL_WECHAT_Bind();
                RestRequest req = new RestRequest();
                req.requestURI = 'wechat/v0/externalcontact/bind';
                req.httpMethod = 'POST';
                req.requestBody = Blob.valueOf('{ "last_name":"test","memberid": "USER1234","union_id": "testSarahUnionid3","externalid": "accExternalId123","phone":"0123456789"}');
                RestContext.request = req;
                blRequest.init('wechat/v0/externalcontact/bind',  '/externalcontact/bind', null);
                Map<String,Object> data = new Map<String,Object>{
                    'last_name'=>'test',
                    'union_id'=>'testSarahUnionid3',
                    'externalid'=>'accExternalId123',
                    'storeCode'=>'FR01',
                    'country_code'=>'0033',
                    'mobile'=>'741791080'
                };
                System.debug('my data ->>'+data);
                Account myClient;
                myClient = BL_WECHAT_Utils.createWeChatAccount(data);
                myClient.wechat_external_id__c = 'accExternalId123';
                System.debug('my client ->>'+myClient);
                BL_WECHAT_Utils.upsertClient(myClient);
        
                Object o = blRequest.executePOST();
            }
        }catch(Exception ex){
            System.debug('ex -->>'+ex);
        }
        
    }

    // @isTest
    // static void test_bind2() {

    //     BL_WECHAT_Bind blRequest = new BL_WECHAT_Bind();
    //     RestRequest req = new RestRequest();
    //     req.requestURI = 'wechat/v0/externalcontact/bind';
    //     req.httpMethod = 'POST';
    //     req.requestBody = Blob.valueOf('{ "last_name":"test","memberid": "USER1234","union_id": "testSarahUnionid3","externalid": "aerytreointreghjgffmhgf","phone":"0123456789"}');
    //     RestContext.request = req;
    //     blRequest.init('wechat/v0/externalcontact/bind',  '/externalcontact/bind', null);
    //     Map<String,Object> data = new Map<String,Object>{
    //         'last_name'=>'',
    //         'union_id'=>'testSarahUnionid3',
    //         'externalid'=>'aerytreointreghjgffmhgf',
    //         'storeCode'=>'FR01',
    //         'country_code'=>'0033',
    //         'mobile'=>'741791080'
    //     };
    //     System.debug('my data ->>'+data);
    //     Account myClient;
    //     myClient = BL_WECHAT_Utils.createWeChatAccount(data);
    //     System.debug('my client ->>'+myClient);
    //     BL_WECHAT_Utils.upsertClient(myClient);


    //     Object o = blRequest.executePOST();

    // }

    @isTest
    static void test_bindExecuteDelete() {
        
		Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
		User u = new User();
		u.UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@rimowa.com';
		u.Email ='test@rimowa.com';
		u.LastName = 'test';
		u.ProfileId = sysAdmin.Id;
		u.LocaleSidKey = 'en_US';
		u.LanguageLocaleKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.EmailEncodingKey = 'UTF-8';
		u.Alias = 'user4t_';
		u.StoreCode__c = 'FR01';
        u.StaffCode__c = '';
        u.WeChat_Work_User_Id__c = 'memberId1234';
		insert u;

        System.runAs(u){
            // Account acc = new Account();
            // acc.Salutation = '02';    
            // acc.FirstName = 'firstName';
            // acc.LastName = 'lastName';
            // acc.wechat_union_id__c='testEliUnionid123';
            // acc.wechat_external_id__c='testblabla';
            // insert acc;

            Map<String,Object> data = new Map<String,Object>{
                'last_name'=>'test',
                'union_id'=>'testSarahUnionid3',
                // 'externalid'=>'aerytreointreghjgffmhgf',
                'storeCode'=>'FR01',
                'country_code'=>'0033',
                'mobile'=>'741791080'
            };
            System.debug('my data ->>'+data);
            Account acc;
            acc = BL_WECHAT_Utils.createWeChatAccount(data);
            acc.wechat_external_id__c = 'accExternalId123';
            System.debug('my client ->>'+acc);
            BL_WECHAT_Utils.upsertClient(acc);
            System.debug('my client after upsert in delete -->> '+acc);
            Account acc2 = [select id, LastName from Account where wechat_union_id__c = 'testSarahUnionid3'];
            System.debug('my client acc2-->> '+acc2);

            Map<String,Object> dataToBind = new Map<String,Object>{
                'clientid' => acc.Id,
                'memberid'=> u.WeChat_Work_User_Id__c,
                'id'=> u.Id
            };
            WeChat_SA_Client__c bind = new WeChat_SA_Client__c();
            bind.SA__c = u.Id;
            bind.Client__c =acc.Id;
            insert bind;
            
            BL_WECHAT_Bind blRequest = new BL_WECHAT_Bind();
            RestRequest req = new RestRequest();
            req.requestURI = 'wechat/v0/externalcontact/bind';
            req.httpMethod = 'DELETE';
            Map<String, String> parameters =  new  Map<String, String>();
            parameters.put('union_id', acc.wechat_union_id__c);
            parameters.put('externalid', acc.wechat_external_id__c);
            parameters.put('memberid', u.WeChat_Work_User_Id__c);
            req.params.putAll(parameters);
            System.debug('req params -->> '+req.params);
            RestContext.request = req;
            blRequest.init('wechat/v0/externalcontact/bind',  '/externalcontact/bind', null);
     
            Object o = blRequest.executeDELETE();
       }
    }

    @isTest
    static void test_bindExecuteDelete2() {
        try{
            Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            
            User u = new User();
            u.UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@rimowa.com';
            u.Email ='test@rimowa.com';
            u.LastName = 'test';
            u.ProfileId = sysAdmin.Id;
            u.LocaleSidKey = 'en_US';
            u.LanguageLocaleKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.EmailEncodingKey = 'UTF-8';
            u.Alias = 'user4t_';
            u.StoreCode__c = 'FR01';
            u.StaffCode__c = '';
            u.WeChat_Work_User_Id__c = 'memberId1234';
            insert u;
    
            System.runAs(u){
                // Account acc = new Account();
                // acc.Salutation = '02';    
                // acc.FirstName = 'firstName';
                // acc.LastName = 'lastName';
                // acc.wechat_union_id__c='testEliUnionid123';
                // acc.wechat_external_id__c='testblabla';
                // insert acc;
    
                Map<String,Object> data = new Map<String,Object>{
                    'last_name'=>'test',
                    'union_id'=>'testSarahUnionid3',
                    // 'externalid'=>'aerytreointreghjgffmhgf',
                    'storeCode'=>'FR01',
                    'country_code'=>'0033',
                    'mobile'=>'741791080'
                };
                System.debug('my data ->>'+data);
                Account acc;
                acc = BL_WECHAT_Utils.createWeChatAccount(data);
                acc.wechat_external_id__c = 'accExternalId123';
                System.debug('my client ->>'+acc);
                BL_WECHAT_Utils.upsertClient(acc);
                System.debug('my client after upsert in delete -->> '+acc);
                Account acc2 = [select id, LastName from Account where wechat_union_id__c = 'testSarahUnionid3'];
                System.debug('my client acc2-->> '+acc2);
    
                Map<String,Object> dataToBind = new Map<String,Object>{
                    'clientid' => acc.Id,
                    'memberid'=> u.WeChat_Work_User_Id__c,
                    'id'=> u.Id
                };
                WeChat_SA_Client__c bind = new WeChat_SA_Client__c();
                bind.SA__c = u.Id;
                bind.Client__c =acc.Id;
                insert bind;
                
                BL_WECHAT_Bind blRequest = new BL_WECHAT_Bind();
                RestRequest req = new RestRequest();
                req.requestURI = 'wechat/v0/externalcontact/bind';
                req.httpMethod = 'DELETE';
                Map<String, String> parameters =  new  Map<String, String>();
                parameters.put('union_id', acc.wechat_union_id__c);
                parameters.put('externalid', acc.wechat_external_id__c);
                // parameters.put('memberid', u.WeChat_Work_User_Id__c);
                req.params.putAll(parameters);
                RestContext.request = req;
                blRequest.init('wechat/v0/externalcontact/bind',  '/externalcontact/bind', null);
         
                Object o = blRequest.executeDELETE();
           }
        } catch(Exception ex){
            System.debug('ex -->>'+ex);
        }
    }
    @isTest
    static void test_bindExecuteDelete3() {
        try{
            Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            
            User u = new User();
            u.UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@rimowa.com';
            u.Email ='test@rimowa.com';
            u.LastName = 'test';
            u.ProfileId = sysAdmin.Id;
            u.LocaleSidKey = 'en_US';
            u.LanguageLocaleKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.EmailEncodingKey = 'UTF-8';
            u.Alias = 'user4t_';
            u.StoreCode__c = 'FR01';
            u.StaffCode__c = '';
            u.WeChat_Work_User_Id__c = 'memberId1234';
            insert u;
    
            System.runAs(u){
                // Account acc = new Account();
                // acc.Salutation = '02';    
                // acc.FirstName = 'firstName';
                // acc.LastName = 'lastName';
                // acc.wechat_union_id__c='testEliUnionid123';
                // acc.wechat_external_id__c='testblabla';
                // insert acc;
    
                Map<String,Object> data = new Map<String,Object>{
                    'last_name'=>'test',
                    'union_id'=>'testSarahUnionid3',
                    // 'externalid'=>'aerytreointreghjgffmhgf',
                    'storeCode'=>'FR01',
                    'country_code'=>'0033',
                    'mobile'=>'741791080'
                };
                System.debug('my data ->>'+data);
                Account acc;
                acc = BL_WECHAT_Utils.createWeChatAccount(data);
                acc.wechat_external_id__c = 'accExternalId123';
                System.debug('my client ->>'+acc);
                BL_WECHAT_Utils.upsertClient(acc);
                System.debug('my client after upsert in delete -->> '+acc);
                Account acc2 = [select id, LastName from Account where wechat_union_id__c = 'testSarahUnionid3'];
                System.debug('my client acc2-->> '+acc2);
    
                Map<String,Object> dataToBind = new Map<String,Object>{
                    'clientid' => acc.Id,
                    'memberid'=> u.WeChat_Work_User_Id__c,
                    'id'=> u.Id
                };
                WeChat_SA_Client__c bind = new WeChat_SA_Client__c();
                bind.SA__c = u.Id;
                bind.Client__c =acc.Id;
                insert bind;
                
                BL_WECHAT_Bind blRequest = new BL_WECHAT_Bind();
                RestRequest req = new RestRequest();
                req.requestURI = 'wechat/v0/externalcontact/bind';
                req.httpMethod = 'DELETE';
                Map<String, String> parameters =  new  Map<String, String>();
                parameters.put('union_id', acc.wechat_union_id__c);
                parameters.put('externalid', acc.wechat_external_id__c);
                parameters.put('memberid', 'falseMemberId');
                req.params.putAll(parameters);
                RestContext.request = req;
                blRequest.init('wechat/v0/externalcontact/bind',  '/externalcontact/bind', null);
         
                Object o = blRequest.executeDELETE();
           }
        } catch(Exception ex){
            System.debug('ex -->>'+ex);
        }
    }
}