unpackaged/main/default/objects/Case/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>this field is feeded by Service cloud for the Client Cologne</description>
    <inlineHelpText>The customer&#39;s original call center</inlineHelpText>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CSC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CCC.EU.DE01</fullName>
            </value>
            <value>
                <fullName>CSC.EU.EU01</fullName>
            </value>
            <value>
                <fullName>CSC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CCC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.KR01</fullName>
            </value>
            <value>
                <fullName>CCC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.02</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/HUB_Handle__c.field-meta.xml
<CustomField>
    <fullName>HUB_Handle__c</fullName>
    <label>HUB Handle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>JAPSO1</fullName>
                <isActive>false</isActive>
                <label>JAPSO1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hub_Origin__c.field-meta.xml
<CustomField>
    <fullName>Hub_Origin__c</fullName>
    <label>Hub Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>Hub the user is working for</description>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DataFactoryForTests.cls
/***********************************
 * 
 * Creation date : 05/01/2024
 * Created By : JBR
 * Company : Vo2-Group
 * 
 * Date        | By                   | Company        | Modifications description
 * ------------|----------------------|----------------|-------------------------
 * 05/01/2024  | Julien Breuleux      | Vo2-Group      | Initial Creation
 * 
 * Description : 
 *       * Data factory used for test clases
 * 
************************************/

@isTest
public class DataFactoryForTests {

    //Create test User
    public static User createTestUser(string name){
        User testUser = new User(
            LastName = name,
            Alias = 'test',
            Username = 'test_' + DateTime.now().getTime() + '@test.com',
            FirstName = 'Test',
            Email = 'test@rimowa.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'CS - Advisor' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Hub__c = 'EU'
        );
        insert testUser;
        return testUser;
    }
    
    //Create Case
    public static Case createCase(){
        Case testCase = new Case(
        	Status = 'New',
            Subject = 'Subject test',
            Description = 'Description Test',
            Origin = 'Email',
            Type = 'To Qualify',
            Activity__c = 'CS',
            Hub_Origin__c = 'AUS',
            HUB_Handle__c = '00',
            SuppliedEmail = 'Test@test.com',
            SuppliedName = 'Test Test'
        );
        insert testCase;
        return testCase;
    }
    
}