unpackaged/main/default/objects/Case/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>this field is feeded by Service cloud for the Client Cologne</description>
    <inlineHelpText>The customer&#39;s original call center</inlineHelpText>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CSC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CCC.EU.DE01</fullName>
            </value>
            <value>
                <fullName>CSC.EU.EU01</fullName>
            </value>
            <value>
                <fullName>CSC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CCC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.KR01</fullName>
            </value>
            <value>
                <fullName>CCC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.02</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/HUB_Handle__c.field-meta.xml
<CustomField>
    <fullName>HUB_Handle__c</fullName>
    <label>HUB Handle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>JAPSO1</fullName>
                <isActive>false</isActive>
                <label>JAPSO1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>Hub the user is working for</description>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CaseOwnerChangerTest.cls
/***********************************
 * 
 * Creation date : 05/01/2024
 * Created By : JBR
 * Company : Vo2-Group
 * 
 * Date        | By                   | Company        | Modifications description
 * ------------|----------------------|----------------|-------------------------
 * 05/01/2024  | Julien Breuleux      | Vo2-Group      | Initial Creation
 * 
 * Description : 
 *       * Test classe to test the CaseOwnerChanger apex method.
 * 
************************************/

@isTest
public class CaseOwnerChangerTest {

    @isTest
    static void testChangeCaseOwner(){
    User testUser = DataFactoryForTests.createTestUser('test');
    Case testCase = DataFactoryForTests.createCase();
    
        // Run as a specific user
        System.runAs(testUser) {
            // Call the method to test
            Test.startTest();
            CaseOwnerChanger.changeCaseOwner(testCase.Id);
            Test.stopTest();
            
            // Retrieve the updated case
            Case updatedCase = [SELECT OwnerId, Status, HUB_Handle__c FROM Case WHERE Id = :testCase.Id];
            
            // Assert the case owner is changed to the test user
            System.assertEquals(testUser.Id, updatedCase.OwnerId, 'The case owner should be updated to the test user.');
            
            // Assert the case status is updated to 'Working'
            System.assertEquals('Working', updatedCase.Status, 'The case status should be updated to Working.');
            
            // Assert the HUB_Handle__c field is updated
            System.assertEquals(testUser.Hub__c, updatedCase.HUB_Handle__c, 'The HUB_Handle__c field should be updated.');
        }
    }
    
}