unpackaged/main/default/objects/Case/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>this field is feeded by Service cloud for the Client Cologne</description>
    <inlineHelpText>The customer&#39;s original call center</inlineHelpText>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CSC.NA.US01</fullName>
            </value>
            <value>
                <fullName>CCC.EU.DE01</fullName>
            </value>
            <value>
                <fullName>CSC.EU.EU01</fullName>
            </value>
            <value>
                <fullName>CSC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CCC.JP.JP01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CSC.AS.KR01</fullName>
            </value>
            <value>
                <fullName>CCC.AS.AU01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.01</fullName>
            </value>
            <value>
                <fullName>CCC.NA.US.02</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/HUB_Handle__c.field-meta.xml
<CustomField>
    <fullName>HUB_Handle__c</fullName>
    <label>HUB Handle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>JAPSO1</fullName>
                <isActive>false</isActive>
                <label>JAPSO1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Hub__c.field-meta.xml
<CustomField>
    <fullName>Hub__c</fullName>
    <description>Hub the user is working for</description>
    <label>Hub</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>JPN</fullName>
            </value>
            <value>
                <fullName>DEUKO1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CaseOwnerChanger.cls
/***********************************
 * 
 * Creation date : 05/01/2024
 * Created By : JBR
 * Company : Vo2-Group
 * 
 * Date        | By                   | Company        | Modifications description
 * ------------|----------------------|----------------|-------------------------
 * 05/01/2024  | Julien Breuleux      | Vo2-Group      | Initial Creation
 * 
 * Description : 
 *       * Called in changeCaseOwner LWC to update the case Owner / Status / Hub Handle.
 *		 * Allow SFSC user to by pass Sharing settings and Roles, in order to update and take ownership of cases.
 * 
************************************/


public without sharing class CaseOwnerChanger {

    @AuraEnabled
    public static void changeCaseOwner(Id caseId) {
        // Check if the record Id is a Case Id
        if (String.valueOf(caseId).startsWith('500')) {
            try {
                // Get the current Case
                Case caseToUpdate = [SELECT Id, OwnerId, Status FROM Case WHERE Id = :caseId LIMIT 1];

                // Retrieve the Hub handle of the current user
                String userHubHandle = getUserHubHandle();

                // Logic to use the Hub handle, e.g., update a custom field on the Case
                caseToUpdate.HUB_Handle__c = userHubHandle;

                // Update case owner
                caseToUpdate.OwnerId = UserInfo.getUserId();

                // Update the case status only if it's new
                if (caseToUpdate.Status == 'New') {
                    caseToUpdate.Status = 'Working';
                }
                
                update caseToUpdate;
            } catch (Exception e) {
                throw new AuraHandledException('An error occurred when trying to change the case owner: ' + e.getMessage());
            }
        } else {
            throw new AuraHandledException('The recordId is not a Case Id');
        }
    }

    private static String getUserHubHandle() {
        Id userId = UserInfo.getUserId();
        User currentUser = [SELECT Hub__c FROM User WHERE Id = :userId LIMIT 1];
        return currentUser.Hub__c;
    }
}