unpackaged/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GC1040</fullName>
            </value>
            <value>
                <fullName>GC1060</fullName>
            </value>
            <value>
                <fullName>GC3020</fullName>
            </value>
            <value>
                <fullName>GC3040</fullName>
            </value>
            <value>
                <fullName>GC3060</fullName>
            </value>
            <value>
                <fullName>GC5020</fullName>
            </value>
            <value>
                <fullName>GC5040</fullName>
            </value>
            <value>
                <fullName>GC5060</fullName>
            </value>
            <value>
                <fullName>GC1020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Catalog_Product__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Product SKU</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientAddress__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Addresses</relationshipLabel>
    <relationshipName>ClientAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Cegid</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Ecommerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CountryCode__c/fields/Alpha_2_code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_code__c</fullName>
    <label>Alpha-2 code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CountryCode__c/fields/Alpha_3_code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_code__c</fullName>
    <label>Alpha-3 code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Translation__c/Product_Translation__c.object-meta.xml
<CustomObject>
    <label>Product Translation</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Translated Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Translation__c/fields/Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalog__c</fullName>
    <label>Product (Catalog)</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Products Translations</relationshipLabel>
    <relationshipName>Products_Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CLT_TestDateFactory_Test.cls
/**
 * @author Sarah AYOUN (Balink)
 * @date Mai,07 2024
 * @Type Apex Test Class
 *****************************************************************************************************************************************************************
 * @description This Test class contains the methods to test those method from CLT_TestDateFactory :
 * each method of CLT_TestDateFactory has its own test method, this is only test factory class so the assert equals checks that the data was created as expected
 * 
 * ****************************************************************************************************************************************************************
 * @Version : 
 * Version	|Date of modication	|Modified By	|Related Jira Ticket	|Description of changes			
 * 0.0		|2024/05/07			|.Sarah A		|.						|.original version
*/
@isTest
private class CLT_TestDateFactory_Test {
    @isTest
    static void createTestUserWithLangCodeTest() {
        User u = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, 'fr', true);
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;

        List<User> uFactoryAfterInsert = [SELECT Id FROM User WHERE LanguageLocaleKey = 'fr' AND Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser];
        System.assertEquals(1, uFactoryAfterInsert.size(), 'user created with profile name and with lang code size is not 1');
    }

    @isTest
    static void createTestUserWithProfileTest() {
        User u = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;

        List<User> uFactoryAfterInsert = [SELECT Id FROM User WHERE LanguageLocaleKey = 'en_US' AND Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser];
        System.assertEquals(1, uFactoryAfterInsert.size(), 'user created with profile name and without lang code size is not 1');
    }

    @isTest
    static void createTestUserWithNoProfileTest() {
        User u = CLT_TestDateFactory.createTestUser();
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;

        List<User> uFactoryAfterInsert = [SELECT Id FROM User WHERE LanguageLocaleKey = 'en_US' AND Username LIKE :testUserEmailPostfix AND Profile.Name = 'System Administrator'];
        System.assertEquals(1, uFactoryAfterInsert.size(), 'user created without precised profile and no lang code size is not 1');
    }

    @isTest
    static void createTaskTest() {
        User u = CLT_TestDateFactory.createTestUser();
        Task t = CLT_TestDateFactory.createTask(u.Id, true);
        List<Task> tasksAfterFactoryInsert = [SELECT Id FROM Task WHERE OwnerId = :u.Id];
        System.assertEquals(1, tasksAfterFactoryInsert.size(), 'user assigned tasks list size is not 1');
    }

    @isTest
    static void createEventTest() {
        User u = CLT_TestDateFactory.createTestUser();
        Event e = CLT_TestDateFactory.createTestEvent(u.Id, true);
        List<Event> eventsAfterFactoryInsert = [SELECT Id FROM Event WHERE OwnerId = :u.Id];
        System.assertEquals(1, eventsAfterFactoryInsert.size(), 'user assigned events list size is not 1');
    }

    @isTest
    static void createTestStoreTest() {
        Store__c s = CLT_TestDateFactory.createTestStore('TST123', true);
        List<Store__c> storesAfterFactoryInsert = [SELECT Id FROM Store__c WHERE SourceStoreId__c = 'TST123'];
        System.assertEquals(1, storesAfterFactoryInsert.size(), 'store with TST123 code  list size is not 1');
    }

    @isTest
    static void createTestProductTest() {
        Catalog_Product__c p = CLT_TestDateFactory.createTestProduct('TST123', true);
        List<Catalog_Product__c> productsAfterFactoryInsert = [SELECT Id FROM Catalog_Product__c WHERE Product_SKU__c = 'TST123'];
        System.assertEquals(1, productsAfterFactoryInsert.size(), 'product with TST123 sku list size is not 1');
    }

    @isTest
    static void createTestProductTranslationTest() {
        Catalog_Product__c p = CLT_TestDateFactory.createTestProduct('TST123', true);
        Product_Translation__c pt = CLT_TestDateFactory.createTestProductTranslation(p.Id, true);
        List<Product_Translation__c> productTranslationsAfterFactoryInsert = [SELECT Id FROM Product_Translation__c WHERE Product_Catalog__c = :p.Id];
        System.assertEquals(1, productTranslationsAfterFactoryInsert.size(), 'product translations list size is not 1');
    }

    @isTest
    static void createTestClientTest() {
        Store__c s = CLT_TestDateFactory.createTestStore('TST123', true);
        User u = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);

        Account client = CLT_TestDateFactory.createTestClient('testfirstname', 'testlastname', u.Id, s.Id, true);
        List<Account> clientsAfterFactoryInsert = [SELECT Id FROM Account WHERE IsPersonAccount = true AND FirstName = 'testfirstname' AND LastName = 'testlastname' AND ClientAdvisor__pc = :u.Id AND MainStore__pc = :s.Id];
        System.assertEquals(1, clientsAfterFactoryInsert.size(), 'clients list size is not 1');
    }

    @isTest
    static void createTestCountryCodeTest() {
        CountryCode__c cc = CLT_TestDateFactory.createTestCountryCode('France', 'FR', 'FRA', true);

        List<CountryCode__c> countryCodesAfterFactoryInsert = [SELECT Id FROM CountryCode__c WHERE Name = 'France' AND Alpha_2_code__c = 'FR' AND Alpha_3_code__c = 'FRA'];
        System.assertEquals(1, countryCodesAfterFactoryInsert.size(), 'country codes list size is not 1');
    }

    @isTest
    static void createTestClientSourceTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        ClientSource__c cs = CLT_TestDateFactory.createTestClientSource(client.Id, '001', 'TST00123', true);

        List<ClientSource__c> clientSourcesAfterFactoryInsert = [SELECT Id FROM ClientSource__c WHERE Client__c = :client.Id AND Source__c = '001' AND SourceCode__c = 'TST00123'];
        System.assertEquals(1, clientSourcesAfterFactoryInsert.size(), 'country codes list size is not 1');
    }

    @isTest
    static void createTestWishlistTest() {
        Catalog_Product__c p = CLT_TestDateFactory.createTestProduct('TST123', true);
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        WishlistItem__c wishlist = CLT_TestDateFactory.createTestWishlist(p.Id, client.Id, true);

        List<WishlistItem__c> wishlistItemsAfterFactoryInsert = [SELECT Id FROM WishlistItem__c WHERE Client__c = :client.Id AND Product__c = :p.Id];
        System.assertEquals(1, wishlistItemsAfterFactoryInsert.size(), 'wishlist items list size is not 1');
    }

    @isTest
    static void createTestClientListTest() {
        CLT_TestDateFactory.createTestClientList('test client list', ' FirstName = \'Test\' ', true);

        List<ClientList__c> clientListsAfterFactoryInsert = [SELECT Id FROM ClientList__c WHERE Name = 'test client list'];
        System.assertEquals(1, clientListsAfterFactoryInsert.size(), 'clisnt lists list size is not 1');
    }

    @isTest
    static void createTestGiftTest() {
        String giftNameOption =  Gift__c.Name__c.getDescribe().getPicklistValues()[0].getLabel();
        Gift__c gift = CLT_TestDateFactory.createTestGift(giftNameOption, true);

        List<Gift__c> giftsAfterFactoryInsert = [SELECT Id FROM Gift__c WHERE Name__c = :giftNameOption];
        System.assertEquals(1, giftsAfterFactoryInsert.size(), 'gifts list size is not 1');
    }

    @isTest
    static void createTestClientelingEventTest() {
        String eventNameOption =  Event__c.Name__c.getDescribe().getPicklistValues()[0].getLabel();
        Event__c evnt = CLT_TestDateFactory.createTestClientelingEvent(eventNameOption, true);

        List<Event__c> eventsAfterFactoryInsert = [SELECT Id FROM Event__c WHERE Name__c = :eventNameOption];
        System.assertEquals(1, eventsAfterFactoryInsert.size(), 'events list size is not 1');
    }

    @isTest
    static void createTestPersonalClientListTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
        ClientList__c cl = CLT_TestDateFactory.createTestPersonalClientList('Test Personal Client List', sa.Id, true);

        List<ClientList__c> clientListsAfterFactoryInsert = [SELECT Id FROM ClientList__c WHERE Name = 'Test Personal Client List' AND OwnerId = :sa.Id];
        System.assertEquals(1, clientListsAfterFactoryInsert.size(), 'client lists list size is not 1');
    }

    @isTest
    static void createTestPersonalClientListMemberTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
        Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);

        Account client = CLT_TestDateFactory.createTestClient('Test client', 'Test Last Name', sa.Id, store.Id,  true);
        ClientList__c cl = CLT_TestDateFactory.createTestPersonalClientList('Test Personal Client List', sa.Id, true);
        CLT_TestDateFactory.createTestPersonalClientListMember(cl.Id, client.Id, true);

        List<ClientListMember__c> clientListsMembersAfterFactoryInsert = [SELECT Id FROM ClientListMember__c WHERE ClientList__c = :cl.Id];
        System.assertEquals(1, clientListsMembersAfterFactoryInsert.size(), 'client list Members list size is not 1');
    }

    @isTest
    static void createTestStandardProductTest() {
        Product2 p = CLT_TestDateFactory.createTestStandardProduct('TST123', true);

        List<Product2> standardProductsAfterFactoryInsert = [SELECT Id FROM Product2 WHERE StockKeepingUnit = 'TST123'];
        System.assertEquals(1, standardProductsAfterFactoryInsert.size(), 'products list size is not 1');
    }

    @isTest
    static void createTestTransactionTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        Transaction__c t = CLT_TestDateFactory.createTestTransaction(client.Id, Date.today(), true);

        List<Transaction__c> transactionsAfterFactoryInsert = [SELECT Id FROM Transaction__c WHERE TransactionDate__c = TODAY AND Client__c = :client.Id];
        System.assertEquals(1, transactionsAfterFactoryInsert.size(), 'transactions list size is not 1');
    }

    @isTest
    static void createTestTransactionItemTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        Transaction__c t = CLT_TestDateFactory.createTestTransaction(client.Id, Date.today(), true);
        Product2 product = CLT_TestDateFactory.createTestStandardProduct('TEST123', true);
        TransactionItem__c ti = CLT_TestDateFactory.createTestTransactionItem(t.Id, client.Id, product.Id, true);

        List<TransactionItem__c> transactionItemsAfterFactoryInsert = [SELECT Id FROM TransactionItem__c WHERE Transaction__c = :t.Id];
        System.assertEquals(1, transactionItemsAfterFactoryInsert.size(), 'transaction items list size is not 1');
    }

    @isTest
    static void createTestNewsTest() {
        CLT_TestDateFactory.createTestNews('https://www.rimowa.com/ww/en/stories/rimowa-x-gewa-introduction.html', 'RIMOWA × GEWA:THE ULTIMATE CASE FOR VIOLINS RIMOWA', true);

        List<News__c> newsAfterFactoryInsert = [SELECT Id FROM News__c WHERE Link__c = 'https://www.rimowa.com/ww/en/stories/rimowa-x-gewa-introduction.html'];
        System.assertEquals(1, newsAfterFactoryInsert.size(), 'news list size is not 1');
    }

    @isTest
    static void createTestNewsContentTest() {
        News__c n = CLT_TestDateFactory.createTestNews('https://www.rimowa.com/ww/en/stories/rimowa-x-gewa-introduction.html', 'RIMOWA × GEWA:THE ULTIMATE CASE FOR VIOLINS RIMOWA', true);
        CLT_TestDateFactory.createTestNewsContent(n.Id, 'fr', 'https://www.rimowa.com/fr/fr/stories/rimowa-x-gewa-introduction.html', 'RIMOWA × GEWA : LÉTUI POUR VIOLON IDÉAL', true);
        
        List<NewsContent__c> newsContentsAfterFactoryInsert = [SELECT Id FROM NewsContent__c WHERE News__c = :n.Id];
        System.assertEquals(1, newsContentsAfterFactoryInsert.size(), 'news contents list size is not 1');
    }

    @isTest
    static void createTestFeedbackTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        CLT_TestDateFactory.createTestFeedback(client.Id, true);

        List<due__Diduenjoy_Feedback__c> feedbacksAfterFactoryInsert = [SELECT Id FROM due__Diduenjoy_Feedback__c WHERE due__Account__c = :client.Id];
        System.assertEquals(1, feedbacksAfterFactoryInsert.size(), 'feedbacks list size is not 1');
    }

    @isTest
    static void createTestFeedbackAnswerTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        due__Diduenjoy_Feedback__c feedback = CLT_TestDateFactory.createTestFeedback(client.Id, true);
        CLT_TestDateFactory.createTestFeedbackAnswer(feedback.Id, 10, true);

        List<due__Diduenjoy_Answer__c> feedbackAnswersAfterFactoryInsert = [SELECT Id FROM due__Diduenjoy_Answer__c WHERE due__Diduenjoy_Feedback__c = :feedback.Id];
        System.assertEquals(1, feedbackAnswersAfterFactoryInsert.size(), 'feedback answers list size is not 1');
    }

    @isTest
    static void createTestNoteTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        CLT_TestDateFactory.createTestNote('test note', client.Id, true);

        List<Note__c> notesAfterFactoryInsert = [SELECT Id FROM Note__c WHERE Client__c = :client.Id];
        System.assertEquals(1, notesAfterFactoryInsert.size(), 'notes list size is not 1');
    }

    @isTest
    static void createTestClientAddressTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test First Name', 'Test Last Name', sa.Id, store.Id, true);
        CLT_TestDateFactory.createTestClientAddress(client.Id, true);

        List<ClientAddress__c> clientAddressesAfterFactoryInsert = [SELECT Id FROM ClientAddress__c WHERE Client__c = :client.Id];
        System.assertEquals(1, clientAddressesAfterFactoryInsert.size(), 'clientAddresses list size is not 1');
    }

    @isTest
    static void createTestNotificationTest() {
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
         
        CLT_TestDateFactory.createTestNotification('TEST TYPE', sa.Id, DateTime.now(), true);

        List<Notification__c> notificationsAfterFactoryInsert = [SELECT Id FROM Notification__c WHERE User__c = :sa.Id];
        System.assertEquals(1, notificationsAfterFactoryInsert.size(), 'notifications list size is not 1');
    }

    @isTest
    static void createTestRClientConfigurationsTest() {
        CLT_TestDateFactory.createTestRClientConfigurations(true);
        System.assertNotEquals(null, RClientConfigurations__c.getOrgDefaults(), 'Client Configurations is null');
    }
}