unpackaged/main/default/objects/Accessory_Sub_Type__c/Accessory_Sub_Type__c.object-meta.xml
<CustomObject>
    <label>Accessory Sub Type</label>
    <nameField>
        <label>Accessory_Sub_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Sub Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_Sub_Type__c/fields/Accessory_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Type</label>
    <referenceTo>Accessory_Type__c</referenceTo>
    <relationshipLabel>Accessory Sub Types</relationshipLabel>
    <relationshipName>Accessory_sub_types</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Accessory_sub_type_Translation__c/Accessory_sub_type_Translation__c.object-meta.xml
<CustomObject>
    <label>Accessory-sub-type Translation</label>
    <nameField>
        <label>Translated Accessory-sub-type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory-sub-type Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_sub_type_Translation__c/fields/Accessory_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Sub_Type__c</fullName>
    <label>Accessory Sub Type</label>
    <referenceTo>Accessory_Sub_Type__c</referenceTo>
    <relationshipLabel>Accessory-sub-type Translations</relationshipLabel>
    <relationshipName>Accessory_sub_type_Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Accessory_Type__c/Accessory_Type__c.object-meta.xml
<CustomObject>
    <label>Accessory Type</label>
    <nameField>
        <label>Accessory-type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Accessory Types</relationshipLabel>
    <relationshipName>Accessory_Types_del</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Accessory_type_Translation__c/Accessory_type_Translation__c.object-meta.xml
<CustomObject>
    <label>Accessory-type Translation</label>
    <nameField>
        <label>Translated Accessory-type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory-type Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_type_Translation__c/fields/Accessory_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Type__c</fullName>
    <label>Accessory Type</label>
    <referenceTo>Accessory_Type__c</referenceTo>
    <relationshipLabel>Accessory-type Translations</relationshipLabel>
    <relationshipName>Accessory_type_Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Collection__c/Collection__c.object-meta.xml
<CustomObject>
    <label>Collection</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Collection__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Collections</relationshipLabel>
    <relationshipName>Collections_del</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Collection_Translation__c/Collection_Translation__c.object-meta.xml
<CustomObject>
    <label>Collection Translation</label>
    <nameField>
        <label>Translated Collection</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Collection_Translation__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <label>Collection</label>
    <referenceTo>Collection__c</referenceTo>
    <relationshipLabel>Collections Translations</relationshipLabel>
    <relationshipName>Collections_Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Collection_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLT_ProductHierarchy.cls
public with sharing class CLT_ProductHierarchy implements CLT_RetailInterface{
    
    public Object retrieveDelete(Map<String, String> params){
        return null;
    }
    
    public Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    public Object retrieveGet(Map<String, String> params){
        Map<String, Object> result = new Map<String, Object>();

        list<map<string, object>> categories = getCategories();
        list<map<string, object>> collections = getCollections();
        list<map<string, object>> collectionTranslations = getCollectionTranslations();
        list<map<string, object>> accessoryTypes = getAccessoryTypes();
        list<map<string, object>> accessoryTypeTranslations = getAccessoryTypeTranslations();
        list<map<string, object>> accessorySubTypes = getaccessorySubTypes();
		list<map<string, object>> accessorySubTypeTranslations = getAccessorySubTypeTranslations();
        
		for(map<string, object> collection:collections)
        	System.debug(collection);
        
        
        result.put('categories', categories);
        result.put('collections', collections);
        result.put('collectionTranslations', collectionTranslations);
        result.put('accessoryTypes', accessoryTypes);
        result.put('accessoryTypeTranslations', accessoryTypeTranslations);
        result.put('accessorySubTypes', accessorySubTypes);
        result.put('accessorySubTypeTranslations', accessorySubTypeTranslations);
        system.debug('result: ' + result);
        return result;
    }

    public list<map<string, object>> getCategories(){    
        return CLT_Utils_Mapping.getStandardWrapperList('Category__c', 'Category', 'FROM Category__c');
    }
    
    public list<map<string, object>> getCollections(){
        return CLT_Utils_Mapping.getStandardWrapperList('Collection__c', 'Collection', 'FROM Collection__c');
    }
    
    public list<map<string, object>> getCollectionTranslations(){
        final String userLanguage = UserInfo.getLanguage();
        return CLT_Utils_Mapping.getStandardWrapperList('Collection_Translation__c',
            'CollectionTranslation', 'FROM Collection_Translation__c WHERE Language__c = ' + '\'' +userLanguage+ '\'');
    }

    public list<map<string, object>> getAccessoryTypes(){
        return CLT_Utils_Mapping.getStandardWrapperList('Accessory_Type__c', 'AccessoryType', 'FROM Accessory_Type__c');
    }
    
    public list<map<string, object>> getAccessoryTypeTranslations(){
        final String userLanguage = UserInfo.getLanguage();
        return CLT_Utils_Mapping.getStandardWrapperList('Accessory_type_Translation__c',
        	'AccessoryTypeTranslation', 'FROM Accessory_type_Translation__c WHERE Language__c = ' + '\'' +userLanguage+ '\'');
    }
    
    public list<map<string, object>> getAccessorySubTypes(){
        return CLT_Utils_Mapping.getStandardWrapperList('Accessory_Sub_Type__c', 'AccessorySubType', 'FROM Accessory_Sub_Type__c');
    }
    
    public list<map<string, object>> getAccessorySubTypeTranslations(){
        final String userLanguage = UserInfo.getLanguage();
        return CLT_Utils_Mapping.getStandardWrapperList('Accessory_sub_type_Translation__c',
            'AccessorySubTypeTranslation', 'FROM Accessory_sub_type_Translation__c WHERE Language__c = ' + '\'' +userLanguage+ '\'');
    }
}