unpackaged/main/default/objects/Accessory_Sub_Type__c/Accessory_Sub_Type__c.object-meta.xml
<CustomObject>
    <label>Accessory Sub Type</label>
    <nameField>
        <label>Accessory_Sub_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Sub Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accessory_Sub_Type__c/fields/Accessory_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Type</label>
    <referenceTo>Accessory_Type__c</referenceTo>
    <relationshipLabel>Accessory Sub Types</relationshipLabel>
    <relationshipName>Accessory_sub_types</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Accessory_Type__c/Accessory_Type__c.object-meta.xml
<CustomObject>
    <label>Accessory Type</label>
    <nameField>
        <label>Accessory-type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Collection__c/Collection__c.object-meta.xml
<CustomObject>
    <label>Collection</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Story__c/Story__c.object-meta.xml
<CustomObject>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Story__c/fields/Accessory_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Sub_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Sub Type</label>
    <referenceTo>Accessory_Sub_Type__c</referenceTo>
    <relationshipLabel>Stories</relationshipLabel>
    <relationshipName>Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Story__c/fields/Accessory_Type__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Type</label>
    <referenceTo>Accessory_Type__c</referenceTo>
    <relationshipLabel>Stories</relationshipLabel>
    <relationshipName>Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Story__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection</label>
    <referenceTo>Collection__c</referenceTo>
    <relationshipLabel>Stories</relationshipLabel>
    <relationshipName>Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Story__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Stories</relationshipLabel>
    <relationshipName>Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CLT_Story.cls
public with sharing class CLT_Story implements CLT_RetailInterface{
 
    public Object retrieveDelete(Map<String, String> params){
        return null;    
    }
    
    public Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    public Object retrieveGet(Map<String, String> params){   
         return new Map<String, Object> {
        'stories' => getStories(params)
        };

    } 
    
     //Return stories that match the params parameter value
    List<Map<String, Object>> getStories(Map<String, String> params){
        List<Story__c> storiesList = [Select Id, Name, Title__c, Text__c, Accessory_Type__c, Accessory_Sub_Type__c, Product__c, Image__c, Collection__c, CurrencyIsoCode from Story__c];
        return CLT_Utils_Mapping.getStandardWrapperListFromObjectList('Story__c', 'Story', storiesList);
    }
}