unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Reach Out</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ClientListMemberTrigger.cls
public class CLT_Utils_ClientListMemberTrigger {
    public static void updateLastContactDate(List<ClientListMember__c> newClientListMembers, Map<Id,ClientListMember__c> oldCLMMap) {
        List<Account> accountToUpdate = new List<Account>();
        Set<Id> setListAccountIdAlreadyAdded = new Set<Id>();
    
        for (ClientListMember__c clm : newClientListMembers) {
            if (clm.Status__c == 'Contacted' && (   !oldCLMMap.containsKey(clm.Id) 
                                                 || (oldCLMMap.containsKey(clm.Id) && oldCLMMap.get(clm.Id).Status__c != 'Contacted')) ) {
                Account account = new Account(id = clm.Client__c);
                
                //Fev2024: EBU>ToBalink : think about ensuring there is no duplicate in a to-be-created/updated list
                if (!setListAccountIdAlreadyAdded?.contains(clm.Client__c)) {
                    account.LastContactDate__pc = Date.today();
                    accountToUpdate.add(account);
                    //add the client list member id to the set Id variable to get only one instance of the same account in the list to be updated
                    setListAccountIdAlreadyAdded.Add(clm.Client__c);
                }
            }
        }
        
        if(accountToUpdate.size() > 0) {
            update accountToUpdate;
        }
    }
}