unpackaged/main/default/objects/CorrectiveInvoice__c/CorrectiveInvoice__c.object-meta.xml
<CustomObject>
    <label>Corrective Invoice</label>
    <nameField>
        <label>Corrective Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corrective Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CorrectiveInvoice__c/fields/Corrective_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Invoice_Date__c</fullName>
    <label>Corrective Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CorrectiveInvoice__c/fields/OriginalInvoiceId__c.field-meta.xml
<CustomField>
    <fullName>OriginalInvoiceId__c</fullName>
    <label>Original Invoice Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CorrectiveInvoice__c/fields/PreviousCorrectiveInvoice__c.field-meta.xml
<CustomField>
    <fullName>PreviousCorrectiveInvoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Corrective Invoice</label>
    <referenceTo>CorrectiveInvoice__c</referenceTo>
    <relationshipLabel>Corrective Invoices</relationshipLabel>
    <relationshipName>Corrective_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FulfillmentOrder/fields/Complementary__c.field-meta.xml
<CustomField>
    <fullName>Complementary__c</fullName>
    <label>Complementary</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FulfillmentOrder/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice/fields/Invoice_Timezone_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Timezone_Date__c</fullName>
    <label>Invoice Timezone Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Invoice/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Legal_Entity__c/fields/CountryLabel__c.field-meta.xml
<CustomField>
    <fullName>CountryLabel__c</fullName>
    <label>Country Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Legal_Entity__c/fields/FooterBilling__c.field-meta.xml
<CustomField>
    <fullName>FooterBilling__c</fullName>
    <label>Footer Billing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Legal_Entity__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/BillingContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactFirstName__c</fullName>
    <label>Billing Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/BillingContactLastName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactLastName__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/language__c.field-meta.xml
<CustomField>
    <fullName>language__c</fullName>
    <label>language</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderDeliveryGroupSummary/fields/Complementary__c.field-meta.xml
<CustomField>
    <fullName>Complementary__c</fullName>
    <label>Complementary</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderDeliveryGroupSummary/fields/RI_TAX_ID__c.field-meta.xml
<CustomField>
    <fullName>RI_TAX_ID__c</fullName>
    <label>Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <formula>Product2.COO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COO</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/hsCode__c.field-meta.xml
<CustomField>
    <fullName>hsCode__c</fullName>
    <formula>Product2.hsCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hsCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/hsCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>hsCodeDescription__c</fullName>
    <formula>Product2.hsCodeDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HsCode Description</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <formula>Product2.COO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COO</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/hsCode__c.field-meta.xml
<CustomField>
    <fullName>hsCode__c</fullName>
    <formula>Product2.hsCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hsCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderItemSummary/fields/hsCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>hsCodeDescription__c</fullName>
    <formula>Product2.hsCodeDescription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HsCode Description</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactFirstName__c</fullName>
    <label>Billing Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/BillingContactLastName__c.field-meta.xml
<CustomField>
    <fullName>BillingContactLastName__c</fullName>
    <label>Billing Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/language__c.field-meta.xml
<CustomField>
    <fullName>language__c</fullName>
    <label>Language</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>18</length>
    <type>Text</type>
    
</CustomField>

unpackaged/main/default/objects/OrderSummary/fields/VAT_ID__c.field-meta.xml
<CustomField>
    <fullName>VAT_ID__c</fullName>
    <label>VAT ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Methods_Mapping__mdt/Payment_Methods_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Payment Methods Mapping</label>
    <pluralLabel>Payment Methods Mapping</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Payment_Methods_Mapping__mdt/fields/Is_Card_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Is_Card_Payment_Method__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Card Payment Method</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Payment_Methods_Mapping__mdt/fields/Translation__c.field-meta.xml
<CustomField>
    <fullName>Translation__c</fullName>
    <label>Translation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <label>COO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/hsCode__c.field-meta.xml
<CustomField>
    <fullName>hsCode__c</fullName>
    <label>hsCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/hsCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>hsCodeDescription__c</fullName>
    <label>hsCode Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/Sales_Channel_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Sales Channel Mapping</label>
    <pluralLabel>Sales Channel Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/AmountsFormat__c.field-meta.xml
<CustomField>
    <fullName>AmountsFormat__c</fullName>
    <label>Amounts Format</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/VAT_ID__c.field-meta.xml
<CustomField>
    <fullName>VAT_ID__c</fullName>
    <label>VAT ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sales_Channel_Mapping__mdt/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SOM_Invoice_Setting__mdt/SOM_Invoice_Setting__mdt.object-meta.xml
<CustomObject>
    <label>SOM Invoice Setting</label>
    <pluralLabel>SOM Invoice Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SOM_Invoice_Setting__mdt/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SOM_Invoice_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/SOM_InvoiceDocumentController.cls
global with sharing class SOM_InvoiceDocumentController {
    
    public static final String   CONCAT_CHARACTER = ',';
    public Map<String, String>   invoiceConfigs { get; set; }
    public InvoiceDocument       invoiceDoc { get; set;}
    public Map<String,String>    invoiceTaxLineItems {get; set; }
    public Map<String,String>    countryMap {get;set;}
    public String                correctiveInvoiceHeaderMessage {get; set; }
    public String                AmountsFormat {get; set; }
    public InvoiceAddress        invoiceAddress { get; set;}
    
    
    public SOM_InvoiceDocumentController() {
        this.countryMap = SOM_Utils.getCountryKeyValueMap(SOM_Constants.ORDER_SUMMARY_NAME, SOM_Constants.ORDER_SUMMARY_COUNTRY_FIELD_NAME);
        this.setInvoiceDocumentConfigs();
        this.setInvoiceData(); 
    }
    
    public void setInvoiceDocumentConfigs(){
        this.invoiceConfigs = new Map<String,String>();
        String templateCode = ApexPages.currentPage().getParameters().get('template');
        List<SOM_Invoice_Setting__mdt> invoiceSettings = [SELECT MasterLabel, Value__c, Template__c FROM SOM_Invoice_Setting__mdt WHERE Template__c = :templateCode OR Template__c = :'CoreModel'];
        for (SOM_Invoice_Setting__mdt invoiceSetting : invoiceSettings) {
            if(!invoiceConfigs.containsKey(invoiceSetting.MasterLabel) || invoiceSetting.Template__c != 'CoreModel'){
                if (invoiceSetting.Value__c == null) {
                    invoiceConfigs.put(invoiceSetting.MasterLabel, '');
                } else {
                    invoiceConfigs.put(invoiceSetting.MasterLabel, invoiceSetting.Value__c);
                }
            }
        }
    }
    
    public void setInvoiceData(){
        String templateCode = ApexPages.currentPage().getParameters().get('template');
        InvoiceDocument invDoc        = new InvoiceDocument();
        InvoiceAddress invAddress     = new InvoiceAddress();
        InvoiceContact invCtr         = new InvoiceContact();
        CorrectiveInvoice__c cInvoice = null;
        Id invoiceId = ApexPages.currentPage().getParameters().get('invoiceId');
        Boolean isCorrectiveInvoice = invoiceId.getSObjectType().getDescribe().getName() == SOM_Constants.CORRECTIVE_INVOICE_SOBJECT_TYPE_NAME;
        String REPLACEMENT = invoiceConfigs.get('REPLACEMENT');
        if(isCorrectiveInvoice){
            cInvoice = [SELECT Id, Name,OriginalInvoiceId__c, PreviousCorrectiveInvoice__r.Name, CreatedDate, Corrective_Invoice_Date__c FROM CorrectiveInvoice__c WHERE Id = :invoiceId];
            Invoice originalInvoice = [SELECT Id, InvoiceNumber__c FROM Invoice WHERE Id = :cInvoice.OriginalInvoiceId__c];
            String previousInv      = String.isEmpty(cInvoice.PreviousCorrectiveInvoice__r.Name) ? originalInvoice.InvoiceNumber__c : cInvoice.PreviousCorrectiveInvoice__r.Name;
            if(REPLACEMENT != null && REPLACEMENT != ''){
                this.correctiveInvoiceHeaderMessage =  previousInv;
            }
            invoiceId = originalInvoice.Id;        
        }
        
        List<FulfillmentOrder> fulfillmentOrder = [SELECT Invoice.TotalAmount, Invoice.TotalAmountWithTax, Invoice.TotalTaxAmount, Invoice.InvoiceDate, Invoice.Invoice_Timezone_Date__c, Invoice.InvoiceNumber__c, Invoice.DocumentNumber, OrderSummary.Account.Name, OrderSummary.OrderNumber, 
                                                   FulfilledToName, StreetNumber__c, FulfilledToCity, FulfilledToPostalCode, FulfilledToStreet, FulfilledToState, FulfilledToCountry, OrderSummary.BillingCity,OrderSummary.BillingState, OrderSummary.BillingPostalCode, OrderSummary.BillingContactFirstName__c , OrderSummary.BillingContactLastName__c,
                                                   OrderSummary.BillingStreet, OrderSummary.BillingCountry, OrderSummaryId, OrderSummary.Legal_Entity__c, OrderSummary.VAT_ID__c, CurrencyIsoCode, OrderSummary.language__c,OrderSummary.StreetNumber__c,OrderSummary.Complementary__c, (SELECT id, TrackingNumber FROM FulfillmentOrderShipments) FROM FulfillmentOrder WHERE InvoiceId= :invoiceId];
        List<InvoiceLine> invoiceLines = [SELECT Id, Type, TaxRate,TaxAmount, Product2.Description, Quantity, UnitPrice, GrossUnitPrice, ChargeAmountWithTax, ChargeTaxAmount, TYPEOF ReferenceEntityItem WHEN OrderItemSummary THEN hsCode__c,hsCodeDescription__c,COO__c, Description, LineNumber END FROM InvoiceLine WHERE InvoiceId = :invoiceId];
        
        System.debug('fulfillmentOrder.get(0).OrderSummary.Legal_Entity__c ' + fulfillmentOrder.get(0).OrderSummary.VAT_ID__c);
                
        invAddress = setInvoiceAddress (fulfillmentOrder.get(0).OrderSummary.Legal_Entity__c);
        invAddress.VATID = fulfillmentOrder.get(0).OrderSummary.VAT_ID__c;
        
        invDoc.invoiceDate    = isCorrectiveInvoice ? DateTime.newInstance(cInvoice.Corrective_Invoice_Date__c.year(), cInvoice.Corrective_Invoice_Date__c.month(), cInvoice.Corrective_Invoice_Date__c.day()).format('yyyy-MM-dd') : DateTime.newInstance(fulfillmentOrder.get(0).Invoice.Invoice_Timezone_Date__c.year(), fulfillmentOrder.get(0).Invoice.Invoice_Timezone_Date__c.month(), fulfillmentOrder.get(0).Invoice.Invoice_Timezone_Date__c.day()).format('yyyy-MM-dd');
        invDoc.documentNumber = isCorrectiveInvoice ? cInvoice.Name : fulfillmentOrder.get(0).Invoice.InvoiceNumber__c;
        invDoc.Template 	  = templateCode;
        
        if (fulfillmentOrder != null && !fulfillmentOrder.isEmpty()) {
            //AmountsFormat info
            this.AmountsFormat  = setAmountsFormat(fulfillmentOrder.get(0).FulfilledToCountry);
            
            //invoice info
            invDoc.orderNumber    = fulfillmentOrder.get(0).OrderSummary.orderNumber;
            
            if(templateCode == 'JP'){
                invDoc.totalWithTax   = setAmountsJPFormat(SOM_Utils.getTotalFormatted(fulfillmentOrder.get(0).Invoice.TotalAmountWithTax,AmountsFormat));
                invDoc.netSubTotal    = setAmountsJPFormat(SOM_Utils.getTotalFormatted(fulfillmentOrder.get(0).Invoice.TotalAmount,AmountsFormat));
            }else{
                invDoc.totalWithTax   = SOM_Utils.getTotalFormatted(fulfillmentOrder.get(0).Invoice.TotalAmountWithTax,AmountsFormat);
                invDoc.netSubTotal    = SOM_Utils.getTotalFormatted(fulfillmentOrder.get(0).Invoice.TotalAmount,AmountsFormat);
            }
            
            invDoc.currencyCode   = fulfillmentOrder.get(0).CurrencyIsoCode;
            //Invoice lines
            if (invoiceLines != null && !invoiceLines.isEmpty()) {
                invDoc.lineItems = this.getInvoiceLines(invoiceLines, this.getSerialNumbers(FulfillmentOrder),templateCode);
                this.invoiceTaxLineItems = new Map<String, String>();
                this.invoiceTaxLineItems = this.getInvoiceTaxLineItems(invoiceLines, templateCode);
                
            }
            invDoc.paymentType     = this.getPaymentMethod(fulfillmentOrder.get(0));
            invDoc.billingContact  = this.getBillingContact(fulfillmentOrder.get(0));
            invDoc.deliveryContact = this.getDeliveryContact(fulfillmentOrder.get(0));
            invDoc.trackingNumbers = this.getTrackingNumbers(FulfillmentOrder);
            invDoc.TaxID 		   = this.getOrderDeliveryGroupSummary(fulfillmentOrder.get(0).OrderSummaryId);
        } else {
            System.debug('FulfillmentOrder is empty, InvoiceId: ' + invoiceId);
        }
        
        this.invoiceDoc = invDoc;
        this.invoiceAddress = invAddress;
    }
    
    
    
    public Map<Id, List<String>> getSerialNumbers(List<FulfillmentOrder> fulfillmentOrders){
        //construct shipment ids
        List<Id> shipmentIds = new List<Id>();
        for (FulfillmentOrder fulOrder:fulfillmentOrders) {
            List<Shipment> shipments = fulOrder.FulfillmentOrderShipments;
            if (shipments != null) {
                for (Shipment ship:shipments) {
                    shipmentIds.add(ship.Id);
                }
            }
        }
        
        //construct serial numbers map
        Map<Id, List<String>> serialNumbersMap = new Map<Id, List<String>>();
        List<ShipmentItem> shipmentItems = [SELECT Id, OrderItemSummaryId, SerialNumber__c FROM ShipmentItem WHERE ShipmentId IN :shipmentIds];
        for (ShipmentItem shipItem:shipmentItems) {
            List<String> serialNumbers = serialNumbersMap.get(shipItem.OrderItemSummaryId);
            if (serialNumbers == null) {
                serialNumbers = new List<String>();
            }
            if(shipItem.SerialNumber__c != null) {
                serialNumbers.add(shipItem.SerialNumber__c);
            }
            serialNumbersMap.put(shipItem.OrderItemSummaryId, serialNumbers);
        }
        
        return serialNumbersMap;
    }
    
    public String getTrackingNumbers(List<FulfillmentOrder> fulfillmentOrders){
        //shipment tracking numbers ==> One Invoice for all FOs
        Set<String> settrackingNumbers = new Set<String>();
        for (FulfillmentOrder fulOrder:fulfillmentOrders) {
            List<Shipment> shipments = fulOrder.FulfillmentOrderShipments;
            if (shipments != null) {
                for (Shipment ship:shipments) {
                    settrackingNumbers.add(ship.TrackingNumber);
                }
            }
        }
        
        return String.join(new List<String>(settrackingNumbers), CONCAT_CHARACTER);
    }
    
    public InvoiceContact getDeliveryContact(FulfillmentOrder fulfillmentOrder){
        InvoiceContact delivContact = new InvoiceContact();
		String Country = countryMap.containsKey(fulfillmentOrder.FulfilledToCountry) ? countryMap.get(fulfillmentOrder.FulfilledToCountry) : fulfillmentOrder.FulfilledToCountry;
        delivContact.name    = fulfillmentOrder.FulfilledToName;
        delivContact.city    = fulfillmentOrder.FulfilledToCity;
        delivContact.zipCode = fulfillmentOrder.FulfilledToPostalCode;
        if (Country == 'Brazil' && !String.IsBlank(fulfillmentOrder.StreetNumber__c) ){
        	delivContact.address = fulfillmentOrder.FulfilledToStreet + ', ' + fulfillmentOrder.StreetNumber__c ;
        }else{
           delivContact.address = fulfillmentOrder.FulfilledToStreet; 
        }
        delivContact.state   = fulfillmentOrder.FulfilledToState;
        delivContact.country = Country; 
        
        return delivContact;
    }
    
    public InvoiceContact getBillingContact(FulfillmentOrder fulfillmentOrder){
        InvoiceContact billContact = new InvoiceContact();
        String Country = countryMap.containsKey(fulfillmentOrder.OrderSummary.BillingCountry)? countryMap.get(fulfillmentOrder.OrderSummary.BillingCountry) : fulfillmentOrder.OrderSummary.BillingCountry;
        billContact.name    = fulfillmentOrder.OrderSummary.BillingContactFirstName__c + ' ' + fulfillmentOrder.OrderSummary.BillingContactLastName__c;
        billContact.city    = fulfillmentOrder.OrderSummary.BillingCity;
        billContact.zipCode = fulfillmentOrder.OrderSummary.BillingPostalCode;
        if (Country == 'Brazil' && !String.IsBlank(fulfillmentOrder.OrderSummary.StreetNumber__c) && !String.IsBlank(fulfillmentOrder.OrderSummary.Complementary__c)){
        	billContact.address = fulfillmentOrder.OrderSummary.BillingStreet + ', ' + fulfillmentOrder.OrderSummary.StreetNumber__c + ' - ' + fulfillmentOrder.OrderSummary.Complementary__c;
        }else if(Country == 'Brazil' && String.IsBlank(fulfillmentOrder.OrderSummary.StreetNumber__c) && !String.IsBlank(fulfillmentOrder.OrderSummary.Complementary__c)){
        	billContact.address = fulfillmentOrder.OrderSummary.BillingStreet + ' - ' + fulfillmentOrder.OrderSummary.Complementary__c;
        }else if(Country == 'Brazil' && !String.IsBlank(fulfillmentOrder.OrderSummary.StreetNumber__c) && String.IsBlank(fulfillmentOrder.OrderSummary.Complementary__c)){
        	billContact.address = fulfillmentOrder.OrderSummary.BillingStreet + ', ' + fulfillmentOrder.OrderSummary.StreetNumber__c;
        }else{
           billContact.address = fulfillmentOrder.OrderSummary.BillingStreet; 
        }
        billContact.state   = fulfillmentOrder.OrderSummary.BillingState;
        billContact.country = Country;
        this.AmountsFormat  = setAmountsFormat(fulfillmentOrder.FulfilledToCountry);
        
        return billContact;
    }
    
    public List<InvoiceLineItem> getInvoiceLines(List<InvoiceLine> invoiceLines, Map<Id, List<String>> serialNumbersMap, String templateCode){
        List<InvoiceLineItem> lineItems = new List<InvoiceLineItem>();
        for(InvoiceLine invoiceLine:invoiceLines) {
            if (invoiceLine.Type.equalsIgnoreCase(SOM_Constants.INVOICE_LINE_TYPE_CHARGE) && invoiceLine.Quantity>0) {
                InvoiceLineItem lineItem = new InvoiceLineItem();
                lineItem.itemDescription = invoiceLine.Product2.Description;
                lineItem.quantity        = invoiceLine.Quantity;
                if(templateCode == 'JP'){
                    lineItem.netAmount       = setAmountsJPFormat(SOM_Utils.getTotalFormatted(invoiceLine.UnitPrice,AmountsFormat));
                    lineItem.vat             = setAmountsJPFormat(SOM_Utils.getTotalFormatted(invoiceLine.ChargeTaxAmount,AmountsFormat));
                    lineItem.grossAmount     = setAmountsJPFormat(SOM_Utils.getTotalFormatted(invoiceLine.GrossUnitPrice,AmountsFormat));
                    lineItem.total           = setAmountsJPFormat(SOM_Utils.getTotalFormatted(invoiceLine.ChargeAmountWithTax,AmountsFormat));
                }else{
                    lineItem.netAmount       = SOM_Utils.getTotalFormatted(invoiceLine.UnitPrice,AmountsFormat);
                    lineItem.vat             = SOM_Utils.getTotalFormatted(invoiceLine.ChargeTaxAmount,AmountsFormat);
                    lineItem.grossAmount     = SOM_Utils.getTotalFormatted(invoiceLine.GrossUnitPrice,AmountsFormat);
                    lineItem.total           = SOM_Utils.getTotalFormatted(invoiceLine.ChargeAmountWithTax,AmountsFormat);
                }
                if (invoiceLine.ReferenceEntityItem instanceOf OrderItemSummary) {
                    OrderItemSummary orderItem = invoiceLine.ReferenceEntityItem;
                    lineItem.hsCode            = orderItem.hsCode__c;
                    lineItem.hsCodeDescription = orderItem.hsCodeDescription__c;
                    lineItem.coo               = orderItem.COO__c;
                    lineItem.itemDescription   = orderItem.Description;
                    List<String> serialNumbers = serialNumbersMap.get(orderItem.Id);
                    if (serialNumbers != null) {
                        lineItem.serialNumber = String.join(serialNumbers, CONCAT_CHARACTER);
                    }
                    lineItem.lineNumber        = orderItem.LineNumber;
                }
                lineItems.add(lineItem);
            }
        }
        //sort
        lineItems.sort();
        Integer counter = 1;
        for(InvoiceLineItem single : lineItems){
            single.itemNumber = counter;
            counter++;
        }
        return lineItems;
    }
    
    public String getPaymentMethod(FulfillmentOrder fulfillmentOrder){
        //Get order payment summary
        List<OrderPaymentSummary> paymentSummary = [SELECT Type, PaymentMethodId, PaymentMethod.ImplementorType FROM OrderPaymentSummary WHERE OrderSummaryId = :fulfillmentOrder.OrderSummaryId];
        if (paymentSummary != null && !paymentSummary.isEmpty()) {
            List<Payment_Methods_Mapping__mdt> paymentMethodsMapping = [SELECT Id, Value__c, Translation__c, Is_Card_Payment_Method__c FROM Payment_Methods_Mapping__mdt WHERE Value__c = :paymentSummary.get(0).Type AND Language__c = :fulfillmentOrder.OrderSummary.language__c];
            if (paymentMethodsMapping != null && !paymentMethodsMapping.isEmpty()) {
                return paymentMethodsMapping.get(0).Translation__c;
            } else {
                return paymentSummary.get(0).Type;
            }
        }
        
        return '';
    }
    
    public String getOrderDeliveryGroupSummary(String OrderSumId){
        List<OrderDeliveryGroupSummary> OrderDeliveryGroupSum = [SELECT RI_TAX_ID__c FROM OrderDeliveryGroupSummary WHERE OrderSummaryId = :OrderSumId];
        if (OrderDeliveryGroupSum != null && !OrderDeliveryGroupSum.isEmpty()) {
            return OrderDeliveryGroupSum.get(0).RI_TAX_ID__c;
        }        
        return '';
    }
    
    
    public Map<String,String> getInvoiceTaxLineItems(List<InvoiceLine> lineItems, String templateCode){
        Map<Decimal, Decimal> invoiceTaxes       = new Map<Decimal, Decimal>();
        Map<String, String> invoiceTaxesSorted = new Map<String, String>();
        
        for (InvoiceLine lineItem:lineItems) {
            if (lineItem.Type.equalsIgnoreCase(SOM_Constants.INVOICE_LINE_TYPE_TAX)) {
                if (invoiceTaxes.containsKey(lineItem.TaxRate)) {
                    invoiceTaxes.put(lineItem.TaxRate,invoiceTaxes.get(lineItem.TaxRate)+lineItem.TaxAmount);
                } else {
                    invoiceTaxes.put(lineItem.TaxRate, lineItem.TaxAmount);
                }
                
            }
        } 
        
        List<Decimal> sortedTaxes = new List<Decimal>();
        sortedTaxes.addAll(invoiceTaxes.keySet());
        sortedTaxes.sort();
        if (templateCode == 'JP'){
            for(Decimal dec: sortedTaxes){
                invoiceTaxesSorted.put(setAmountsJPFormat(String.valueOf(dec)),setAmountsJPFormat(SOM_Utils.getTotalFormatted(invoiceTaxes.get(dec),AmountsFormat)));
            }
        }else{
            for(Decimal dec: sortedTaxes){
                invoiceTaxesSorted.put(String.valueOf(dec),(SOM_Utils.getTotalFormatted(invoiceTaxes.get(dec),AmountsFormat)));
            }
        }
        return invoiceTaxesSorted;
    }
    
    
    public String setAmountsFormat(String CountryIso) {
        Sales_Channel_Mapping__mdt AmountsFormat = [SELECT AmountsFormat__c FROM Sales_Channel_Mapping__mdt WHERE  Zone__c =: CountryIso];
        return AmountsFormat.AmountsFormat__c;
    } 
    
    public InvoiceAddress setInvoiceAddress(String Code) {
        InvoiceAddress invAddress     = new InvoiceAddress();
        Legal_Entity__c LegalEntity = [SELECT Id, Country__c, Code__c, Name, Address__c, City__c, ZipCode__c, CountryLabel__c,FooterBilling__c FROM Legal_Entity__c WHERE Code__c = :Code limit 1];
        invAddress.name = LegalEntity.Name; 
        invAddress.address = LegalEntity.Address__c ; 
        invAddress.countryLabel = LegalEntity.CountryLabel__c; 
        invAddress.FooterBilling = LegalEntity.FooterBilling__c; 
        return invAddress;
    } 
    
    public String setAmountsJPFormat(String Amount) {
		String AmountJP =  Amount.Substring(0,Amount.length()-3);
        return AmountJP;
    } 

    
    
    global with sharing class InvoiceDocument{
        public String                documentNumber {get; set;} //Invoice: DocumentNumber
        public String                invoiceDate {get; set;} //Invoice : InvoiceDate
        public String                orderNumber {get; set;} //OrderSummary : OrderNumber
        public String                currencyCode {get; set;} //FO : currency
        public InvoiceContact        billingContact {get; set;}
        public InvoiceContact        deliveryContact {get; set;}
        public String                trackingNumbers {get; set;}
        public List<InvoiceLineItem> lineItems {get; set;}
        public String                netSubTotal {get; set;}
        public String                totalWithTax {get; set;}
        public String                paymentType {get; set;}
        public String                Template {get; set;} 
        public String                TaxID {get; set;} 
        public String 				 CROSS_BORDER { get; set; }
    }
    
    
    
    global with sharing class InvoiceAddress{
        public String                name {get; set;} //Invoice: DocumentNumber
        public String                address {get; set;} //Invoice : InvoiceDate
        public String                countryLabel {get; set;} //OrderSummary : OrderNumber
        public String                VATID {get; set;} //FO : currency
        public String                FooterBilling {get; set;}
    }
    
    global with sharing class InvoiceContact{
        public String name {get; set;}
        public String company {get; set;} //mapping of the field??
        public String zipCode {get; set;}
        public String city {get; set;}
        public String address {get; set;}
        public String state {get; set;}
        public String country {get; set;}
    }
    
    //  implements Comparable
    global with sharing class InvoiceLineItem implements Comparable {
        public String  itemDescription {get; set;} //Product2 : description
        public Integer itemNumber {get; set;}//
        public String  serialNumber {get; set;} //serialnumber on shipping object
        public String  hsCode {get; set;} //custom field orderItemSummary
        public String  hsCodeDescription {get; set;}
        public String  coo {get; set;}
        public Decimal quantity {get; set;} //InvoiceLine : Quantity
        public String  netAmount {get; set;} //InvoiceLine : UnitPrice
        public String  vat {get; set;} //InvoiceLine: ChargeTaxAmount
        public String  grossAmount {get; set;} //invoiceLine : TotalAmountWithTax /Quantity
        public String  total {get; set;} //invoiceLine : TotalAmountWithTax
        //add number LineNumber
        public Integer lineNumber {get; set;}
        
        // compareTo method
        public Integer compareTo(Object compareTo) {
            // Cast argument to InvoiceLineItem
            InvoiceLineItem compareToOppy = (InvoiceLineItem)compareTo;
            
            // The return value of 0 indicates that both elements are equal.
            Integer returnValue = 0;
            if ((this.LineNumber == null) && (compareToOppy.LineNumber == null)) {
                // both objects have null LineNumber
                returnValue = 0;
            } else if ((this.LineNumber == null) && (compareToOppy.LineNumber != null)){
                // nulls-first implementation
                returnValue = -1;
            } else if ((this.LineNumber != null) && (compareToOppy.LineNumber == null)){
                // nulls-first implementation
                returnValue = 1;
            } else if (this.LineNumber > compareToOppy.LineNumber) {
                // Set return value to a positive value.
                returnValue = 1;
            } else if (this.LineNumber < compareToOppy.LineNumber) {
                // Set return value to a negative value.
                returnValue = -1;
            } 
            return returnValue;
        }
        
        
    }
}