unpackaged/main/default/objects/CorrectiveInvoice__c/CorrectiveInvoice__c.object-meta.xml
<CustomObject>
    <label>Corrective Invoice</label>
    <nameField>
        <label>Corrective Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corrective Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CorrectiveInvoice__c/fields/OriginalInvoiceId__c.field-meta.xml
<CustomField>
    <fullName>OriginalInvoiceId__c</fullName>
    <label>Original Invoice Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CorrectiveInvoice__c/fields/PDFGenerationStatus__c.field-meta.xml
<CustomField>
    <fullName>PDFGenerationStatus__c</fullName>
    <label>PDF Generation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Posted To BLOB Storage</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice/fields/PDFGenerationStatus__c.field-meta.xml
<CustomField>
    <fullName>PDFGenerationStatus__c</fullName>
    <label>PDF Generation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Posted To BLOB Storage</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SOM_CreateInvoicePDFFileAction.cls
global with sharing class SOM_CreateInvoicePDFFileAction {

    @InvocableMethod(label='Create Invoice PDF File' description='Create Invoice PDF file for the specified Invoice Id')
    global static void CreateInvoicePDFFileAction(List<Id> invoiceId){
        Attachment attachment = new Attachment();
        PageReference page;
        String OrderCountry;
        if(Schema.Invoice.SObjectType == invoiceId.get(0).getSobjectType()){
            Invoice invoice = [SELECT Id, DocumentNumber, InvoiceNumber__c, (SELECT Id, OrderSummary.OrderNumber, OrderSummaryId, FulfilledToCountry FROM FulfillmentOrders) FROM Invoice WHERE Id = :invoiceId.get(0)];
            attachment.Name = getInvoiceName(invoice.InvoiceNumber__c, invoice.FulfillmentOrders.get(0).OrderSummary.OrderNumber);
            OrderCountry = invoice.FulfillmentOrders.get(0).FulfilledToCountry;
            invoice.PDFGenerationStatus__c = SOM_Constants.PDF_GENERATION_STATUS_GENERATED;
            update invoice;
        } else if(Schema.CorrectiveInvoice__c.SObjectType == invoiceId.get(0).getSobjectType()){
            CorrectiveInvoice__c cInvoice = [SELECT Id, Name, OriginalInvoiceId__c FROM CorrectiveInvoice__c WHERE Id = :invoiceId.get(0)];
            Invoice invoice = [SELECT Id, DocumentNumber, InvoiceNumber__c, (SELECT Id, OrderSummary.OrderNumber, OrderSummaryId, FulfilledToCountry FROM FulfillmentOrders) FROM Invoice WHERE Id = :cInvoice.OriginalInvoiceId__c];
            attachment.Name = getInvoiceName(cInvoice.Name, invoice.FulfillmentOrders.get(0).OrderSummary.OrderNumber);
            OrderCountry = invoice.FulfillmentOrders.get(0).FulfilledToCountry;
            cInvoice.PDFGenerationStatus__c = SOM_Constants.PDF_GENERATION_STATUS_GENERATED;
            update cInvoice;
        }
        if(OrderCountry == 'AE') page = new PageReference('/apex/SOM_InvoiceArabicDocument');
        else page = new PageReference('/apex/SOM_InvoiceDocument');
        page.getParameters().put('invoiceId', invoiceId.get(0));
        page.getParameters().put('template', OrderCountry);

        if(Test.isRunningTest()) { 
            attachment.Body = blob.valueOf('Unit.Test');
          } else {
            attachment.Body = page.getContent();
          }
       
        attachment.IsPrivate  = false;
        attachment.ParentId   = invoiceId.get(0);

        insert attachment;
    }

    global static String getInvoiceName(String invoiceNumber, String orderNumber){
        return 'Invoice_'+ orderNumber +'_'+ invoiceNumber+'.pdf';
    }

}