unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLT_Clients_Test.cls
@isTest
private class CLT_Clients_Test {
    
    @isTest static void test_method_one() {
        Id recordTypeId = [SELECT Id FROM RecordType WHERE IsPersonType = true LIMIT 1].Id;

        Account account = new Account(LastName = 'Test', FirstName = 'Adam', Phone = '4848579', RecordTypeId = recordTypeId);
        insert account;
        
        ClientSource__c cs = new ClientSource__c(Client__c = account.Id, SourceCode__c = 'TST123');
        insert cs;
        
        Map<String, String> params = new Map<String, String>();
        Map<String, Object> body = new Map<String, Object>();
        params.put('Phone', '4848579');
        params.put('Id', 'test123');
        body.put('Id', 'test123');
        CLT_Clients cltClients = new CLT_Clients();

        Test.startTest();
        cltClients.retrieveGet(params);
        cltClients.retrieveDelete(params);
        params.clear();
        cltClients.retrievePost(params, body);
        Test.stopTest();
    }
    
}