unpackaged/main/default/objects/AccountAPI__c/AccountAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AccountAPI</label>
</CustomObject>

unpackaged/main/default/objects/AccountAPI__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client_Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccountAPI__c/fields/Client_secret__c.field-meta.xml
<CustomField>
    <fullName>Client_secret__c</fullName>
    <label>Client_secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccountAPI__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content-Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccountAPI__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccountAPI__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/WS_AccountUTL_TST.cls
/**
 * @description       : 
 * @author            : Ulrich M. NDONG NGOMO
 * @group             : 
 * @last modified on  : 03-10-2023
 * @last modified by  : Ulrich M. NDONG NGOMO
**/
@IsTest(SeeAllData=false)
public with sharing class WS_AccountUTL_TST {

    // Mock the AccountAPI__c object for testing
    public static AccountAPI__c createMockAccountAPI(String sObjectInstance) {
        AccountAPI__c api = new AccountAPI__c();
        api.Name = sObjectInstance;
        api.EndPoint__c = 'https://example.com/api';
        api.Method__c = 'POST';
        api.Content_Type__c = 'application/json';
        api.Client_Id__c = 'client_id';
        api.Client_secret__c = 'client_secret';
        insert api;
        return api;
    }
    
    @isTest
    static void testBuildRequest() {
        // Create a test AccountAPI__c record
        AccountAPI__c api = createMockAccountAPI('TestInstance');
        
        // Call the buildRequest method
        HttpRequest req = WS_AccountUTL.buildRequest('TestInstance');
        
        // Create a sample JSON content
        String jsonContent = '{"key": "value"}';
        Test.startTest();
        
        // Call the pushRequest method
        WS_AccountUTL.pushRequest(jsonContent, 'TestInstance');
        
        Test.stopTest();
        
        // Verify the values in the request
        System.assertEquals(api.EndPoint__c, req.getEndpoint());
        System.assertEquals(api.Method__c, req.getMethod());
        System.assertEquals(api.Content_Type__c, req.getHeader('Content-Type'));
        System.assertEquals(api.Client_Id__c, req.getHeader('client_id'));
        System.assertEquals(api.Client_secret__c, req.getHeader('client_secret'));
    }
}