unpackaged/main/default/objects/Client_List_Translation__c/Client_List_Translation__c.object-meta.xml
<CustomObject>
    <label>Client List Translation</label>
    <nameField>
        <label>Client List Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client List Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_List_Translation__c/fields/Client_List__c.field-meta.xml
<CustomField>
    <fullName>Client_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Translations</relationshipLabel>
    <relationshipName>Client_List_Translations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_List_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>FR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientList__c/fields/Ascendant__c.field-meta.xml
<CustomField>
    <fullName>Ascendant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ascendant</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ClientListQuery__c.field-meta.xml
<CustomField>
    <fullName>ClientListQuery__c</fullName>
    <label>ClientListQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/DisplayType__c.field-meta.xml
<CustomField>
    <fullName>DisplayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Total Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/InMyStore__c.field-meta.xml
<CustomField>
    <fullName>InMyStore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In My Store</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/IsDarkText__c.field-meta.xml
<CustomField>
    <fullName>IsDarkText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dark Text</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/IsManagerList__c.field-meta.xml
<CustomField>
    <fullName>IsManagerList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>Order By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>totalTurnover</fullName>
                <label>Total Amount Of Client Purchase</label>
            </value>
            <value>
                <fullName>lastPurchaseDate</fullName>
                <label>Last Purchase Date</label>
            </value>
            <value>
                <fullName>firstName</fullName>
                <label>First Name</label>
            </value>
            <value>
                <fullName>lastName</fullName>
                <label>Last Name</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplay__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplay__c</fullName>
    <label>Specific Field Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplayLabel__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplayLabel__c</fullName>
    <label>Specific Field Display Label</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/StaticList__c.field-meta.xml
<CustomField>
    <fullName>StaticList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Static List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Stores__c.field-meta.xml
<CustomField>
    <fullName>Stores__c</fullName>
    <label>Stores</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE00</fullName>
                <label>RIMOWA Orient Trading LLC</label>
            </value>
            <value>
                <fullName>AE01</fullName>
                <label>Dubai - Dubai Mall</label>
            </value>
            <value>
                <fullName>AE02</fullName>
                <label>Dubai - Mall of the Emirates</label>
            </value>
            <value>
                <fullName>AE03</fullName>
                <label>Dubai - Galeries Lafayette</label>
            </value>
            <value>
                <fullName>AT00</fullName>
                <label>RIMOWA Austria</label>
            </value>
            <value>
                <fullName>AT01</fullName>
                <label>Salzburg - Getreidegasse</label>
            </value>
            <value>
                <fullName>AT02</fullName>
                <label>Vienna - Seitzergasse</label>
            </value>
            <value>
                <fullName>AU00</fullName>
                <label>RIMOWA Australia</label>
            </value>
            <value>
                <fullName>AU01</fullName>
                <label>Melbourne - Chadstone</label>
            </value>
            <value>
                <fullName>AU02</fullName>
                <label>Sydney - Westfield</label>
            </value>
            <value>
                <fullName>AU03</fullName>
                <label>Sydney - David Jones</label>
            </value>
            <value>
                <fullName>AUCS</fullName>
                <label>Australia - Corporate Sales</label>
            </value>
            <value>
                <fullName>BR00</fullName>
            </value>
            <value>
                <fullName>BR01</fullName>
                <label>São Paulo - Fasano Jardins</label>
            </value>
            <value>
                <fullName>BR02</fullName>
                <label>Rio de Janeiro - Shopping Leblon</label>
            </value>
            <value>
                <fullName>BR03</fullName>
                <label>São Paulo - Iguatemi São Paulo</label>
            </value>
            <value>
                <fullName>BR04</fullName>
                <label>Brasília - Iguatemi Brasilia</label>
            </value>
            <value>
                <fullName>BR05</fullName>
                <label>Rio de Janeiro - Barra da Tujica</label>
            </value>
            <value>
                <fullName>BR06</fullName>
                <label>Belo Horizonte - BH Shopping</label>
            </value>
            <value>
                <fullName>BR07</fullName>
                <label>Curitiba - Patio Batel</label>
            </value>
            <value>
                <fullName>BR08</fullName>
                <label>São Paulo - JK Iguatemi</label>
            </value>
            <value>
                <fullName>BR09</fullName>
                <label>São Roque - Catarina Fashion Outlet</label>
            </value>
            <value>
                <fullName>BR10</fullName>
                <label>RIMOWA CARE</label>
            </value>
            <value>
                <fullName>CA00</fullName>
                <label>Toronto - Bloor Street</label>
            </value>
            <value>
                <fullName>CA02</fullName>
                <label>Vancouver- Alberni Street</label>
            </value>
            <value>
                <fullName>CA90</fullName>
                <label>RIMOWA Cambridge HQ</label>
            </value>
            <value>
                <fullName>CN00</fullName>
                <label>RIMOWA China</label>
            </value>
            <value>
                <fullName>CN01</fullName>
                <label>Beijing - SKP Beijing</label>
            </value>
            <value>
                <fullName>CN02</fullName>
                <label>Shanghai Service Centre</label>
            </value>
            <value>
                <fullName>CN03</fullName>
                <label>Shenyang Service Centre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membered</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/VisibilityBasedOnField__c.field-meta.xml
<CustomField>
    <fullName>VisibilityBasedOnField__c</fullName>
    <label>Visibility Based On Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local_Main_CA__c</fullName>
            </value>
            <value>
                <fullName>Last_Transaction_SA__pc</fullName>
            </value>
            <value>
                <fullName>ClientAdvisor__pc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/IsManager__c.field-meta.xml
<CustomField>
    <fullName>IsManager__c</fullName>
    <formula>CONTAINS(Profile.Name , &#39;Manager&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Manager</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLT_ClientList.cls
global with sharing class CLT_ClientList implements CLT_RetailInterface{
    public Object retrieveDelete(Map<String, String> params){
        return null;
    }

    global Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    global Object retrieveGet(Map<String, String> params){
        return getClientLists((String)params.get('Type'));
    }

//------------------------------------START GET Client List------------------------------------------------------------------------

    Map<String, Object> getClientLists(String clientListId){
        list<ClientListWrapper> clientsListWrapper = new list<ClientListWrapper>();
        User currentUser = [SELECT IsManager__c, StoreCode__c FROM User WHERE Id =: UserInfo.getUserId()];
        Boolean isManager = currentUser.IsManager__c == null ? false : currentUser.IsManager__c;
        Boolean isSpecificClientList = String.isEmpty(clientListId) ? false : true;

        Set<String> clientListIds = new Set<String>();
        String userId = UserInfo.getUserId();
        Set<Object> clients = new Set<Object>();
        User userInfo = CLT_Utils_Query.getUserInfos();
        string storeCode = userInfo.StoreCode__c;
        Set<Id> allClientIds = new Set<Id>();
//        Boolean isManager = userInfo.Is_Manager__c;

        List<ClientList__c > clientLists = getClientLists(clientListId, isManager, storeCode);

        for (ClientList__c clientList: clientLists){
            Set<Id> clientIds = new Set<Id>();
            clientListIds.add(clientList.Id);
    
            if(!String.isEmpty(clientList.clientListQuery__c) || clientList.Type__c == 'Membered'){
                String clientsQuery = CLT_Utils_Query.getClientsQuery(false, false) + CLT_Utils_ClientLists.buildDynamicQuery(clientList, userId, storeCode, isSpecificClientList);
//                String clientsQuery = 'SELECT Id From Account WHERE ID != \'\' ' + CLT_Utils_ClientLists.buildDynamicQuery(clientList, userId, storeCode);
                system.debug(clientsQuery);
                Map<Id, Account> dynamicClients = new Map<Id, Account>((List<Account>)Database.query(clientsQuery));
                clientIds.addAll(dynamicClients.keySet());
                List<Account> clientsToAdd = getClientToAdd(dynamicClients.values(), allClientIds);
                allClientIds.addAll(clientIds);
                clients.addAll((List<Object>)CLT_Utils_Mapping.getStandardWrapperListFromObjectList('Account', 'Client', clientsToAdd));
                
                clientsListWrapper.add(new ClientListWrapper(clientList, clientIds));
            }
        }  

        Map<String, Object> result = new Map<String, Object>();
        result.put('clientLists', clientsListWrapper);
        result.put('clients', clients);
        result.put('documents', CLT_Utils.getDocuments(clientListIds));

        return result;
    }

    private List<Account> getClientToAdd(List<Account> clients, Set<Id> clientIds) {
        List<Account> ret = new List<Account>();

        for (Account client : clients){
            if (!clientIds.contains(client.Id)){
                ret.add(client);
            }
        }
        return ret;
    }

    List<ClientList__c> getClientLists(String clientListId, Boolean isManager, String storeCode){
        string query = 'SELECT Id,OwnerId,Owner.FirstName,CreatedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,' +
                                'IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c, ' + 
                                '(SELECT Description__c,Title__c,Name FROM Client_List_Translations__r' +
                                ' WHERE Language__c = \'' + UserInfo.getLanguage() +'\' LIMIT 1)' +
                        ' FROM ClientList__c ' +
            			' WHERE Id != \'\' AND (Stores__c includes (\'' + storeCode + '\') OR Stores__c = \'\')';
        
        if(clientListId != null){
            query += ' AND Id = \'' + clientListId + '\'';
        }
        if(!isManager){
            query += 'AND IsManagerList__c = false';
        }

        System.debug('queryyyy '+ query);
        return Database.query(query);
    }
//------------------------------------END   GET Client List------------------------------------------------------------------------

    class ClientListWrapper{
        public String id {get;set;}
        public String name {get;set;}
        public String createdDate {get;set;}
        public String listDescription {get;set;}
        public Decimal position {get;set;}
        public String ownerId {get;set;}
        public String type {get;set;}
        public Boolean isStaticList {get; set;}
        public Boolean isDarkText {get;set;}
        public Boolean ascendant {get;set;}
        public String orderBy {get;set;}
        public string displayType {get;set;}
        public string specificFieldDisplay {get; set;}
        public string specificFieldDisplayLabel {get; set;}
        public Set<Id> clientIds {get;set;}
  

        ClientListWrapper(ClientList__c clientList, Set<Id> clientIds){
            this(clientList);
            this.clientIds = clientIds;
        }

        ClientListWrapper(ClientList__c clientList){
            this.id = clientList.Id;
            this.isStaticList = clientList.StaticList__c;
            this.isDarkText = clientList.IsDarkText__c;
            this.orderBy = clientList.OrderBy__c;
            this.ascendant = clientList.Ascendant__c;
            this.displayType = clientList.DisplayType__c;
            this.specificFieldDisplay = clientList.SpecificFieldDisplay__c;
            this.specificFieldDisplayLabel = clientList.SpecificFieldDisplayLabel__c;
            this.position = clientList.position__c;
            this.name = clientList.Name;
            this.listDescription = clientList.Description__c;
            this.ownerId = clientList.OwnerId;
            this.createdDate = clientList.CreatedDate.format('yyyy-MM-dd');


            if (!clientList.Client_List_Translations__r.isEmpty()){
                this.listDescription = clientList.Client_List_Translations__r.get(0).Description__c;
                this.name = clientList.Client_List_Translations__r.get(0).Title__c;
            }
        }
    }
}