unpackaged/main/default/objects/Client_List_Translation__c/Client_List_Translation__c.object-meta.xml
<CustomObject>
    <label>Client List Translation</label>
    <nameField>
        <label>Client List Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client List Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_List_Translation__c/fields/Client_List__c.field-meta.xml
<CustomField>
    <fullName>Client_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Translations</relationshipLabel>
    <relationshipName>Client_List_Translations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_List_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>FR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientList__c/fields/AlwaysLimitedList__c.field-meta.xml
<CustomField>
    <fullName>AlwaysLimitedList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Always Limited List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Ascendant__c.field-meta.xml
<CustomField>
    <fullName>Ascendant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ascendant</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ClientListQuery__c.field-meta.xml
<CustomField>
    <fullName>ClientListQuery__c</fullName>
    <label>ClientListQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ContactedSectionDisplayPeriod__c.field-meta.xml
<CustomField>
    <fullName>ContactedSectionDisplayPeriod__c</fullName>
    <label>Contacted Section Display Period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/DisplayToReachOutContactedSection__c.field-meta.xml
<CustomField>
    <fullName>DisplayToReachOutContactedSection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display To Reach Out/Contacted Section</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/DisplayType__c.field-meta.xml
<CustomField>
    <fullName>DisplayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Total Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/InMyStore__c.field-meta.xml
<CustomField>
    <fullName>InMyStore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In My Store</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/IsDarkText__c.field-meta.xml
<CustomField>
    <fullName>IsDarkText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dark Text</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>Order By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>totalTurnover</fullName>
                <label>Total Amount Of Client Purchase</label>
            </value>
            <value>
                <fullName>lastPurchaseDate</fullName>
                <label>Last Purchase Date</label>
            </value>
            <value>
                <fullName>firstName</fullName>
                <label>First Name</label>
            </value>
            <value>
                <fullName>lastName</fullName>
                <label>Last Name</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplay__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplay__c</fullName>
    <label>Specific Field Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/SpecificFieldDisplayLabel__c.field-meta.xml
<CustomField>
    <fullName>SpecificFieldDisplayLabel__c</fullName>
    <label>Specific Field Display Label</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/StaticList__c.field-meta.xml
<CustomField>
    <fullName>StaticList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Static List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membered</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/VisibilityBasedOnField__c.field-meta.xml
<CustomField>
    <fullName>VisibilityBasedOnField__c</fullName>
    <label>Visibility Based On Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local_Main_CA__c</fullName>
            </value>
            <value>
                <fullName>Last_Transaction_SA__pc</fullName>
            </value>
            <value>
                <fullName>ClientAdvisor__pc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>ClientListMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Reach Out</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <description>RMS Repair Order</description>
    <label>Repair Order</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Asia Pacific</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>South America</label>
            </value>
            <value>
                <fullName>AMERIC</fullName>
                <label>America</label>
            </value>
            <value>
                <fullName>EUROPE</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>MEAST</fullName>
                <label>Middle East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUT</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>FSS</fullName>
                <label>Free Standing Store</label>
            </value>
            <value>
                <fullName>CCC</fullName>
                <label>Customer Care Center</label>
            </value>
            <value>
                <fullName>SIS</fullName>
                <label>Shop-in-shop</label>
            </value>
            <value>
                <fullName>SUB</fullName>
                <label>Subsidiary Head Quarter</label>
            </value>
            <value>
                <fullName>WHS</fullName>
                <label>Wharehouse</label>
            </value>
            <value>
                <fullName>HDQ</fullName>
                <label>Heardquarter</label>
            </value>
            <value>
                <fullName>POP</fullName>
                <label>Pop Up Store</label>
            </value>
            <value>
                <fullName>ECO</fullName>
                <label>eCommerce store</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/IsManager__c.field-meta.xml
<CustomField>
    <fullName>IsManager__c</fullName>
    <formula>CONTAINS(Profile.Name , &#39;Manager&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Manager</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Asia Pacific</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Japan</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>AMERIC</fullName>
        <label>America</label>
    </customValue>
    <customValue>
        <fullName>EUROPE</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>MEAST</fullName>
        <label>Middle East</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLT_ClientList.cls
global with sharing class CLT_ClientList implements CLT_RetailInterface{
    public Object retrieveDelete(Map<String, String> params){
        return null;
    }

    global Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    global Object retrieveGet(Map<String, String> params){
        Boolean noLimit = params.containsKey('noLimit') ? Boolean.valueOf(params.get('noLimit')) : false;

        return getClientLists((String)params.get('Type'), noLimit);
    }

//------------------------------------START GET Client List------------------------------------------------------------------------

    Map<String, Object> getClientLists(String clientListId, Boolean noLimit){
        list<ClientListWrapper> clientsListWrapper = new list<ClientListWrapper>();
        User currentUser = [SELECT IsManager__c, StoreCode__c FROM User WHERE Id =: UserInfo.getUserId()];
        Boolean isManager = currentUser.IsManager__c == null ? false : currentUser.IsManager__c;
        Boolean isSpecificClientList = String.isEmpty(clientListId) ? false : true;

        Set<String> clientListIds = new Set<String>();
        String userId = UserInfo.getUserId();
        Set<Object> clients = new Set<Object>();
        User userInfo = CLT_Utils_Query.getUserInfos();
        string storeCode = userInfo.StoreCode__c;
        Set<Id> allClientIds = new Set<Id>();
//        Boolean isManager = userInfo.Is_Manager__c;

        List<ClientList__c > clientLists = getClientLists(clientListId, isManager, storeCode);

        for (ClientList__c clientList: clientLists){
            Set<Id> clientIds = new Set<Id>();
            clientListIds.add(clientList.Id);
    
            if(!String.isEmpty(clientList.clientListQuery__c)){
                String clientsQuery = CLT_Utils_Query.getClientsQuery(false, false) + CLT_Utils_ClientLists.buildDynamicQuery(clientList, userId, storeCode, isSpecificClientList, noLimit);
//                String clientsQuery = 'SELECT Id From Account WHERE ID != \'\' ' + CLT_Utils_ClientLists.buildDynamicQuery(clientList, userId, storeCode);
                system.debug(clientsQuery);
                Map<Id, Account> dynamicClients = new Map<Id, Account>((List<Account>)Database.query(clientsQuery));
                clientIds.addAll(dynamicClients.keySet());
                List<Account> clientsToAdd = getClientToAdd(dynamicClients.values(), allClientIds);
                allClientIds.addAll(clientIds);
                clients.addAll((List<Object>)CLT_Utils_Mapping.getStandardWrapperListFromObjectList('Account', 'Client', clientsToAdd));
                
                clientsListWrapper.add(new ClientListWrapper(clientList, clientIds));
            }
            else if(clientList.Type__c == 'Membered'){
                List<Map<String,Object>> membersWithStatusMap = new List<Map<String,Object>>();
                for(ClientListMember__c clm : [SELECT Client__c, Status__c
                                            FROM ClientListMember__c
                                            WHERE ClientList__c = :clientList.Id AND Client__r.ClientAdvisor__pc = :System.UserInfo.getUserId()]) {
                    membersWithStatusMap.add(new Map<String,Object>{
                        'id' => clm.Client__c,
                        'status' => clm.Status__c
                    });
                    clientIds.add(clm.Client__c);
                }
                String clientsToAddQuery = CLT_Utils_Query.getClientsQuery(false, false) + ' AND Id IN :clientIds AND Id NOT IN :allClientIds';
                List<Account> clientsToAdd = (List<Account>)Database.query(clientsToAddQuery);
                allClientIds.addAll(clientIds);
                clients.addAll((List<Object>)CLT_Utils_Mapping.getStandardWrapperListFromObjectList('Account', 'Client', clientsToAdd));
                
                clientsListWrapper.add(new ClientListWrapper(clientList, clientIds, membersWithStatusMap));
                
            }
        }  

        Map<String, Object> result = new Map<String, Object>();
        result.put('clientLists', clientsListWrapper);
        result.put('clients', clients);
        result.put('documents', CLT_Utils.getDocuments(clientListIds));

        return result;
    }

    private List<Account> getClientToAdd(List<Account> clients, Set<Id> clientIds) {
        List<Account> ret = new List<Account>();

        for (Account client : clients){
            if (!clientIds.contains(client.Id)){
                ret.add(client);
            }
        }
        return ret;
    }

    List<ClientList__c> getClientLists(String clientListId, Boolean isManager, String storeCode){
        string query = 'SELECT Id,OwnerId,Owner.FirstName,CreatedDate,LastModifiedDate,Type__c,Owner.LastName,Description__c,Position__c,Name,ClientListQuery__c,InMyStore__c,StaticList__c,' +
                                'IsDarkText__c,OrderBy__c,Ascendant__c,DisplayType__c,VisibilityBasedOnField__c,SpecificFieldDisplay__c,SpecificFieldDisplayLabel__c,' +
                                'DisplayToReachOutContactedSection__c,ContactedSectionDisplayPeriod__c,AlwaysLimitedList__c, ' + 
                                '(SELECT Description__c,Title__c,Name FROM Client_List_Translations__r' +
                                ' WHERE Language__c = \'' + UserInfo.getLanguage() +'\' LIMIT 1)' +
                        ' FROM ClientList__c ' +
            			' WHERE Id != \'\' AND Type__c != \'Personal\' ';
        List<Store__c> storesList = [SELECT Region__c,Country__c,SourceStoreId__c FROM Store__c WHERE SourceStoreId__c = :storeCode LIMIT 1];
        String perimeterCond = '';
        if(storesList.size() > 0) {
            Store__c store = storesList[0];
            perimeterCond += !String.isEmpty(store.Region__c) ? ' AND (Region__c = \'\' OR Region__c INCLUDES (\'' + store.Region__c + '\'))' : ' AND (Region__c = \'\')';
            perimeterCond += !String.isEmpty(store.Country__c) ? ' AND (Country__c = \'\' OR Country__c INCLUDES (\'' + store.Country__c + '\'))' : ' AND (Country__c = \'\')';
            perimeterCond += !String.isEmpty(store.SourceStoreId__c) ? ' AND (Stores__c = \'\' OR Stores__c INCLUDES (\'' + store.SourceStoreId__c + '\'))' : ' AND (Stores__c = \'\')';
        }
        else {
            perimeterCond += ' AND (Region__c = \'\')';
            perimeterCond += ' AND (Country__c = \'\')';
            perimeterCond += ' AND (Stores__c = \'\')';
        }

        query += perimeterCond;
        
        if(clientListId != null){
            query += ' AND Id = \'' + clientListId + '\' ';
        }
        else if (String.isEmpty(clientListId)) {
            List<String> memberdListIds = new List<String>();
            for(AggregateResult ar : [SELECT ClientList__c clientListId 
                                    FROM ClientListMember__c 
                                    WHERE ClientList__r.Type__c = 'Membered' AND ClientList__r.IsActive__c = TRUE AND 
                                        (ClientList__r.StartDate__c <= TODAY OR ClientList__r.StartDate__c = NULL) AND 
                                        (ClientList__r.EndDate__c >= TODAY OR ClientList__r.EndDate__c = NULL) AND 
                                        Client__r.ClientAdvisor__pc = :UserInfo.getUserId() 
                                    GROUP BY ClientList__c ]) {
                memberdListIds.add((String)ar.get('clientListId'));
            }
            query += ' AND (Type__c != \'Membered\' OR (Type__c = \'Membered\' AND Id IN (\'' + String.join(memberdListIds, '\',\'') +'\'))) ';
        }
        if(!isManager){
            query += ' AND IsManagerList__c = false ';
        }

        System.debug('queryyyy '+ query);
        return Database.query(query);
    }
//------------------------------------END   GET Client List------------------------------------------------------------------------

    public class ClientListWrapper{
        public String id {get;set;}
        public String name {get;set;}
        public String createdDate {get;set;}
        public DateTime modifiedDate {get;set;}
        public String listDescription {get;set;}
        public Decimal position {get;set;}
        public String ownerId {get;set;}
        public String type {get;set;}
        public Boolean isStaticList {get; set;}
        public Boolean displayToReachOutContactedSection {get; set;}
        public Integer contactedSectionDisplayPeriod {get; set;}
        public Boolean isDarkText {get;set;}
        public Boolean ascendant {get;set;}
        public String orderBy {get;set;}
        public string displayType {get;set;}
        public string specificFieldDisplay {get; set;}
        public string specificFieldDisplayLabel {get; set;}
        public Set<Id> clientIds {get;set;}
        public List<Map<String,Object>> membersWithStatus {get;set;}

        public ClientListWrapper(ClientList__c clientList, Set<Id> clientIds, List<Map<String,Object>> membersWithStatus){
            this(clientList, clientIds);
            this.membersWithStatus = membersWithStatus;
        }

        public ClientListWrapper(ClientList__c clientList, Set<Id> clientIds){
            this(clientList);
            this.clientIds = clientIds;
        }

        public ClientListWrapper(ClientList__c clientList){
            this.id = clientList.Id;
            this.isStaticList = clientList.StaticList__c;
            this.displayToReachOutContactedSection = clientList.DisplayToReachOutContactedSection__c;
            this.contactedSectionDisplayPeriod = (Integer)clientList.ContactedSectionDisplayPeriod__c;
            this.isDarkText = clientList.IsDarkText__c;
            this.orderBy = clientList.OrderBy__c;
            this.ascendant = clientList.Ascendant__c;
            this.displayType = clientList.DisplayType__c;
            this.specificFieldDisplay = clientList.SpecificFieldDisplay__c;
            this.specificFieldDisplayLabel = clientList.SpecificFieldDisplayLabel__c;
            this.position = clientList.position__c;
            this.name = clientList.Name;
            this.listDescription = clientList.Description__c;
            this.ownerId = clientList.OwnerId;
            this.type = clientList.Type__c;
            this.createdDate = clientList.CreatedDate.format('yyyy-MM-dd');
            this.modifiedDate = clientList.LastModifiedDate;


            if (!clientList.Client_List_Translations__r.isEmpty()){
                this.listDescription = clientList.Client_List_Translations__r.get(0).Description__c;
                this.name = clientList.Client_List_Translations__r.get(0).Title__c;
            }
        }
    }
}