unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/TransactionHandlerTest.cls
@isTest
private class TransactionHandlerTest {

    static testMethod void myUnitTest() {
        /*ACCOUNT*/
		Account acc1 = new Account();  
        acc1.LastName = 'Serge';
    	insert acc1;
    
        
        Transaction__c trans = new Transaction__c();
        trans.Client__c = acc1.Id;
        trans.TransactionDate__c = date.today();
        insert trans;
        TransactionItem__c transItem = new TransactionItem__c();
        transItem.Client__c = acc1.Id;
        transItem.Transaction__c = trans.Id;
        insert transItem;
    }
}