unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/SourceTransactionId__c.field-meta.xml
<CustomField>
    <fullName>SourceTransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Source Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/TransactionPayment__c.object-meta.xml
<CustomObject>
    <label>Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Transaction Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionPayment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions Payments</relationshipLabel>
    <relationshipName>TransactionsPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/fields/PaidAmount__c.field-meta.xml
<CustomField>
    <fullName>PaidAmount__c</fullName>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions Payments</relationshipLabel>
    <relationshipName>TransactionsPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/WS_TransactionPaymentUTL_TST.cls
@IsTest(SeeAllData=false)
public class WS_TransactionPaymentUTL_TST {
    
    @isTest
    static void testUpsertTransactionPayment() {
        List<Account> accList = TestDataFactory.createSObjectList('Account', 1);
        Transaction__c transact = new Transaction__c(
            SourceTransactionId__c = 'TestSourceId',
            InclTaxAmount__c = 100.00
        );
        insert transact;

        TransactionPayment__c transactionPayment = new TransactionPayment__c(
            Transaction__c = transact.Id,
            PaidAmount__c = 50.00,
            Client__c = accList[0].Id
        );

        Test.startTest();
        String response = WS_TransactionPaymentUTL.upsertTransactionPayment(transactionPayment, transact);
        Test.stopTest();
        System.assertNotEquals('Some information are missing', response);
    }
}