unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/SourceTransactionId__c.field-meta.xml
<CustomField>
    <fullName>SourceTransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Source Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/TransactionPayment__c.object-meta.xml
<CustomObject>
    <label>Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Transaction Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionPayment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions Payments</relationshipLabel>
    <relationshipName>TransactionsPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/fields/PaidAmount__c.field-meta.xml
<CustomField>
    <fullName>PaidAmount__c</fullName>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CC_MASTER</fullName>
                <label>Master</label>
            </value>
            <value>
                <fullName>CC_VISA</fullName>
                <label>Visa</label>
            </value>
            <value>
                <fullName>C_PAYPAL</fullName>
                <label>Paypal</label>
            </value>
            <value>
                <fullName>CC_AMEX</fullName>
                <label>Amex</label>
            </value>
            <value>
                <fullName>AEC</fullName>
                <label>American Express CZK</label>
            </value>
            <value>
                <fullName>AEE</fullName>
                <label>American Express EUR</label>
            </value>
            <value>
                <fullName>AEG</fullName>
                <label>American Express GPB</label>
            </value>
            <value>
                <fullName>AEH</fullName>
                <label>American Express HKD</label>
            </value>
            <value>
                <fullName>AEK</fullName>
                <label>American Express KRW</label>
            </value>
            <value>
                <fullName>AEM</fullName>
                <label>American Express MOP</label>
            </value>
            <value>
                <fullName>AER</fullName>
                <label>American Express RMB</label>
            </value>
            <value>
                <fullName>AEU</fullName>
                <label>American Express AED</label>
            </value>
            <value>
                <fullName>APH</fullName>
                <label>Alipay HKD</label>
            </value>
            <value>
                <fullName>APK</fullName>
                <label>Alipay KRW</label>
            </value>
            <value>
                <fullName>APM</fullName>
                <label>Alipay MOP</label>
            </value>
            <value>
                <fullName>APR</fullName>
                <label>Alipay RMB</label>
            </value>
            <value>
                <fullName>APU</fullName>
                <label>Alipay AED</label>
            </value>
            <value>
                <fullName>ARC</fullName>
                <label>Paid Deposit CZK</label>
            </value>
            <value>
                <fullName>ARE</fullName>
                <label>paid deposits EUR</label>
            </value>
            <value>
                <fullName>ARG</fullName>
                <label>paid Deposit GPB</label>
            </value>
            <value>
                <fullName>ARH</fullName>
                <label>Paid Deposit HKD</label>
            </value>
            <value>
                <fullName>ARK</fullName>
                <label>Paid Deposit KRW</label>
            </value>
            <value>
                <fullName>ARM</fullName>
                <label>Paid Deposit MOP</label>
            </value>
            <value>
                <fullName>ARR</fullName>
                <label>Paid Deposit RMB</label>
            </value>
            <value>
                <fullName>ARU</fullName>
                <label>Paid deposit AED</label>
            </value>
            <value>
                <fullName>AVC</fullName>
                <label>issued CZK</label>
            </value>
            <value>
                <fullName>AVE</fullName>
                <label>issued EUR</label>
            </value>
            <value>
                <fullName>AVG</fullName>
                <label>issued GPB</label>
            </value>
            <value>
                <fullName>AVR</fullName>
                <label>input EUR</label>
            </value>
            <value>
                <fullName>BCK</fullName>
                <label>BC Card KRW</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions Payments</relationshipLabel>
    <relationshipName>TransactionsPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/WS_TransactionPayment_TST.cls
/**
 * @description       : 
 * @author            : Ulrich M. NDONG NGOMO
 * @group             : 
 * @last modified on  : 20-10-2023
 * @last modified by  : Ulrich M. NDONG NGOMO
**/
@IsTest(SeeAllData=false)
public class WS_TransactionPayment_TST {
    
    @isTest
    static void upsertTransactionTest() {
        
        List<Account> accList = TestDataFactory.createSObjectList('Account', 1);
        Transaction__c transact = new Transaction__c(
            SourceTransactionId__c = 'TestSourceIdU',
            InclTaxAmount__c = 100.00
        );
        insert transact;

        TransactionPayment__c transactionPayment = new TransactionPayment__c(
            Transaction__c = transact.Id,
            PaidAmount__c = 50.00,
            Client__c = accList[0].Id
        );
        insert transactionPayment;

        // Create a sample JSON request body for testing.
        String requestBody = '{"CurrencyIsoCode": "EUR","Client__c": "'+accList[0].Id+'","PaymentMethod__c": null,"PaidAmount__c": -1090,"UCRCreationDate__c": "2020-02-14T00:00:00","UCRLastUpdateDate__c": "2020-02-14T00:00:00","Transaction__r": {"SourceTransactionId__c": "TestSourceIdU"}}';
        System.debug('requestBody'+requestBody);
        Blob requestBodyBlob = Blob.valueOf(requestBody);

        // Create a mock REST request and response.
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/ManageTransactionPayment/';
        request.httpMethod = 'POST';
        request.requestBody = requestBodyBlob;

        RestResponse response = new RestResponse();

        // Set the mock request and response.
        RestContext.request = request;
        RestContext.response = response;
        Test.startTest();
        String jsonResponse = WS_TransactionPayment.upsertTransactionPayment();
        Test.stopTest();
        
    }

}