unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/NotificationManagementId__c.field-meta.xml
<CustomField>
    <fullName>NotificationManagementId__c</fullName>
    <label>Notification Management Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Seen__c.field-meta.xml
<CustomField>
    <fullName>Seen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seen?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/SendingTime__c.field-meta.xml
<CustomField>
    <fullName>SendingTime__c</fullName>
    <label>Sending Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/TargetScreenId__c.field-meta.xml
<CustomField>
    <fullName>TargetScreenId__c</fullName>
    <label>Target Screen Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <description>RMS Repair Order</description>
    <label>Repair Order</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CLT_BatchSendPushNotifications_Test.cls
@isTest
private class CLT_BatchSendPushNotifications_Test {
    @TestSetup
	static void prepareTestData(){
		User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
        CLT_TestDateFactory.createTestNotification('TEST TYPE', sa.Id, DateTime.now(), true);
	}

    @isTest
    static void testCLT_BatchSendPushNotifications() {
        List<CLT_SendPushNotifications.FlowInputs> flowInput = new List<CLT_SendPushNotifications.FlowInputs>();
        for(Notification__c notif : [SELECT Id,User__c,NotificationManagementId__c,Type__c,Subtype__c,Seen__c,Read__c,SendingTime__c,Title__c,Body__c,RelatedRecordId__c,TargetScreenId__c,Client__c,Client__r.Name 
                                    FROM Notification__c]) {
            flowInput.add(new CLT_SendPushNotifications.FlowInputs(notif.Id, notif.User__c, notif.NotificationManagementId__c, notif.Type__c,notif.Subtype__c,
                notif.Title__c, notif.Body__c, notif.RelatedRecordId__c, notif.TargetScreenId__c, notif.Client__c, (notif.Client__c != null ? notif.Client__r.Name : '')));
        }
        Test.startTest();
        CLT_BatchSendPushNotifications b = new CLT_BatchSendPushNotifications(flowInput);
        Database.executeBatch(b, 10);
        Test.stopTest();
        
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;

        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        List<Notification__c> sentNotificationsListAfterBatch = [SELECT Id FROM Notification__c WHERE User__c = :sa.Id AND Sent__c = true];
        System.assertEquals(1, sentNotificationsListAfterBatch.size(), 'testCLT_BatchSendPushNotifications - Sent Notifications list size is not 1 after batch run');
    }
}