unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/NotificationManagementId__c.field-meta.xml
<CustomField>
    <fullName>NotificationManagementId__c</fullName>
    <label>Notification Management Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Seen__c.field-meta.xml
<CustomField>
    <fullName>Seen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seen?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/SendingTime__c.field-meta.xml
<CustomField>
    <fullName>SendingTime__c</fullName>
    <label>Sending Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/TargetScreenId__c.field-meta.xml
<CustomField>
    <fullName>TargetScreenId__c</fullName>
    <label>Target Screen Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <description>RMS Repair Order</description>
    <label>Repair Order</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CLT_BatchSendPushNotifications.cls
public with sharing class CLT_BatchSendPushNotifications implements Database.Batchable<sObject> {
    String query;
    List<String> notificationsIds = new List<String>();

    public CLT_BatchSendPushNotifications(List<CLT_SendPushNotifications.FlowInputs> flowInput) {
        for(CLT_SendPushNotifications.FlowInputs fi : flowInput) {
            if(!String.isEmpty(fi.id))
            notificationsIds.add(fi.id);
        }

        query = 'SELECT Id,User__c,NotificationManagementId__c,Type__c,Subtype__c,Seen__c,Read__c,SendingTime__c,Title__c,Body__c,RelatedRecordId__c,TargetScreenId__c,Client__c,Client__r.Name ' + 
                ' FROM Notification__c ' + 
                ' WHERE Id '+ (notificationsIds.size() > 0 ? ' IN :notificationsIds' : ' = NULL');
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Notification__c> scope) {
        List<CLT_SendPushNotifications.FlowInputs> flowInputToPush = new List<CLT_SendPushNotifications.FlowInputs>();
        for(Notification__c notif : scope) {
            flowInputToPush.add(new CLT_SendPushNotifications.FlowInputs(notif.Id, notif.User__c, notif.NotificationManagementId__c, notif.Type__c,
                notif.Subtype__c, notif.Title__c, notif.Body__c, notif.RelatedRecordId__c, notif.TargetScreenId__c, notif.Client__c, (notif.Client__c != null ? notif.Client__r.Name : ''))
            );
        }
        
        CLT_SendPushNotifications.sendNotifications(flowInputToPush);
    }

    public void finish(Database.BatchableContext BC) {
    }
}