unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Catalog_Product__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Product SKU</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CLT_ProductDetails_Test.cls
@isTest
private class CLT_ProductDetails_Test {
    @isTest
    static void test_ProductDetails() {
        Catalog_Product__c product = new Catalog_Product__c();
        product.Product_SKU__c = 'testSku1';
        product.Name = 'testSku1';
        
        insert product;
        
        CLT_ProductDetails productDetails = new  CLT_ProductDetails();
 		Test.startTest();

        productDetails.retrieveGet(new Map<String, String>{'productId' => product.Id});      
		productDetails.retrieveDelete(new Map<String, String>());
		productDetails.retrievePost(new Map<String, String>(),new Map<String,Object>());

		Test.stopTest();
    }
}