unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <description>RMS Repair Order</description>
    <label>Repair Order</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product List</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/removedItem__c.field-meta.xml
<CustomField>
    <fullName>removedItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>keep track of deleted items =&gt; instead of deleting the item of the wishlit when the user delete this item from the app, this checbox turns to true and we don&#39;t send it to the app anymore</description>
    <label>removedItem</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ProductDetails.cls
public class CLT_Utils_ProductDetails {

    //return details of my clients wishlist related to a specific product
    public static List<Map<String, Object>> getMyClientsRelatedWishlist(String productId, String userId) {
        List<Map<String, Object>> wishlists = CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishlistClient', 
            'FROM WishlistItem__c WHERE Product__c = \'' + productId + '\' AND CreatedById = \'' + userId + '\' AND removedItem__c = FALSE ORDER BY CreatedDate DESC');
        return wishlists;
    }

    //return details of my store clients wishlist related to a specific product
    public static List<Map<String, Object>> getStoreClientsRelatedWishlist(String productId, String storeCode) {
        List<Map<String, Object>> wishlists = CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishlistClient', 
            'FROM WishlistItem__c WHERE Product__c = \'' + productId + '\' AND CreatedBy.StoreCode__c = \'' + storeCode + '\' AND removedItem__c = FALSE ORDER BY CreatedDate DESC');
        return wishlists;
    }

    //return details of my clients wishlist related to a product family
    public static List<Map<String, Object>> getMyClientsRelatedFamilyWishlist(String name, String category, String accessoryType, String id, String userId) {
        String productFamilyCond;
        if(category == 'Luggage' || (category == 'Accessories' && accessoryType == 'Extras')) {
            productFamilyCond = 'Product__r.Name = \'' + name + '\'';
        }
        else {
            productFamilyCond = 'Product__r.Id = \'' + id + '\'';
        }
        List<Map<String, Object>> wishlists = CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishlistClient', 
            'FROM WishlistItem__c WHERE ' + productFamilyCond + ' AND Client__r.ClientAdvisor__pc = \'' + userId + '\' ORDER BY CreatedDate DESC');
        return wishlists;
    }

    //return details of my store clients wishlist related to a product family
    public static List<Map<String, Object>> getStoreClientsRelatedFamilyWishlist(String name, String category, String accessoryType, String id, String storeCode) {
        String productFamilyCond;
        if(category == 'Luggage' || (category == 'Accessories' && accessoryType == 'Extras')) {
            productFamilyCond = 'Product__r.Name = \'' + name + '\'';
        }
        else {
            productFamilyCond = 'Product__r.Id = \'' + id + '\'';
        }
        List<Map<String, Object>> wishlists = CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c', 'WishlistClient', 
            'FROM WishlistItem__c WHERE ' + productFamilyCond + ' AND Client__r.MainStore__pr.SourceStoreId__c = \'' + storeCode + '\' ORDER BY CreatedDate DESC');
        return wishlists;
    }

    //return all my tasks related to a specific product
    public static List<Map<String, Object>> getRelatedTasks(String productId, String userId){
        List<Map<String, Object>> tasks = CLT_Utils_Mapping.getStandardWrapperList('Task', 'productTask', 
            'FROM Task WHERE WhatId != null AND Related_Products__c LIKE \'%' + productId + '%\' AND OwnerId = \'' + userId + '\' AND Outreach_Type__c != \'Wishlist\' ORDER BY ActivityDate DESC');
        return tasks;
    }

    //return all store tasks related to a specific product
    public static List<Map<String, Object>> GetStoreRelatedTasks(String productId, String storeCode){
        List<Map<String, Object>> tasks = CLT_Utils_Mapping.getStandardWrapperList('Task', 'productTask', 
            'FROM Task WHERE WhatId != null AND Related_Products__c LIKE \'%' + productId + '%\' AND OwnerId IN (SELECT Id FROM User WHERE StoreCode__c = \'' + storeCode + '\') AND Outreach_Type__c != \'Wishlist\' ORDER BY ActivityDate DESC');
        return tasks;
    }
}