unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CLT_Email_Template__c/CLT_Email_Template__c.object-meta.xml
<CustomObject>
    <label>CLT Email Template</label>
    <nameField>
        <label>CLT Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLT Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CLT_Email_Template__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/CLT_Email_Template__c/fields/PersonalizedTemplate__c.field-meta.xml
<CustomField>
    <fullName>PersonalizedTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personalized Template?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CLT_Email_Template__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CLT_Email_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Event__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEIT 1898 TOKYO VIC Event</fullName>
            </value>
            <value>
                <fullName>Holiday Season 2023</fullName>
            </value>
            <value>
                <fullName>Seit 1898 NYC - VIC</fullName>
            </value>
            <value>
                <fullName>Seit 1898 NYC - VVIC</fullName>
            </value>
            <value>
                <fullName>Seit 1898 NYC - Public</fullName>
            </value>
            <value>
                <fullName>Adidas</fullName>
                <isActive>false</isActive>
                <label>Adidas</label>
            </value>
            <value>
                <fullName>NEC 7</fullName>
                <isActive>false</isActive>
                <label>NEC 7</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Event__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Asia Pacific</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>South America</label>
            </value>
            <value>
                <fullName>AMERIC</fullName>
                <label>America</label>
            </value>
            <value>
                <fullName>EUROPE</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>MEAST</fullName>
                <label>Middle East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Gift Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gift__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gift__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEIT 1898 TOKYO VIC Gift</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Chinese New Year 2022</fullName>
            </value>
            <value>
                <fullName>Holiday season 2022</fullName>
            </value>
            <value>
                <fullName>Mooncake box 2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gift__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Asia Pacific</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>South America</label>
            </value>
            <value>
                <fullName>AMERIC</fullName>
                <label>America</label>
            </value>
            <value>
                <fullName>EUROPE</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>MEAST</fullName>
                <label>Middle East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>TF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Asia Pacific</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>South America</label>
            </value>
            <value>
                <fullName>AMERIC</fullName>
                <label>America</label>
            </value>
            <value>
                <fullName>EUROPE</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>MEAST</fullName>
                <label>Middle East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Email_templates__c.field-meta.xml
<CustomField>
    <fullName>Email_templates__c</fullName>
    <label>Email templates</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLT_BatchNewElementNotif_Test.cls
@isTest
private class CLT_BatchNewElementNotif_Test {
    @TestSetup
    static void comboChallengeBatchPrepareData(){
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, false);
        sa.StoreCode__c = 'TST123';
        sa.Email_templates__c = 'FR;';
        insert sa;

		Store__c store = CLT_TestDateFactory.createTestStore('TST123', false);
        store.Region__c = '001';
        store.Country__c = 'FR';
        insert store;

        CLT_TestDateFactory.createTestRClientConfigurations(true);
    }

    @isTest
    static void CLT_BatchNewElementNotifTest() {
        String eventNameOption =  Event__c.Name__c.getDescribe().getPicklistValues()[0].getLabel();
        Event__c evnt = CLT_TestDateFactory.createTestClientelingEvent(eventNameOption, false);
        evnt.Region__c = '001';
        insert evnt;
        Test.setCreatedDate(evnt.Id, DateTime.now().addHours(-5));

        String giftNameOption =  Gift__c.Name__c.getDescribe().getPicklistValues()[0].getLabel();
        Gift__c gift = CLT_TestDateFactory.createTestGift(giftNameOption, false);
        gift.Region__c = '001';
        gift.Countries__c = 'FR';
        insert gift;
        Test.setCreatedDate(gift.Id, DateTime.now().addHours(-5));

        Catalog_Product__c catalogProduct = CLT_TestDateFactory.createTestProduct('TST123', true);
        Test.setCreatedDate(catalogProduct.Id, DateTime.now().addHours(-5));

        CLT_Email_Template__c cltEt = new CLT_Email_Template__c(
            JSON__c = JSON.serialize(new Map<String, Object> {'developerName' => 'French_EMAIL'}),
            Is_Active__c = true,
            PersonalizedTemplate__c = false
        );
        insert cltEt;
        Test.setCreatedDate(cltEt.Id, DateTime.now().addHours(-5));

        Test.startTest();
        CLT_BatchNewElementNotif b = new CLT_BatchNewElementNotif();
        Database.executeBatch(b);
        Test.stopTest();
        String testUserEmailPostfix = '%' + CLT_TestDateFactory.TEST_USER_EMAIL_POSTFIX;

        User sa = [SELECT Id FROM User WHERE Username LIKE :testUserEmailPostfix AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        List<Notification__c> notificationsListAfterBatch = [SELECT Id FROM Notification__c WHERE User__c = :sa.Id];
        System.assertEquals(4, notificationsListAfterBatch.size(), 'Notifications list size is not 4 after batch run');
    }

    @isTest
    static void CLT_SchedBatchNewElementNotifTest() {
        Test.startTest();
        CLT_BatchNewElementNotif schedBatch = new CLT_BatchNewElementNotif();
        String sch = '0 0 23 * * ?'; 
        Id jobId = System.schedule('Test CLT_BatchNewElementNotif Sched', sch, schedBatch);
        CronTrigger cronTrig = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(sch, cronTrig.CronExpression, 'CLT_SchedBatchNewElementNotifTest scheduler not set at the correct time');
        Test.stopTest();
    }
}