unpackaged/main/default/objects/Catalog_Product__c/Catalog_Product__c.object-meta.xml
<CustomObject>
    <label>Product (Catalog)</label>
    <nameField>
        <label>Product (Catalog) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalog)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Catalog_Product__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <externalId>true</externalId>
    <label>Product SKU</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Store Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Catalog_Product__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CLT_WishlistItem_Test.cls
@isTest
public class CLT_WishlistItem_Test {


    @isTest static void test_method_one() {
		Profile sysAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
		User u = new User();
		u.UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@rimowa.com';
		u.Email ='test@rimowa.com';
		u.LastName = 'test';
		u.ProfileId = sysAdmin.Id;
		u.LocaleSidKey = 'en_US';
		u.LanguageLocaleKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.EmailEncodingKey = 'UTF-8';
		u.Alias = 'user4t_';
		u.StoreCode__c = 'TE1';
		insert u;
        
        System.runAs(u){
        	Test.startTest();
            Store__c s = new Store__c();
            s.Name = 'Test Store';
            s.SourceStoreId__c = 'TE1';
            insert s;      
            
            Account acc = new Account();
            acc.LastName = 'Test';
            insert acc;
            
            Catalog_Product__c pdt = new Catalog_Product__c();
            pdt.Name = 'RTW';
            pdt.CurrencyIsoCode = 'EUR';
            pdt.Product_SKU__c = 'TestSKU';
            insert pdt;

        	Map <String, String> params = new Map <String, String>();
        	params.put('clientId', acc.Id);
        	String jsonString  = '{"clientId" : "' + acc.Id + '", "productId" : "' + pdt.Id + '"}';
       
        	CLT_WishlistItem cltWli = new CLT_WishlistItem();
            
            cltWli.retrievePost(params, (Map<String, Object>)JSON.deserializeUntyped(jsonString));
        	cltWli.retrieveGet(params);
            
            params.clear();
            // WishlistItem__c wi = [SELECT Id FROM WishlistItem__c WHERE Client__c =: acc.Id AND Product__c =: pdt.Id limit 1];
            // params.put('id', wi.Id);
            cltWli.retrieveDelete(params);
            Test.stopTest();
        }
        
    }


}