unpackaged/main/default/objects/Template_Images__c/Template_Images__c.object-meta.xml
<CustomObject>
    <label>Template Images</label>
    <nameField>
        <displayFormat>TI-{0000}</displayFormat>
        <label>Template Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Template_Images__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <label>Email Template Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Template_Images__c/fields/Image_1__c.field-meta.xml
<CustomField>
    <fullName>Image_1__c</fullName>
    <label>Image 1</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Template_Images__c/fields/Image_2__c.field-meta.xml
<CustomField>
    <fullName>Image_2__c</fullName>
    <label>Image 2</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/CLT_EmailTemplates_Test.cls
@isTest
private class CLT_EmailTemplates_Test {
    
    @testSetup
    static void setup() {
        Id emailTemplateId = [SELECT Id FROM EmailTemplate WHERE ( Folder.Name LIKE 'EN %' ) AND IsActive = TRUE LIMIT 1].Id;
        
        Template_Images__c ti = new Template_Images__c();
        ti.Email_Template_Id__c = emailTemplateId;
        ti.Image_1__c = 'www.google.com';
        ti.Image_2__c = 'www.google.com';
        insert ti;
    }

	@isTest static void test_method_one() {
		Map<String, String> params = new Map<String, String>();
		Map<String, Object> body = new Map<String, Object>();
		CLT_EmailTemplates cltemailTemplates = new CLT_EmailTemplates();

		Test.startTest();
		cltemailTemplates.retrieveGet(params);
		cltemailTemplates.retrievePost(params, body);
		cltemailTemplates.retrieveDelete(params);
        params.put('isNew','true');
        cltemailTemplates.retrieveGet(params);
		Test.stopTest();
	}

}