unpackaged/main/default/objects/Async_Job_Request__c/Async_Job_Request__c.object-meta.xml
<CustomObject>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>ASJ-{000000}</displayFormat>
        <label>Async Job Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Async_Job_Request__c/fields/ContextInformation__c.field-meta.xml
<CustomField>
    <fullName>ContextInformation__c</fullName>
    <label>Context Information</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RunningJobId__c.field-meta.xml
<CustomField>
    <fullName>RunningJobId__c</fullName>
    <label>Running Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/SerializedObject__c.field-meta.xml
<CustomField>
    <fullName>SerializedObject__c</fullName>
    <label>Serialized Object</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/TriggeringObject__c.field-meta.xml
<CustomField>
    <fullName>TriggeringObject__c</fullName>
    <defaultValue>&quot;Undefined&quot;</defaultValue>
    <label>Triggering Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NewLog</fullName>
        <default>true</default>
        <label>NewLog</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <masterLabel>Request Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AsyncRequestHandlerTest.cls
@isTest
private class AsyncRequestHandlerTest {
    
    @isTest static void testCreationOneAsyncRequest () {
        String sContext = 'AfterInsert', sType = 'Account';
        Account accountForTesting = new Account(FirstName = 'Chloé', LastName = 'Burté', PersonEmail = 'chloe.burte.test@gmail.com');
        insert accountForTesting;
        
        AsyncRequestHandler.RecordAsyncRequest(sContext,sType,accountForTesting);
        
        Test.startTest();
        List<Async_Job_Request__c> lAsyncRequestsTests = [SELECT Id, Name, TriggeringObject__c, RecordId__c, SerializedObject__c, Status__c, RunningJobId__c, ContextInformation__c  
                                                          FROM Async_Job_Request__c 
                                                          WHERE RecordId__c = :accountForTesting.Id ];
        Test.stopTest();
        
        System.AssertEquals(1, lAsyncRequestsTests?.size(), 'AsyncRequestHandlerTest - testCreationOneAsyncRequest - One Async_Job_Request__c record only should have been created');
    }     
	
    
    @isTest static void  testCreationSeveralAsyncRequest () {
    	String sContext = 'AfterInsert', sType = 'Account';
        List<Account> listAccountForTesting = new List<Account> ();
        For (integer i=0; i<50; i++) {
        	Account accountForTesting = new Account(FirstName = 'Chloé'+'_'+i, LastName = 'Burté'+'_'+i, PersonEmail = 'chloe.burte.test'+'_'+i+'@gmail.com');
            listAccountForTesting.add(accountForTesting);
        }
        insert listAccountForTesting;
        
        AsyncRequestHandler.RecordMultipleAsyncRequest(sContext,sType,listAccountForTesting);
        
        Test.startTest();
        List<Async_Job_Request__c> lAsyncRequestsTests = [SELECT Id, Name, TriggeringObject__c, RecordId__c, SerializedObject__c, Status__c, RunningJobId__c, ContextInformation__c 
                                                          FROM Async_Job_Request__c ];
        Test.stopTest();
        
        System.AssertEquals(50, lAsyncRequestsTests?.size(), 'AsyncRequestHandlerTest - testCreationOneAsyncRequest - One Async_Job_Request__c record only should have been created');
    }  
    
    @isTest static void testUpdateStatus () {
        Account accountForTesting = new Account(FirstName = 'Chloé', LastName = 'Burté', PersonEmail = 'chloe.burte.test@gmail.com');
        insert accountForTesting;
        List<Async_Job_Request__c> lAsyncRequestsTests = new List<Async_Job_Request__c> ();
        lAsyncRequestsTests.add(new Async_Job_Request__c(TriggeringObject__c='Account',Status__c='NewLog', recordId__c = accountForTesting.Id, ContextInformation__c = 'TESTUPDATE'));
        lAsyncRequestsTests.add(new Async_Job_Request__c(TriggeringObject__c='Account',Status__c='NewLog', recordId__c = accountForTesting.Id, ContextInformation__c = 'TESTUPDATE'));
        insert lAsyncRequestsTests;
        
        Test.startTest();
        AsyncRequestHandler.UpdateStatusOfAsyncRequest (lAsyncRequestsTests, AsyncRequestHandler.EnumStatus.InProgress);
        
        String sStatus = AsyncRequestHandler.EnumStatus.InProgress.name();
        List<Async_Job_Request__c> lAsyncRequestsSuiteUpdate = [SELECT Id, Name, TriggeringObject__c, RecordId__c, SerializedObject__c, Status__c, RunningJobId__c, ContextInformation__c 
                                                          		FROM Async_Job_Request__c
                                                                WHERE Status__c = :sStatus ];
        Test.stopTest();
        
        System.AssertEquals(2, lAsyncRequestsSuiteUpdate?.size(), 'AsyncRequestHandlerTest - testUpdateStatus - The method has not correctly updated the status of all tested Async_Job_Request__c');
   	}
    
    @isTest static void testUpdateJobId () {
        Account accountForTesting = new Account(FirstName = 'Chloé', LastName = 'Burté', PersonEmail = 'chloe.burte.test@gmail.com');
        insert accountForTesting;
        List<Async_Job_Request__c> lAsyncRequestsTests = new List<Async_Job_Request__c> ();
        Async_Job_Request__c a1 = new Async_Job_Request__c(TriggeringObject__c='Account',Status__c='NewLog', recordId__c = accountForTesting.Id, ContextInformation__c = 'TESTUPDATE');
        Async_Job_Request__c a2 = new Async_Job_Request__c(TriggeringObject__c='Account',Status__c='NewLog', recordId__c = accountForTesting.Id, ContextInformation__c = 'TESTUPDATE');
        lAsyncRequestsTests.add(a1);
        lAsyncRequestsTests.add(a2);
        insert lAsyncRequestsTests;
        
        Test.startTest();

        String sFakeJobId = '707KD00000FLXIjYAP';
        Id idFakeJobId = Id.valueOf(sFakeJobId);
        String sStatus = AsyncRequestHandler.EnumStatus.InProgress.name();
        
        AsyncRequestHandler.UpdateAsyncRequestWithJobid (lAsyncRequestsTests, idFakeJobId);       
        List<Async_Job_Request__c> lAsyncRequestsSuiteUpdate = [SELECT Id, Name, TriggeringObject__c, RecordId__c, SerializedObject__c, Status__c, RunningJobId__c, ContextInformation__c 
                                                          		FROM Async_Job_Request__c
                                                                WHERE RunningJobId__c = :sFakeJobId ];
        Test.stopTest();
        
        System.AssertEquals(2, lAsyncRequestsSuiteUpdate?.size(), 'AsyncRequestHandlerTest - testUpdateStatus - The method has not correctly updated the jobId of all tested Async_Job_Request__c');
    }
    
}