unpackaged/main/default/objects/Async_Job_Request__c/Async_Job_Request__c.object-meta.xml
<CustomObject>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>ASJ-{000000}</displayFormat>
        <label>Async Job Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Async_Job_Request__c/fields/ContextInformation__c.field-meta.xml
<CustomField>
    <fullName>ContextInformation__c</fullName>
    <label>Context Information</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RunningJobId__c.field-meta.xml
<CustomField>
    <fullName>RunningJobId__c</fullName>
    <label>Running Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/SerializedObject__c.field-meta.xml
<CustomField>
    <fullName>SerializedObject__c</fullName>
    <label>Serialized Object</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/TriggeringObject__c.field-meta.xml
<CustomField>
    <fullName>TriggeringObject__c</fullName>
    <defaultValue>&quot;Undefined&quot;</defaultValue>
    <label>Triggering Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NewLog</fullName>
        <default>true</default>
        <label>NewLog</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <masterLabel>Request Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AsyncRequestHandler.cls
public class AsyncRequestHandler {
    
    public enum EnumStatus {NewLog, InProgress, OK, KO}
	public enum EnumObjectType {Account, Undefined}
	
    public static void RecordAsyncRequest (string sContextInfo, string sObjectType, sObject sRecord) {
        Async_Job_Request__c asyncRequest = new Async_Job_Request__c( RecordId__c = sRecord.Id,
                                                                      Status__c = EnumStatus.NewLog.name(),
                                                                      TriggeringObject__c = sObjectType,
                                                                      ContextInformation__c = sContextInfo,
                                                                      SerializedObject__c = JSON.serialize(sRecord)
                                                                    );
        
        Insert asyncRequest;
    }
    
    public static void RecordMultipleAsyncRequest (string sContextInfo, string sObjectType, List<sObject> sRecords) {
        List <Async_Job_Request__c> lstAsyncRequests = new List<Async_Job_Request__c> ();
     
        for (sObject sCurrentObject : sRecords ) {
            Async_Job_Request__c asyncRequestLoopItem = new Async_Job_Request__c( RecordId__c = sCurrentObject.Id,
                                                                                  Status__c = EnumStatus.NewLog.name(),
                                                                                  TriggeringObject__c = sObjectType,
                                                                                  ContextInformation__c = sContextInfo,
                                                                                  SerializedObject__c = JSON.serialize(sCurrentObject)
                                                                                );
            lstAsyncRequests.add(asyncRequestLoopItem);            
        }        
      	Insert lstAsyncRequests;
    }
        
	public static void UpdateStatusOfAsyncRequest (List<Async_Job_Request__c> sRequest, EnumStatus enumStatusNewValue) {
        For (Async_Job_Request__c asjCurrent : sRequest) {
            asjCurrent.Status__c = EnumStatus.InProgress.name();
        }
        update sRequest;
    }
    
    public static void UpdateAsyncRequestWithJobid (List<Async_Job_Request__c> sRequest, ID jobID) {
        For (Async_Job_Request__c asjCurrent : sRequest) {
            asjCurrent.RunningJobId__c = jobID;
        }
        update sRequest;
    }
}