unpackaged/main/default/objects/Async_Job_Request__c/Async_Job_Request__c.object-meta.xml
<CustomObject>
    <label>Async Job Request</label>
    <nameField>
        <displayFormat>ASJ-{000000}</displayFormat>
        <label>Async Job Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Async_Job_Request__c/fields/ContextInformation__c.field-meta.xml
<CustomField>
    <fullName>ContextInformation__c</fullName>
    <label>Context Information</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/RunningJobId__c.field-meta.xml
<CustomField>
    <fullName>RunningJobId__c</fullName>
    <label>Running Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/SerializedObject__c.field-meta.xml
<CustomField>
    <fullName>SerializedObject__c</fullName>
    <label>Serialized Object</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Async_Job_Request__c/fields/TriggeringObject__c.field-meta.xml
<CustomField>
    <fullName>TriggeringObject__c</fullName>
    <defaultValue>&quot;Undefined&quot;</defaultValue>
    <label>Triggering Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Request_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NewLog</fullName>
        <default>true</default>
        <label>NewLog</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <masterLabel>Request Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Batch_HandleAsyncRequests_Sched_Test.cls
@isTest 
public class Batch_HandleAsyncRequests_Sched_Test {
	
    @isTest 
    static void testScheduledJob() { 
        // Execute the scheduled job in test context => Launch the job
        Test.startTest();
        
        // Create an account for reference
        Account accountForTesting = new Account(FirstName = 'Chloé', LastName = 'Burté', PersonEmail = 'chloe.burte.test@gmail.com');
        insert accountForTesting;
                
        // Create test accounts to be updated
        List<Async_Job_Request__c> lNewAsyncRequests = new List<Async_Job_Request__c> ();
		For (Integer i=0; i<100; i++) {
            Async_Job_Request__c currentAsyncRequest = new Async_Job_Request__c (TriggeringObject__c='Account',Status__c='NewLog', recordId__c = accountForTesting.Id, ContextInformation__c = 'TEST');
            lNewAsyncRequests.add(currentAsyncRequest);
        }
        For (Integer j=0; j<25; j++) {
            Async_Job_Request__c currentAsyncRequest = new Async_Job_Request__c (TriggeringObject__c='Account',Status__c='InProgress', recordId__c = accountForTesting.Id, ContextInformation__c = 'TEST');
            lNewAsyncRequests.add(currentAsyncRequest);
        }
        For (Integer k=0; k<25; k++) {
            Async_Job_Request__c currentAsyncRequest = new Async_Job_Request__c (TriggeringObject__c='Undefined', Status__c='InProgress', recordId__c = accountForTesting.Id, ContextInformation__c = 'TEST');
            lNewAsyncRequests.add(currentAsyncRequest);
        }
        insert lNewAsyncRequests;
        
        
        Batch_HandleAsyncRequests_Schedulable job = new Batch_HandleAsyncRequests_Schedulable(); 
        String jobId = System.schedule('Test Class - Test Batch_HandleAsyncRequests_Schedulable', '0 0 * * * ?', job);
        job.execute(null); 
                         
                
        // Verify that the job was scheduled 
        CronTrigger ct = [SELECT Id, CronExpression FROM CronTrigger WHERE Id = :jobId]; 
        System.assertNotEquals(null, ct, 'Test Class - Test Batch_HandleAsyncRequests_Schedulable - CronTrigger should not be null'); 

        // Verify that the data was processed 
        List<Async_Job_Request__c> lTestAsyncRequests = [SELECT Id, Name, TriggeringObject__c, RecordId__c, SerializedObject__c, Status__c, RunningJobId__c,
                                                         		ContextInformation__c, Createddate, lastmodifieddate, SystemModstamp
                                                                FROM Async_Job_Request__c
																WHERE Status__c = 'NewLog' AND ContextInformation__c = 'TEST'
																ORDER BY SystemModstamp ASC]; 
        System.assertEquals(100, lTestAsyncRequests.size(), 'Batch_HandleAsyncRequests_Sched_Test - testScheduledJob() - the list size is incorrect'); 
        
        Test.stopTest(); 

    } 
}