unpackaged/main/default/objects/BL_Translation__c/BL_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation Element for each Language</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BL_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>the language to be translated the source text</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar</fullName>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
            <value>
                <fullName>pt new</fullName>
                <label>Brazilian Portuguese new</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>nl</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>en_SG</fullName>
                <label>English (Singapore)</label>
            </value>
            <value>
                <fullName>en_GB</fullName>
                <label>English (United Kingdom)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BL_Translation__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DDC</fullName>
                <label>Digital Card</label>
            </value>
            <value>
                <fullName>CLT</fullName>
                <label>Clienteling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BL_EditTranslationCtrl_Test.cls
@IsTest
private class BL_EditTranslationCtrl_Test {
    
    private static testMethod void test_BL_EditTranslationCtrl() {
        BL_Translation__c record = new BL_Translation__c(
            Language__c = 'EN'
        );
        insert record;

        BL_EditTranslationCtrl.saveTranslationContent(record.Id, 'test');

        String content = BL_EditTranslationCtrl.getTranslationContent(record.Id);
        System.assertEquals('test', content);
    }

    private static testMethod void test_replaceKeys() {
        BL_EditTranslationCtrl.Translation translation = createTranslation('DDC', 'EN', '{"key1": "value1"}');
        
        Map<String,String> keysMap = new Map<String,String> { 'key1' => 'key2' };
        translation.replaceKeys(keysMap);

        Map<String,String> labelsMap = translation.getLabelsMap();
        System.debug('labelsMap: ' + labelsMap);
        System.assertNotEquals(null, labelsMap);
        System.assertEquals(1, labelsMap.size());
        System.assert(!labelsMap.containsKey('key1'));
        System.assert(labelsMap.containsKey('key2'));
        System.assertEquals('value1', labelsMap.get('key2'));
        System.assert(translation.isDirty);

        BL_EditTranslationCtrl.replaceKeysInTranslations('DDC', keysMap);
    }

    private static BL_EditTranslationCtrl.Translation createTranslation(
        String target, String language, String content)
    {
        BL_Translation__c record = new BL_Translation__c(
            Target__c = target,
            Language__c = language
        );
        insert record;

        ContentVersion contentVersion = BL_EditTranslationCtrl.createNewFile(record.Id, content);

        return new BL_EditTranslationCtrl.Translation(record, contentVersion);
    }
}