unpackaged/main/default/objects/BL_Translation__c/BL_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation Element for each Language</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BL_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>the language to be translated the source text</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar</fullName>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
            <value>
                <fullName>pt new</fullName>
                <label>Brazilian Portuguese new</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>nl</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>en_SG</fullName>
                <label>English (Singapore)</label>
            </value>
            <value>
                <fullName>en_GB</fullName>
                <label>English (United Kingdom)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BL_Translation__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DDC</fullName>
                <label>Digital Card</label>
            </value>
            <value>
                <fullName>CLT</fullName>
                <label>Clienteling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLT_Translation.cls
public class CLT_Translation implements CLT_RetailInterface {
    public Object retrieveDelete(Map<String, String> params){
        return null;
    }

    public Object retrievePost(Map<String, String> params, Map<String,Object> body){
        return null;
    }

    public Object retrieveGet(Map<String, String> params){
        String targetApplication = params.containsKey('target') ? (String)params.get('target') : 'CLT';
        return getLanguageData(targetApplication, UserInfo.getLanguage());
    }

    private Object getLanguageData(String targetApplication, String language){
        List<BL_Translation__c> trans = [SELECT Id 
                                    FROM BL_Translation__c 
                                    WHERE Language__c = :language AND Target__c = :targetApplication];
 
        Utils.addCustomHeader('QUERY','SELECT Id FROM BL_Translation__c WHERE Language__c = ' + language + ' AND Target__c = ' + targetApplication,RestContext.request);
 
        string transId;
        if(trans.size() > 0) {
            transId = trans[0].Id;
        }
        else {
            List<BL_Translation__c> defaultTrans = [SELECT Id FROM BL_Translation__c WHERE Language__c = 'en_US' AND Target__c = :targetApplication];
            if(defaultTrans.size() > 0) {
                transId = defaultTrans[0].Id;
            }
            else {
                throw new TranslationException(
                    'No default en_US translation with target = \'' + targetApplication + '\' were found.'
                    );
            }
        }

        List<ContentDocumentLink> contentDocs = [
            SELECT ContentDocumentId,Id,LinkedEntityId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :transId
        ];

        if(contentDocs.size() >= 0) {
            List<ContentVersion> contentVersions = [
                SELECT IsLatest,versionData,ContentDocumentId
                FROM ContentVersion
                WHERE IsLatest=true AND ContentDocumentId = :contentDocs[0].ContentDocumentId
            ];

            return contentVersions[0].versionData.toString();
        }
        else {
            throw new TranslationException(
                'No default contentDoc attached to translation: ' + transId
            );
        }
    }

    public class TranslationException extends Exception {
    }
}