unpackaged/main/default/objects/BL_Translation__c/BL_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation Element for each Language</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BL_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>the language to be translated the source text</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar</fullName>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
            <value>
                <fullName>pt new</fullName>
                <label>Brazilian Portuguese new</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>nl</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>en_SG</fullName>
                <label>English (Singapore)</label>
            </value>
            <value>
                <fullName>en_GB</fullName>
                <label>English (United Kingdom)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BL_TestCommon.cls
@isTest
public with sharing class BL_TestCommon { 
       

    public static BL_Translation__c createTranslation ( String lang ){
        BL_Translation__c trans = new BL_Translation__c();
        trans.Language__c = lang;
        insert trans;
        return trans; 
    }
    
    public static ContentDocumentLink createContentDocumentLink(Id recordId, String body){
        ContentVersion cv = createContentVersion(Blob.valueOf(body));
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=recordId;
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        return contentlink;
    }
    
    public static ContentVersion createContentVersion(Blob body){
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content';      
        cv.PathOnClient ='test';           
        cv.VersionData = body;          
        insert cv;
        return cv;
    }
    @isTest
    static void UtilsTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
         Test.startTest();
        RestRequest request = RestContext.request;
                Account account = new Account(Name = 'acc1');
        		insert account;
                List <Account> ac = new List<Account>();
         		ac.add(account);
        		List <String> acc = new List<String>();
         		acc.add('Account');
        		Set <String> accset = new Set<String>();
        		accset.add('Account');
                BL_Utils.getCurrentOrgLimits();
                BL_Utils.log('Success', account);
        Test.stopTest();
    }
    
}