unpackaged/main/default/objects/BL_Translation__c/BL_Translation__c.object-meta.xml
<CustomObject>
    <description>Translation Element for each Language</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BL_Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>the language to be translated the source text</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar</fullName>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
            <value>
                <fullName>pt new</fullName>
                <label>Brazilian Portuguese new</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>nl</fullName>
                <label>Dutch</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>en_SG</fullName>
                <label>English (Singapore)</label>
            </value>
            <value>
                <fullName>en_GB</fullName>
                <label>English (United Kingdom)</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>sv</fullName>
                <label>Swedish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BL_Translation__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DDC</fullName>
                <label>Digital Card</label>
            </value>
            <value>
                <fullName>CLT</fullName>
                <label>Clienteling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DDC_TranslationsCommon_WS_Test.cls
@isTest
private with sharing class DDC_TranslationsCommon_WS_Test {

    private static testMethod void test_getLanguageData() {
        // prepare data
        BL_Translation__c translation = new BL_Translation__c(Language__c = 'fr', Target__c = 'DDC');
        insert translation;
        ContentVersion docVersion = new ContentVersion(
            Title = 'test', 
            VersionData = Blob.valueOf('{ "shit": "merde" }'),
            PathOnClient = 'test');
        insert docVersion;
        docVersion = [select Id, ContentDocumentId from ContentVersion where Id = :docVersion.Id];
        ContentDocumentLink docLink = new ContentDocumentLink(
            LinkedEntityId = translation.Id, 
            ContentDocumentId = docVersion.ContentDocumentId);
        insert docLink;

        // test ws
        Map<String,String> pathParameters = new Map<String,String> { 'langCode' => 'fr' };
        DDC_TranslationsCommon_WS ws = new DDC_TranslationsCommon_WS();
        Map<String,Object> common = (Map<String,Object>) ws.executeGET(pathParameters, null);
        String value = (String) common.get('shit');
        System.assertEquals('merde', value);

        pathParameters.put('langCode', 'none');
        try {
            common = (Map<String,Object>) ws.executeGET(pathParameters, null);
        } catch (DDC_TranslationsCommon_WS.TranslationException ex) {}
    }
}