unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>ClientListMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Reach Out</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLT_Utils_ClientListMemberTrigger_Test.cls
/**
 * @author Eric Burté
 * @date March,26th 2023
 * @Type Apex Test Class
 *****************************************************************************************************************************************************************
 * @description This Test class contains the methods to test method from CLT_Utils_ClientListMemberTrigger Apex class :
 * testSetup : Creation of Client, ClientList and ClientListMember
 * CLASS			       				|	RELATED TEST METHOD						|	DESCRIPTION
 * CLT_Utils_ClientListMemberTrigger	|	testCreateUniqueClientListMember		|	Add different Client List Members in the CLM list to be updated
 * CLT_Utils_ClientListMemberTrigger	|	testCreateDuplicateClientListMember		|	Add the same Client List Member in the CLM list to be updated, expecting for an exception
 * 										|											|	
 * 
 * ****************************************************************************************************************************************************************
 * @Version : 
 * Version	|Date of modication	|Modified By	|Related Jira Ticket	|Description of changes			
 * 0.0		|2023/03/26			|.EBU			|.						|.original version
 * 0.1		|					|.				|.						|
 * 																		  
*/

@isTest
private class CLT_Utils_ClientListMemberTrigger_Test {
   
    @testSetup static void setup() {      
        //Client list creation
        ClientList__c clientlist1 = new clientlist__c (name = 'DreamPurse');
        insert clientlist1;
        
        //Client creation
        Account client1 = new Account (firstname = 'Eric', lastname='BurtéTEST');
        insert client1;
        Account client2 = new Account (firstname = 'Ulrich', lastname='SalesforceZane');
        insert client2;
        
        //Client list member creation
        ClientListMember__c clm1 = new ClientListMember__c (Client__c = client1.Id, ClientList__c = clientlist1.Id, Name = 'EricBurtéDreamPurse', Status__c = 'Contacted');
        insert clm1;      
        ClientListMember__c clm2 = new ClientListMember__c (Client__c = client2.Id, ClientList__c = clientlist1.Id, Name = 'UlrichDreamPurse', Status__c = 'Contacted');
        insert clm2;  
    }
    
    @isTest private static void testCreateUniqueClientListMember() {
        Boolean bSuccess = true;
        List<ClientListMember__c> newClientListMembers = new List<ClientListMember__c>();

        ClientListMember__c clientList1 = [SELECT Id FROM ClientListMember__c WHERE Name='EricBurtéDreamPurse' LIMIT 1];
        ClientListMember__c clientList2 = [SELECT Id FROM ClientListMember__c WHERE Name='UlrichDreamPurse' LIMIT 1];
                
        Test.startTest();
        newClientListMembers.add(clientList1);
        newClientListMembers.add(clientList2);
        
        try{
            update newClientListMembers;
        }catch (Exception e) {
        	bSuccess = false;
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        Test.stopTest();
        
        Assert.areEqual(true, bSuccess, 'CLT_Utils_ClientListMemberTrigger_Test - testCreateOnlyOneContactsBasedOnCLMcreation - The ClientListMember list insertion failed');
    }
     
    @isTest private static void testCreateDuplicateClientListMember() {
        Boolean bSuccess = true;
        List<ClientListMember__c> newClientListMembers = new List<ClientListMember__c>();

        ClientListMember__c clientList1 = [SELECT Id FROM ClientListMember__c WHERE Name='EricBurtéDreamPurse' LIMIT 1];
        ClientListMember__c clientList2 = [SELECT Id FROM ClientListMember__c WHERE Name='EricBurtéDreamPurse' LIMIT 1];
        
        newClientListMembers.add(clientList1);
        newClientListMembers.add(clientList2);
        
        Test.startTest();
        try{
            update newClientListMembers;
        }catch (Exception e) {
        	bSuccess = false;
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        Test.stopTest();
        
        Assert.areEqual(false, bSuccess, 'CLT_Utils_ClientListMemberTrigger_Test - testCreateAllContactsBasedOnCLMcreation - The ClientListMember list insertion should have failed');
    }  
}