unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientList__c/fields/AlwaysLimitedList__c.field-meta.xml
<CustomField>
    <fullName>AlwaysLimitedList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Always Limited List</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/ClientListQuery__c.field-meta.xml
<CustomField>
    <fullName>ClientListQuery__c</fullName>
    <label>ClientListQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/InMyStore__c.field-meta.xml
<CustomField>
    <fullName>InMyStore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In My Store</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membered</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/VisibilityBasedOnField__c.field-meta.xml
<CustomField>
    <fullName>VisibilityBasedOnField__c</fullName>
    <label>Visibility Based On Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local_Main_CA__c</fullName>
            </value>
            <value>
                <fullName>Last_Transaction_SA__pc</fullName>
            </value>
            <value>
                <fullName>ClientAdvisor__pc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/ClientListMember__c.object-meta.xml
<CustomObject>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Client List Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <label>Client List</label>
    <referenceTo>ClientList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>ClientListMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ClientLists.cls
/**
 * @author (Balink)
 * @Type Apex Class
 *****************************************************************************************************************************************************************
 * @description This class is used by CLT_ClientList to return to R-Client App the correct protfolio at the endpoint /retail/clientList
 ***************************************************************************************************************************************************************** 
 * @Version : 
 * Version	|Date of modication	|Modified By|Related Jira Ticket|Description of changes			
 * 0.0		|.      			|.      	|.          	    |.original version
 * 1.0		|2025/01/12			|.Sarah A	|.RCLIENT-1617	    |.add default order by creation date
*/
global with sharing class CLT_Utils_ClientLists {
    /*
     * @METHOD 	: buildDynamicQuery
     * @DESC 	: calculate the dynamic part of the query for the received client list according to tghe connected user
     * @PARAM 	: clientList-for whom the query is calculated, userId-the connected user, storeCode-of the connected user, isSpecificClientList- is it a single client list call,noLimit-remove the limit of nm records that are returned
     * @RETURN 	: String : the dynamic part of client query that is run for the cliemt list
     */
    global static String buildDynamicQuery(ClientList__c clientList, string userId, string storeCode, Boolean isSpecificClientList, Boolean noLimit){
        String defaultOrderByField = 'CreatedDate DESC';
        List<String> conditions = new List<String>();

        string myClientsCondition = '';
        string generalQuery = ' ' + clientList.clientListQuery__c;
        
        if(!String.isEmpty(clientList.VisibilityBasedOnField__c)) {
            myClientsCondition = CLT_Utils_Query.getAccountBasedFieldCondition(clientList.VisibilityBasedOnField__c, userId);
        }
        else if(clientList.InMyStore__c){  
            myClientsCondition = CLT_Utils_Query.getAccountMyStoreCondition(storeCode);
        }else{
            myClientsCondition = CLT_Utils_Query.getAccountMyClientsCondition(userId);
        }

        if(!String.isEmpty(clientList.clientListQuery__c)) {
            if(!generalQuery.contains('ORDER BY')) {
                if(generalQuery.contains('LIMIT')) {
                    generalQuery = generalQuery.substringBeforeLast('LIMIT') + ' ORDER BY ' + defaultOrderByField + ' LIMIT' + generalQuery.substringAfterLast('LIMIT');
                }
                else {
                    generalQuery += ' ORDER BY ' + defaultOrderByField;
                    if(!isSpecificClientList) {
                        generalQuery += ' LIMIT 200';
                    }
                    else {
                        generalQuery += ' LIMIT 800';
                    }
                }
            }
            else {
                if(generalQuery.contains('LIMIT')) {
                    generalQuery = generalQuery.substringBeforeLast('LIMIT') +  ', ' + defaultOrderByField + ' LIMIT' + generalQuery.substringAfterLast('LIMIT');
                }
                else {
                    generalQuery += ', ' + defaultOrderByField;
                }
            }
        }
        else if (clientList.Type__c == 'Membered') {
            generalQuery = ' AND Id IN (SELECT Client__c FROM ClientListMember__c WHERE ClientList__c = \'' + clientList.Id + '\')';

            if (!isSpecificClientList){
                generalQuery += ' LIMIT 200';
            }
            else if(isSpecificClientList) {
                generalQuery += ' LIMIT 800';
            }
        }

        if(isSpecificClientList && noLimit && !clientList.AlwaysLimitedList__c && generalQuery.contains('LIMIT')) {
            generalQuery = generalQuery.split('LIMIT ')[0];
        }

        system.debug(myClientsCondition + generalQuery);
        return myClientsCondition + generalQuery;
    }
}