unpackaged/main/default/objects/ClientList__c/ClientList__c.object-meta.xml
<CustomObject>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientList__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientList__c/fields/Stores__c.field-meta.xml
<CustomField>
    <fullName>Stores__c</fullName>
    <label>Stores</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE00</fullName>
                <label>RIMOWA Orient Trading LLC</label>
            </value>
            <value>
                <fullName>AE01</fullName>
                <label>Dubai - Dubai Mall</label>
            </value>
            <value>
                <fullName>AE02</fullName>
                <label>Dubai - Mall of the Emirates</label>
            </value>
            <value>
                <fullName>AE03</fullName>
                <label>Dubai - Galeries Lafayette</label>
            </value>
            <value>
                <fullName>AT00</fullName>
                <label>RIMOWA Austria</label>
            </value>
            <value>
                <fullName>AT01</fullName>
                <label>Salzburg - Getreidegasse</label>
            </value>
            <value>
                <fullName>AT02</fullName>
                <label>Vienna - Seitzergasse</label>
            </value>
            <value>
                <fullName>AU00</fullName>
                <label>RIMOWA Australia</label>
            </value>
            <value>
                <fullName>AU01</fullName>
                <label>Melbourne - Chadstone</label>
            </value>
            <value>
                <fullName>AU02</fullName>
                <label>Sydney - Westfield</label>
            </value>
            <value>
                <fullName>AU03</fullName>
                <label>Sydney - David Jones</label>
            </value>
            <value>
                <fullName>AUCS</fullName>
                <label>Australia - Corporate Sales</label>
            </value>
            <value>
                <fullName>BR00</fullName>
            </value>
            <value>
                <fullName>BR01</fullName>
                <label>São Paulo - Fasano Jardins</label>
            </value>
            <value>
                <fullName>BR02</fullName>
                <label>Rio de Janeiro - Shopping Leblon</label>
            </value>
            <value>
                <fullName>BR03</fullName>
                <label>São Paulo - Iguatemi São Paulo</label>
            </value>
            <value>
                <fullName>BR04</fullName>
                <label>Brasília - Iguatemi Brasilia</label>
            </value>
            <value>
                <fullName>BR05</fullName>
                <label>Rio de Janeiro - Barra da Tujica</label>
            </value>
            <value>
                <fullName>BR06</fullName>
                <label>Belo Horizonte - BH Shopping</label>
            </value>
            <value>
                <fullName>BR07</fullName>
                <label>Curitiba - Patio Batel</label>
            </value>
            <value>
                <fullName>BR08</fullName>
                <label>São Paulo - JK Iguatemi</label>
            </value>
            <value>
                <fullName>BR09</fullName>
                <label>São Roque - Catarina Fashion Outlet</label>
            </value>
            <value>
                <fullName>BR10</fullName>
                <label>RIMOWA CARE</label>
            </value>
            <value>
                <fullName>CA00</fullName>
                <label>Toronto - Bloor Street</label>
            </value>
            <value>
                <fullName>CA02</fullName>
                <label>Vancouver- Alberni Street</label>
            </value>
            <value>
                <fullName>CA90</fullName>
                <label>RIMOWA Cambridge HQ</label>
            </value>
            <value>
                <fullName>CN00</fullName>
                <label>RIMOWA China</label>
            </value>
            <value>
                <fullName>CN01</fullName>
                <label>Beijing - SKP Beijing</label>
            </value>
            <value>
                <fullName>CN02</fullName>
                <label>Shanghai Service Centre</label>
            </value>
            <value>
                <fullName>CN03</fullName>
                <label>Shenyang Service Centre</label>
            </value>
            <value>
                <fullName>FR01</fullName>
                <label>Paris - Faubourg St Honoré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>TF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Asia Pacific</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>South America</label>
            </value>
            <value>
                <fullName>AMERIC</fullName>
                <label>America</label>
            </value>
            <value>
                <fullName>EUROPE</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>MEAST</fullName>
                <label>Middle East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/StoreLabel__c.field-meta.xml
<CustomField>
    <fullName>StoreLabel__c</fullName>
    <label>Store Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Asia Pacific</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Japan</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>North America</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>South America</label>
    </customValue>
    <customValue>
        <fullName>AMERIC</fullName>
        <label>America</label>
    </customValue>
    <customValue>
        <fullName>EUROPE</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>MEAST</fullName>
        <label>Middle East</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLT_ClientListPerimeterCtrl_Test.cls
/**
 * @author Sarah AYOUN (Balink)
 * @date July,25 2024
 * @Type Apex Test Class
 *****************************************************************************************************************************************************************
 * @description This Test class contains the methods to test those method from CLT_ClientListPerimeterCtrl :
 * testSetup : Creation of test store
 * TEST METHOD				        		|	DESCRIPTION
 * getInitializationPerimeterTest           |	Test the get of initializaion perimeter
 * getPicklistValuesFromFieldNameTest       |	Test the get of picklist values 
 * getCountryValuesFromSelectedRegionsTest  |	Test the get of countries for a region
 * getStoreValuesFromSelectedCountriesTest  |	Test the get of stores for a country
 * updateClientListPerimeterTest			|	Test the update of perimeter values on a client list
 * 
 * ****************************************************************************************************************************************************************
 * @Version : 
 * Version	|Date of modication	|Modified By	|Related Jira Ticket	|Description of changes			
 * 1.0		|2024/07/25			|.Sarah A.		|.RCLIENT-1085			|.original version
*/
@isTest
private class CLT_ClientListPerimeterCtrl_Test {
    @TestSetup
    static void createTestData() {
        Store__c store = CLT_TestDateFactory.createTestStore('FR01', false);
        store.Region__c = '001';
        store.Country__c = 'FR';
        store.StoreLabel__c = 'TEST_FR01';
        insert store;
    }

    @isTest
    static void getInitializationPerimeterTest() {
        ClientList__c cl = CLT_TestDateFactory.createTestClientList('Test Perimeter List', 'Id != NULL', false);
        cl.Region__c = '001;';
        cl.Country__c = 'FR;';
        cl.Stores__c = 'FR01';
        insert cl;

        Map<String, Object> result = CLT_ClientListPerimeterCtrl.getInitializationPerimeter(cl.Id);
    
        List<Object> regionsFromResult = (List<Object>)JSON.deserializeUntyped(JSON.serialize(result.get('selectedRegions')));
        System.assertEquals(1, regionsFromResult.size(), 'CLT_ClientListPerimeterCtrl_Test:getInitializationPerimeterTest: client list is set to one region and not returned from perimeter');
    }

    @isTest
    static void getPicklistValuesFromFieldNameTest() {
        List<Map<String,string>> storeRegionPicklistValuesCalculated = CLT_ClientListPerimeterCtrl.getPicklistValuesFromFieldName('Store__c', 'Region__c');
        List<Schema.PicklistEntry> storeRegionPicklistValues = Schema.getGlobalDescribe().get('Store__c').getDescribe().fields.getMap().get('Region__c').getDescribe().getPicklistValues();
        System.assertEquals(storeRegionPicklistValues.size(), storeRegionPicklistValuesCalculated.size(), 'CLT_ClientListPerimeterCtrl_Test:getPicklistValuesFromFieldNameTest: picklist values size is not the same as calculated one');

    }

    @isTest
    static void getCountryValuesFromSelectedRegionsTest() {
        List<Map<String,string>> countries = CLT_ClientListPerimeterCtrl.getCountryValuesFromSelectedRegions(new List<String> {'001'});
        System.assertEquals(1, countries.size(), 'CLT_ClientListPerimeterCtrl_Test:getCountryValuesFromSelectedRegionsTest: only one country with the sent region');
    }

    @isTest
    static void getStoreValuesFromSelectedCountriesTest() {
        List<Map<String,string>> stores = CLT_ClientListPerimeterCtrl.getStoreValuesFromSelectedCountries(new List<String> {'FR'});
        System.assertEquals(1, stores.size(), 'CLT_ClientListPerimeterCtrl_Test:getStoreValuesFromSelectedCountriesTest: only one store with the sent country');
    }

    @isTest
    static void updateClientListPerimeterTest() {
        ClientList__c cl = CLT_TestDateFactory.createTestClientList('Test Perimeter List', 'Id != NULL', true);
        Test.startTest();
        CLT_ClientListPerimeterCtrl.updateClientListPerimeter(cl.Id, new List<String> {'001'}, new List<String> {'FR'}, new List<String> {'FR01'});
        Test.stopTest();

        ClientList__c clAfterUpdate = [SELECT Region__c FROM ClientList__c WHERE Id = :cl.Id LIMIT 1];
        System.assertEquals(1, (clAfterUpdate.Region__c.split(';')).size(),'CLT_ClientListPerimeterCtrl_Test:updateClientListPerimeterTest: only one region is sent');
    }
}