unpackaged/main/default/objects/Client_Insight__c/Client_Insight__c.object-meta.xml
<CustomObject>
    <label>Client Insight</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Client Insight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Insights</relationshipLabel>
    <relationshipName>Client_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Collaboration__c</fullName>
    <label>Collaboration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/FrequentTraveler__c.field-meta.xml
<CustomField>
    <fullName>FrequentTraveler__c</fullName>
    <label>Frequent Traveler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/HistoricalClient__c.field-meta.xml
<CustomField>
    <fullName>HistoricalClient__c</fullName>
    <label>Historical Client</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/Client_Insight_History__c.object-meta.xml
<CustomObject>
    <label>Client Insight History</label>
    <nameField>
        <displayFormat>CIH-{0000000}</displayFormat>
        <label>Client Insight History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insight Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ClientInsight__c.field-meta.xml
<CustomField>
    <fullName>ClientInsight__c</fullName>
    <label>Client Insight</label>
    <referenceTo>Client_Insight__c</referenceTo>
    <relationshipLabel>Client Insight Histories</relationshipLabel>
    <relationshipName>ClientInsightHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ModifiedBy__c.field-meta.xml
<CustomField>
    <fullName>ModifiedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modified By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Insight_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CLT_Utils_ClientInsightTrigger_Test.cls
@isTest
private class CLT_Utils_ClientInsightTrigger_Test {
    @TestSetup
    static void prepareTestData(){
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, true);
		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);
        Account client = CLT_TestDateFactory.createTestClient('Test client 1', 'Test Last Name1', sa.Id, store.Id, true);
    }

    @isTest
    static void testClientInsightTrigger_Insert() {
        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        Account client = [SELECT Id FROM Account WHERE FirstName = 'Test client 1' AND LastName = 'Test Last Name1' LIMIT 1];

        System.runAs(sa) {
            Client_Insight__c ci = new Client_Insight__c(
                ExternalId__c = client.Id,
                Client__c = client.Id,
                FrequentTraveler__c = 'Yes',
                HistoricalClient__c = 'Yes',
                Collaboration__c = 'Yes'
            );
            Test.startTest();
            insert ci;
            Test.stopTest();
        }

        List<Client_Insight_History__c> ciHistoryList = [SELECT Id
                                                        FROM Client_Insight_History__c 
                                                        WHERE ClientInsight__r.ExternalId__c = :client.Id AND ModifiedBy__c = :sa.Id];

        System.assertEquals(3, ciHistoryList.size(), 'Client Isight histories list is not 3 when inserting with 3 fields filled');
    }

    @isTest
    static void testClientInsightTrigger_Update() {
        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        Account client = [SELECT Id FROM Account WHERE FirstName = 'Test client 1' AND LastName = 'Test Last Name1' LIMIT 1];

        Client_Insight__c ci = new Client_Insight__c(
            ExternalId__c = client.Id,
            Client__c = client.Id,
            FrequentTraveler__c = 'Yes',
            HistoricalClient__c = 'Yes',
            Collaboration__c = 'Yes'
        );
        insert ci;

        System.runAs(sa) {
            ci.FrequentTraveler__c = 'No';
            ci.HistoricalClient__c = 'No';
            Test.startTest();
            update ci;
            Test.stopTest();
        }

        List<Client_Insight_History__c> ciHistoryList = [SELECT Id
                                                        FROM Client_Insight_History__c 
                                                        WHERE ClientInsight__r.ExternalId__c = :client.Id AND ModifiedBy__c = :sa.Id];

        System.assertEquals(2, ciHistoryList.size(), 'Client Isight histories list is not 2 when updating 2 fields values by the SA');
    }
}