unpackaged/main/default/objects/Client_Insight__c/Client_Insight__c.object-meta.xml
<CustomObject>
    <label>Client Insight</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Client Insight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Insights</relationshipLabel>
    <relationshipName>Client_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Collaboration__c</fullName>
    <label>Collaboration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/FrequentTraveler__c.field-meta.xml
<CustomField>
    <fullName>FrequentTraveler__c</fullName>
    <label>Frequent Traveler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/HistoricalClient__c.field-meta.xml
<CustomField>
    <fullName>HistoricalClient__c</fullName>
    <label>Historical Client</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/Hobbies__c.field-meta.xml
<CustomField>
    <fullName>Hobbies__c</fullName>
    <label>Hobbies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Art</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Gastronomy</fullName>
            </value>
            <value>
                <fullName>Web 3</fullName>
            </value>
            <value>
                <fullName>Photography</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/due__Diduenjoy_Answer__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Answer</label>
    <nameField>
        <label>Diduenjoy Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/fields/due__Diduenjoy_Feedback__c.field-meta.xml
<CustomField>
    <fullName>due__Diduenjoy_Feedback__c</fullName>
    <label>Diduenjoy Feedback</label>
    <referenceTo>due__Diduenjoy_Feedback__c</referenceTo>
    <relationshipLabel>Diduenjoy Answers</relationshipLabel>
    <relationshipName>Diduenjoy_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/News__c/News__c.object-meta.xml
<CustomObject>
    <label>News</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>News Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NewsContent__c/NewsContent__c.object-meta.xml
<CustomObject>
    <label>News Content</label>
    <nameField>
        <displayFormat>NC-{0000}</displayFormat>
        <label>News Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NewsContent__c/fields/News__c.field-meta.xml
<CustomField>
    <fullName>News__c</fullName>
    <label>News</label>
    <referenceTo>News__c</referenceTo>
    <relationshipLabel>News Contents</relationshipLabel>
    <relationshipName>NewsContents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Note__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Compta</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUT</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>FSS</fullName>
                <label>Free Standing Store</label>
            </value>
            <value>
                <fullName>CCC</fullName>
                <label>Customer Care Center</label>
            </value>
            <value>
                <fullName>SIS</fullName>
                <label>Shop-in-shop</label>
            </value>
            <value>
                <fullName>SUB</fullName>
                <label>Subsidiary Head Quarter</label>
            </value>
            <value>
                <fullName>WHS</fullName>
                <label>Wharehouse</label>
            </value>
            <value>
                <fullName>HDQ</fullName>
                <label>Heardquarter</label>
            </value>
            <value>
                <fullName>POP</fullName>
                <label>Pop Up Store</label>
            </value>
            <value>
                <fullName>ECO</fullName>
                <label>eCommerce store</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/ExclTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>ExclTaxAmount__c</fullName>
    <label>Excl Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Sales_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Sales_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>GiftCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLT_Homepage_Test.cls
/**
 * @author (Balink)
 * @Type Apex Test Class
 *****************************************************************************************************************************************************************
 * @description This Test class contains the methods to test those method from CLT_Homepage :
 * testSetup : Creation of test user and store
 * TEST METHOD				        		    |	DESCRIPTION
 * 
 * ****************************************************************************************************************************************************************
 * @Version : 
 * Version	|Date of modication	|Modified By	    |Related Jira Ticket	|Description of changes			
*/
@isTest
private class CLT_Homepage_Test {
    @TestSetup
    static void homepageDataFactory(){
        User sa = CLT_TestDateFactory.createTestUser(System.Label.profileName_StoreUser, false);
        sa.LanguageLocaleKey = 'fr';
        insert sa;

		Store__c store = CLT_TestDateFactory.createTestStore('TST123', true);

		List<Account> clients = new List<Account>();

        Account client1 = CLT_TestDateFactory.createTestClient('Test client 1', 'Test Last Name1', sa.Id, store.Id, false);
        client1.Last_Transaction_SA__pc = sa.Id;
		client1.LifeTimePurchaseAmount__pc = 2500;
		client1.LightCurrentCluster__pc = 'VIC';
        client1.ClientType__pc = 'Client';
		clients.add(client1);

        Account client2 = CLT_TestDateFactory.createTestClient('Test client 2', 'Test Last Name2', sa.Id, store.Id, false);
        client2.Last_Transaction_SA__pc = sa.Id;
		client2.LifeTimePurchaseAmount__pc = 1200;
		client2.LightCurrentCluster__pc = 'Inactive Client';
        client1.ClientType__pc = 'Client';
		clients.add(client2);

		Account client3 = CLT_TestDateFactory.createTestClient('Test client 3', 'Test Last Name3', sa.Id, store.Id, false);
        client3.Last_Transaction_SA__pc = sa.Id;
		client3.LifeTimePurchaseAmount__pc = 0;
		client2.LightCurrentCluster__pc = 'Prospect';
		client3.ClientType__pc = 'PROSPECT_T';
		clients.add(client3);

		insert clients;
    }

    @isTest 
    static void test_Homepage_Delete() {
        CLT_Homepage homepage = new  CLT_Homepage();

        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        System.runAs(sa) {
            Test.startTest();
            
            Object homepageDeleteResponse = homepage.retrieveDelete(new Map<String, String>());
            System.assertEquals(null, homepageDeleteResponse, 'Delete method defined and not tested');

            Test.stopTest();
        }
    }

    @isTest 
    static void test_Homepage_Post() {
        CLT_Homepage homepage = new  CLT_Homepage();

        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        System.runAs(sa) {
            Test.startTest();
            
            Object homepagePostResponse = homepage.retrievePost(new Map<String, String>(), new Map<String,Object>());
            System.assertEquals(null, homepagePostResponse, 'Post method defined and not tested');

            Test.stopTest();
        }
    }

    @isTest 
    static void test_Homepage_Get() {
        CLT_Homepage homepage = new  CLT_Homepage();

        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        System.runAs(sa) {
            Test.startTest();
            
            Object homepageGetResponse = homepage.retrieveGet(new Map<String, String>());
            Object homepagePortfolioResponse = ((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageGetResponse))).get('portfolioInfo');
            Integer getProspectCount = (Integer)((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepagePortfolioResponse))).get('prospect');
            List<Account> prospectList = [SELECT Id FROM Account WHERE ClientAdvisor__pc = :sa.Id AND LightCurrentCluster__pc = 'Prospect'];
            System.assertEquals(prospectList.size(), getProspectCount, 'prospect count is not 1');

            Test.stopTest();
        }
    }

    @isTest 
    static void test_Homepage_Get_NewsContentTranslation() {
        News__c news = CLT_TestDateFactory.createTestNews('https://www.rimowa.com/ww/en/stories/rimowa-x-gewa-introduction.html', 'RIMOWA × GEWA:THE ULTIMATE CASE FOR VIOLINS RIMOWA', true);
        NewsContent__c newsContent = CLT_TestDateFactory.createTestNewsContent(news.Id, 'fr', 'https://www.rimowa.com/fr/fr/stories/rimowa-x-gewa-introduction.html', 'RIMOWA × GEWA : LÉTUI POUR VIOLON IDÉAL', true);
        
        CLT_Homepage homepage = new  CLT_Homepage();

        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];

        System.runAs(sa) {
            Test.startTest();
            
            Object homepageGetResponse = homepage.retrieveGet(new Map<String, String>());
            Object homepageNewsInfoResponse = ((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageGetResponse))).get('newsInfo');
            List<Object> homepageNewsResponse = (List<Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageNewsInfoResponse))).get('news')));
            Map<String, Object> wrappedNews = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageNewsResponse[0]));
            System.assertEquals('https://www.rimowa.com/fr/fr/stories/rimowa-x-gewa-introduction.html', (String)wrappedNews.get('link'), 'New Content link is not french link');

            Test.stopTest();
        }
    }

    @isTest
    static void test_Homepage_Get_ComboChallenge() {
        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
		Store__c store = [SELECT Id FROM Store__c WHERE SourceStoreId__c = 'TST123' LIMIT 1];
        Account client = [SELECT Id FROM Account WHERE ClientAdvisor__pc = :sa.Id LIMIT 1];

        Transaction__c transction = CLT_TestDateFactory.createTestTransaction(client.Id, Date.today().addDays(-7), false);
        transction.Store__c = store.Id;
        insert transction;

        Product2 product = CLT_TestDateFactory.createTestStandardProduct('TEST123', true);

        TransactionItem__c transactionItem = CLT_TestDateFactory.createTestTransactionItem(transction.Id, client.Id, product.Id, false);
        transactionItem.Sales_Advisor__c = sa.Id;
        insert transactionItem;

        client.Last_Transaction_SA__pc = sa.Id;
        client.LastPurchaseDate__pc = Date.today().addDays(-7);
        update client;

        List<Task> tasks = new List<Task>();

        Task outreach = CLT_TestDateFactory.createTask(sa.Id, false);
        outreach.WhatId = client.Id;
        outreach.ActivityDate = Date.today().addDays(-6);
        outreach.Outreach_Type__c = 'SMS';
        tasks.add(outreach);

        Task task = CLT_TestDateFactory.createTask(sa.Id, false);
        task.WhatId = client.Id;
        task.ActivityDate = Date.today().addDays(-5);
        tasks.add(task);

        insert tasks;        

        CLT_Homepage homepage = new  CLT_Homepage();

        System.runAs(sa) {
            Note__c note = CLT_TestDateFactory.createTestNote('Wanted the lightest luggage possible', client.Id, true);
            Test.setCreatedDate(note.Id, Date.today().addDays(-3));
            Test.startTest();
            
            Object homepageGetResponse = homepage.retrieveGet(new Map<String, String>());
            List<Object> homepageComboResponse = (List<Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageGetResponse))).get('comboChallenge')));
            System.assertEquals(1, homepageComboResponse.size(), 'Combo Challenge list size is not 1');

            Test.stopTest();
        }
    }

    @isTest
    static void test_Homepage_Get_ComboChallengeV2() {
        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
		Store__c store = [SELECT Id FROM Store__c WHERE SourceStoreId__c = 'TST123' LIMIT 1];
        Account client = [SELECT Id FROM Account WHERE ClientAdvisor__pc = :sa.Id LIMIT 1];

        Transaction__c transction = CLT_TestDateFactory.createTestTransaction(client.Id, Date.today().addDays(-7), false);
        transction.Store__c = store.Id;
        insert transction;

        Product2 product = CLT_TestDateFactory.createTestStandardProduct('TEST123', true);

        TransactionItem__c transactionItem = CLT_TestDateFactory.createTestTransactionItem(transction.Id, client.Id, product.Id, false);
        transactionItem.Sales_Advisor__c = sa.Id;
        transactionItem.Type__c = 'Sale';
        transactionItem.ExclTaxAmount__c = 100.00;
        insert transactionItem;

        client.Last_Transaction_SA__pc = sa.Id;
        client.LastPurchaseDate__pc = Date.today().addDays(-7);
        update client;

        List<Task> tasks = new List<Task>();

        Task outreach = CLT_TestDateFactory.createTask(sa.Id, false);
        outreach.WhatId = client.Id;
        outreach.ActivityDate = Date.today().addDays(-6);
        outreach.Outreach_Type__c = 'SMS';
        tasks.add(outreach);

        Task task = CLT_TestDateFactory.createTask(sa.Id, false);
        task.WhatId = client.Id;
        task.ActivityDate = Date.today().addDays(-5);
        tasks.add(task);

        insert tasks;        

        CLT_Homepage homepage = new  CLT_Homepage();

        System.runAs(sa) {
            Note__c note = CLT_TestDateFactory.createTestNote('Wanted the lightest luggage possible', client.Id, true);
            Client_Insight__c ci = new Client_Insight__c(
                ExternalId__c = client.Id,
                Client__c = client.Id,
                FrequentTraveler__c = 'Yes',
                HistoricalClient__c = 'Yes',
                Collaboration__c = 'Yes',
                Hobbies__c = 'Art'
            );
            insert ci;
            Test.setCreatedDate(note.Id, Date.today().addDays(-3));
            Test.startTest();
            
            Object homepageGetResponse = homepage.retrieveGet(new Map<String, String>{'versionNum' => '2.13'});
            List<Object> homepageComboResponse = (List<Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageGetResponse))).get('comboChallenge')));
            Boolean noteV2 = (Boolean)(((Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(homepageComboResponse[0]))).get('noteId'));
            System.assertEquals(true, noteV2, 'note is not true even when 4 insights + note');

            Test.stopTest();
        }
    }

    @isTest 
    static void test_Homepage_Get_Feedbacks() {
        User sa = [SELECT Id FROM User WHERE Username LIKE '%clttestuser@rimowa.com' AND Profile.Name = :System.Label.profileName_StoreUser LIMIT 1];
        Account client = [SELECT Id FROM Account WHERE Last_Transaction_SA__pc = :sa.Id LIMIT 1];
        due__Diduenjoy_Feedback__c feedback = CLT_TestDateFactory.createTestFeedback(client.Id, true);
        due__Diduenjoy_Answer__c answer = CLT_TestDateFactory.createTestFeedbackAnswer(feedback.Id, 10, true);
        
        CLT_Homepage homepage = new  CLT_Homepage();

        System.runAs(sa) {
            Test.startTest();
            
            Object homepageGetResponse = homepage.retrieveGet(new Map<String, String>());
            List<Object> homepageFeedbackResponse = (List<Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(homepageGetResponse))).get('feedbacks')));
            System.assertEquals(1, homepageFeedbackResponse.size(), 'Feedback list size is not 1');

            Test.stopTest();
        }
    }
}