unpackaged/main/default/objects/Client_Insight__c/Client_Insight__c.object-meta.xml
<CustomObject>
    <label>Client Insight</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Client Insight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Insights</relationshipLabel>
    <relationshipName>Client_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/LastReviewDate__c.field-meta.xml
<CustomField>
    <fullName>LastReviewDate__c</fullName>
    <label>Last Review Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight__c/fields/ReviewedInformation__c.field-meta.xml
<CustomField>
    <fullName>ReviewedInformation__c</fullName>
    <label>Reviewed Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/Client_Insight_History__c.object-meta.xml
<CustomObject>
    <label>Client Insight History</label>
    <nameField>
        <displayFormat>CIH-{0000000}</displayFormat>
        <label>Client Insight History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insight Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ClientInsight__c.field-meta.xml
<CustomField>
    <fullName>ClientInsight__c</fullName>
    <label>Client Insight</label>
    <referenceTo>Client_Insight__c</referenceTo>
    <relationshipLabel>Client Insight Histories</relationshipLabel>
    <relationshipName>ClientInsightHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ModifiedField__c.field-meta.xml
<CustomField>
    <fullName>ModifiedField__c</fullName>
    <label>Modified Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CLT_NotificationManagement__mdt/CLT_NotificationManagement__mdt.object-meta.xml
<CustomObject>
    <label>CLT NotificationManagement</label>
    <pluralLabel>CLT NotificationManagements</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CLT_NotificationManagement__mdt/fields/RedirectionScreen__c.field-meta.xml
<CustomField>
    <fullName>RedirectionScreen__c</fullName>
    <label>Redirection Screen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Note__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Compta</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Note_History__c/Note_History__c.object-meta.xml
<CustomObject>
    <label>Note History</label>
    <nameField>
        <displayFormat>NH-{0000000000}</displayFormat>
        <label>Note History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note_History__c/fields/ModifiedField__c.field-meta.xml
<CustomField>
    <fullName>ModifiedField__c</fullName>
    <label>Modified Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/NotificationManagementId__c.field-meta.xml
<CustomField>
    <fullName>NotificationManagementId__c</fullName>
    <label>Notification Management Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/Seen__c.field-meta.xml
<CustomField>
    <fullName>Seen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seen?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/SendingTime__c.field-meta.xml
<CustomField>
    <fullName>SendingTime__c</fullName>
    <label>Sending Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/TargetScreenId__c.field-meta.xml
<CustomField>
    <fullName>TargetScreenId__c</fullName>
    <label>Target Screen Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RClientConfigurations__c/RClientConfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>R-Client Configurations</label>
</CustomObject>

unpackaged/main/default/objects/RClientConfigurations__c/fields/ComboChallengeNotificationAfter__c.field-meta.xml
<CustomField>
    <fullName>ComboChallengeNotificationAfter__c</fullName>
    <label>Combo Challenge Notification After</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/RClientConfigurations__c/fields/ComboChallengeNotifSendHour__c.field-meta.xml
<CustomField>
    <fullName>ComboChallengeNotifSendHour__c</fullName>
    <label>Combo Challenge Notif Send Hour</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/RepairOrder__c.object-meta.xml
<CustomObject>
    <description>RMS Repair Order</description>
    <label>Repair Order</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RepairOrder__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RepairOrder__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product List</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/ExclTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>ExclTaxAmount__c</fullName>
    <label>Excl Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/LocalOrTourist__c.field-meta.xml
<CustomField>
    <fullName>LocalOrTourist__c</fullName>
    <formula>IF(ISBLANK(TEXT(Client__r.Country__pc)),  
				&quot;Unlocalized&quot;, 
			 IF(TEXT(Client__r.Country__pc) = TEXT(Store__r.Country__c),
							&quot;Local&quot;, 
							&quot;Tourist&quot;
		) 	
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local or Tourist ?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>GiftCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLT_BatchComboChallengeNotif.cls
global class CLT_BatchComboChallengeNotif implements Database.Batchable<sObject>, Schedulable {
    String query;
    Date dateOfPurchase;
    Integer nbOfDaysAfterPurchase;
    Integer sendingTimeHour;

    public CLT_BatchComboChallengeNotif() {
        RClientConfigurations__c rclientConfigurations = RClientConfigurations__c.getOrgDefaults();
        nbOfDaysAfterPurchase = Integer.valueOf(rclientConfigurations.ComboChallengeNotificationAfter__c);
        sendingTimeHour = Integer.valueOf(rclientConfigurations.ComboChallengeNotifSendHour__c);
        dateOfPurchase = Date.today().addDays(-nbOfDaysAfterPurchase);
        query = 'SELECT Id,Last_Transaction_SA__pc,Last_Transaction_SA__pr.StoreCode__c,LastPurchaseDate__pc,FirstPurchaseDate__pc, ' + 
                    '(SELECT TransactionDate__c, LocalOrTourist__c ' +
                    'FROM Transactions__r ' +
                    'WHERE TransactionDate__c = :dateOfPurchase ORDER BY CreatedDate DESC LIMIT 1),' +
                    '(SELECT ReviewedInformation__c FROM Client_Insights__r WHERE LastReviewDate__c >= :dateOfPurchase),' +
                    '(SELECT Id,Outreach_Type__c,OwnerId FROM Tasks ' +
                    'WHERE CreatedDate >= LAST_N_DAYS:' + nbOfDaysAfterPurchase + ' AND (Outreach_Type__c = NULL OR (Outreach_Type__c != NULL AND Outreach_Type__c NOT IN (\'Gift\',\'Event\',\'Wishlist\'))))' +
                'FROM Account ' +
                'WHERE LastPurchaseDate__pc = :dateOfPurchase AND Id NOT IN ' +
                    '(SELECT Client__c FROM ClientSource__c WHERE (SourceCode__c LIKE \'____\'  OR SourceCode__c LIKE \'%000000\'))';
                System.debug(query);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        List<Notification__c> notificationsToInsert = new List<Notification__c>();

        CLT_NotificationManagement__mdt comboNotificationSetting = [SELECT Id,Type__c,Subtype__c,Name__c,Message__c,RedirectionScreen__c 
                                                                    FROM CLT_NotificationManagement__mdt 
                                                                    WHERE Type__c = 'general' AND  Subtype__c = 'combo'
                                                                    LIMIT 1];

        List<Account> clientsToNotify = getClientsToNotifyList(scope);
        Map<String, List<String>> usersToNotify = new Map<String, List<String>>();
        for(Account client : clientsToNotify) {
            String storeCode = !String.isEmpty(client.Last_Transaction_SA__pr.StoreCode__c) ? client.Last_Transaction_SA__pr.StoreCode__c : '#NOSTORE';
            if(!usersToNotify.containsKey(storeCode)) {
                usersToNotify.put(storeCode, new List<String>());
            }
            usersToNotify.get(storeCode).add(client.Last_Transaction_SA__pc);
        }

        Map<String,Integer> userSendingTimeMap = CLT_PushNotification_Utils.getUsersSendingTimeHour(usersToNotify, sendingTimeHour);

        for(Account client : clientsToNotify) {
            notificationsToInsert.add(new Notification__c(
                NotificationManagementId__c = comboNotificationSetting.Id,
                Type__c = comboNotificationSetting.Type__c,
                Subtype__c = comboNotificationSetting.Subtype__c,
                Seen__c = false,
                Read__c = false,
                SendingTime__c = DateTime.newInstanceGMT(Date.today().addDays(1), Time.newInstance(userSendingTimeMap.containsKey(client.Last_Transaction_SA__pc) ? userSendingTimeMap.get(client.Last_Transaction_SA__pc) : sendingTimeHour, 0, 0, 0)),
                Title__c = comboNotificationSetting.Name__c,
                Body__c = comboNotificationSetting.Message__c,
                TargetScreenId__c = comboNotificationSetting.RedirectionScreen__c,
                Client__c = client.Id,
                User__c = client.Last_Transaction_SA__pc
            ));
        }

        insert notificationsToInsert;
    }

    global void finish(Database.BatchableContext BC) {
    }

    global void execute(SchedulableContext sc) {
         

    }

    public List<Account> getClientsToNotifyList(List<Account> scope) {
        Map<String,Account> challengeClientsMap = getChallengeClientsMap(scope);
        List<Account> clientToNotify = new List<Account>();

        if(challengeClientsMap.keySet().size() > 0) {
            Map<String, List<String>> clientNotesMap = getClientNotesMap(challengeClientsMap.keySet());
        
            for(Account client : challengeClientsMap.values()) {
                Boolean isFirstPurchase = client.FirstPurchaseDate__pc == client.LastPurchaseDate__pc ? true : false;
                Integer doneCombo = 0;
                Boolean isTourist = getIsTouristTransaction(client);
                Boolean isReviewedInsights = getIsReviewedInsights(client);

                if(isReviewedInsights) {
                    doneCombo ++;
                }

                if(!isReviewedInsights && clientNotesMap.containsKey(client.Id) && ((isFirstPurchase && clientNotesMap.get(client.Id).size() >= 5) || (!isFirstPurchase && clientNotesMap.get(client.Id).size() >= 1))) {
                    doneCombo ++;
                }

                Boolean taskDone = false;
                Boolean outrechDone = false;
                for(Task currentTask : client.Tasks) {
                    if(currentTask.OwnerId == client.Last_Transaction_SA__pc) {
                        if(!isTourist && String.isEmpty(currentTask.Outreach_Type__c)) {
                            taskDone = true;
                        }
                        else if(!String.isEmpty(currentTask.Outreach_Type__c)) {
                            outrechDone = true;
                        }
                    }
                }
                if(taskDone) {
                    doneCombo ++;
                }
                if(outrechDone) {
                    doneCombo ++;
                }

                if((!isTourist && doneCombo < 3) || doneCombo < 2) {
                    clientToNotify.add(client);
                }
            }
        }
        return clientToNotify;
    }

    public Map<String,Account> getChallengeClientsMap(List<Account> scope) {
        Map<Id,Account> clientsMap = new Map<Id,Account>(scope);
        Map<String,Account> challengeClientsMap = new Map<String,Account>();
        for(Transaction__c t : [SELECT Client__c,
                                    (SELECT Id 
                                    FROM Transaction_Items__r 
                                    WHERE (NOT Product__r.StockKeepingUnit LIKE '2%') AND Product__r.macrofunction__c != 'REPARATION' 
                                        AND Type__c = 'Sale' AND ExclTaxAmount__c > 0)
                                FROM Transaction__c 
                                WHERE TransactionDate__c = :dateOfPurchase AND Client__c IN :clientsMap.keySet()]) {
            if(t.Transaction_Items__r.size() > 0) {
                Account client = clientsMap.get(t.Client__c);
                challengeClientsMap.put(client.Id, client);
            }
        }
        return challengeClientsMap;
    }

    public Map<String, List<String>> getClientNotesMap(Set<String> challengeClientIds) {
        Map<String, List<String>> clientNotesMap = new Map<String, List<String>>();
        for(Client_Insight_History__c cih : [SELECT ModifiedField__c,ClientInsight__r.Client__c,ClientInsight__r.Client__r.Last_Transaction_SA__pc,ModifiedAt__c,ModifiedBy__c
                                            FROM Client_Insight_History__c
                                            WHERE ClientInsight__r.Client__c IN :challengeClientIds AND ModifiedAt__c >= :dateOfPurchase]) {
            if(cih.ClientInsight__r.Client__r.Last_Transaction_SA__pc == cih.ModifiedBy__c) {
                if(!clientNotesMap.containsKey(cih.ClientInsight__r.Client__c)) {
                    clientNotesMap.put(cih.ClientInsight__r.Client__c, new List<String>());
                }
                if(!clientNotesMap.get(cih.ClientInsight__r.Client__c).contains(cih.ModifiedField__c)) {
                    clientNotesMap.get(cih.ClientInsight__r.Client__c).add(cih.ModifiedField__c);
                }
            }
            
        }

        for(Note_History__c noteH : [SELECT Note__r.Client__c,Note__r.Client__r.Last_Transaction_SA__pc,ModifiedAt__c,ModifiedBy__c
                                    FROM Note_History__c
                                    WHERE Note__r.Client__c IN :challengeClientIds AND ModifiedAt__c >= :dateOfPurchase]) {
            if(noteH.Note__r.Client__r.Last_Transaction_SA__pc == noteH.ModifiedBy__c) {
                if(!clientNotesMap.containsKey(noteH.Note__r.Client__c)) {
                    clientNotesMap.put(noteH.Note__r.Client__c, new List<String>());
                }
                if(!clientNotesMap.get(noteH.Note__r.Client__c).contains('note-comment')) {
                    clientNotesMap.get(noteH.Note__r.Client__c).add('note-comment');
                }
            }
        }

        return clientNotesMap;
    }

    public Boolean getIsTouristTransaction(Account client) {
        Boolean isTourist = false;

        for(Transaction__c currentTransaction : client.Transactions__r) {
            isTourist = currentTransaction.LocalOrTourist__c == 'Tourist' ? true : false; 
        }

        return isTourist;
    }

    public Boolean getIsReviewedInsights(Account client) {
        Boolean isReviewedInsights = false;

        for(Client_Insight__c ci : client.Client_Insights__r) {
            Map<String, Object> reviewedInformationMap = !String.isEmpty(ci.ReviewedInformation__c) ? (Map<String, Object>)JSON.deserializeUntyped(ci.ReviewedInformation__c) : new Map<String, Object>();
            if(reviewedInformationMap.containsKey(client.Last_Transaction_SA__pc)) {
                List<String> userReviewedDateList = ((String)reviewedInformationMap.get(client.Last_Transaction_SA__pc)).split('-');
                Date userReviewedDate = userReviewedDateList.size() == 3 ? Date.newInstance(Integer.valueOf(userReviewedDateList[2]), Integer.valueOf(userReviewedDateList[1]), Integer.valueOf(userReviewedDateList[0])) : Date.newInstance(2000, 1, 1);
                if(userReviewedDate >= dateOfPurchase) {
                    isReviewedInsights = true;
                }
            }
        }

        return isReviewedInsights;
    }
}