unpackaged/main/default/objects/Client_Insight__c/Client_Insight__c.object-meta.xml
<CustomObject>
    <label>Client Insight</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Client Insight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight_History__c/Client_Insight_History__c.object-meta.xml
<CustomObject>
    <label>Client Insight History</label>
    <nameField>
        <displayFormat>CIH-{0000000}</displayFormat>
        <label>Client Insight History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Insight Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ClientInsight__c.field-meta.xml
<CustomField>
    <fullName>ClientInsight__c</fullName>
    <label>Client Insight</label>
    <referenceTo>Client_Insight__c</referenceTo>
    <relationshipLabel>Client Insight Histories</relationshipLabel>
    <relationshipName>ClientInsightHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ModifiedAt__c.field-meta.xml
<CustomField>
    <fullName>ModifiedAt__c</fullName>
    <label>Modified At</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ModifiedBy__c.field-meta.xml
<CustomField>
    <fullName>ModifiedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modified By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Insight_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Insight_History__c/fields/ModifiedField__c.field-meta.xml
<CustomField>
    <fullName>ModifiedField__c</fullName>
    <label>Modified Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLT_Utils_ClientInsightTrigger.cls
public with sharing class CLT_Utils_ClientInsightTrigger {

    public static void createClientInsightHistories(List<Client_Insight__c> newClientInsights, Map<Id, Client_Insight__c> oldClientInsightsMap) {
        List<Client_Insight_History__c> ciHistoriesToInsert = new List<Client_Insight_History__c>();
        for(Client_Insight__c clientInsight : newClientInsights) {
            for(String fieldName : System.Label.ClientInsightFieldsToTrack.split(';')) {
                if((!oldClientInsightsMap.containsKey(clientInsight.Id) && (clientInsight.get(fieldName) != null && (!(clientInsight.get(fieldName) instanceof Boolean) || ((clientInsight.get(fieldName) instanceof Boolean) && (Boolean)clientInsight.get(fieldName) == true)))) || 
                    (oldClientInsightsMap.containsKey(clientInsight.Id) && clientInsight.get(fieldName) != oldClientInsightsMap.get(clientInsight.Id).get(fieldName))) {
                    ciHistoriesToInsert.add(new Client_Insight_History__c (
                        ClientInsight__c = clientInsight.Id,
                        ModifiedField__c = fieldName,
                        NewValue__c = String.valueOf(clientInsight.get(fieldName)),
                        PreviousValue__c = oldClientInsightsMap.containsKey(clientInsight.Id) ? String.valueOf(oldClientInsightsMap.get(clientInsight.Id).get(fieldName)) : '',
                        ModifiedBy__c = clientInsight.LastModifiedById,
                        ModifiedAt__c = clientInsight.LastModifiedDate
                    ));
                }
            }
        }
        insert ciHistoriesToInsert;
    }
}