unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientAddress__c/fields/AddressTypology__c.field-meta.xml
<CustomField>
    <fullName>AddressTypology__c</fullName>
    <label>Address Typology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>BILLING</fullName>
            </value>
            <value>
                <fullName>DELIVERY</fullName>
            </value>
            <value>
                <fullName>TEMPORARY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Addresses</relationshipLabel>
    <relationshipName>ClientAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AFG</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AGO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AIA</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>ALA</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>ALB</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AND</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>ANT</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>ARE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>ARG</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>ARM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>ASM</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>ATA</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>ATF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>ATG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AUS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AUT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZE</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BDI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BEL</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BEN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BFA</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BGD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BGR</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BHR</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BHS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BIH</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BLM</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BLR</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BLZ</fullName>
                <label>Belize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/SourceLastUpdateDate__c.field-meta.xml
<CustomField>
    <fullName>SourceLastUpdateDate__c</fullName>
    <label>Source Last Update Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ClientAddressFields__c/ClientAddressFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Client Address Fields</label>
    
</CustomObject>

unpackaged/main/default/objects/ClientAddressFields__c/fields/Address3__c.field-meta.xml
<CustomField>
    <fullName>Address3__c</fullName>
    <label>Address3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientAddressFields__c/fields/AddressTypology__c.field-meta.xml
<CustomField>
    <fullName>AddressTypology__c</fullName>
    <label>AddressTypology</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientAddressFields__c/fields/IsValid__c.field-meta.xml
<CustomField>
    <fullName>IsValid__c</fullName>
    <label>IsValid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Cegid</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Ecommerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCreationDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreationDate__c</fullName>
    <label>Source Creation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ClientSourceFields__c/ClientSourceFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Client Source Fields</label>
</CustomObject>

unpackaged/main/default/objects/ClientSourceFields__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <label>SourceCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSourceFields__c/fields/SourceCreationDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreationDate__c</fullName>
    <label>SourceCreationDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSourceFields__c/fields/SourceLastUpdateDate__c.field-meta.xml
<CustomField>
    <fullName>SourceLastUpdateDate__c</fullName>
    <label>SourceLastUpdateDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <label>Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <label>Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address3__c.field-meta.xml
<CustomField>
    <fullName>Address3__c</fullName>
    <label>Address 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>TF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/WS_ClientKPIUTL.cls
/**
 * @description       : 
 * @author            : Ulrich M. NDONG NGOMO
 * @group             : 
 * @last modified on  : 05-09-2023
 * @last modified by  : Ulrich M. NDONG NGOMO
**/
public with sharing class WS_ClientKPIUTL {
    
    public static List<Database.SaveResult> upsertClientSources(List<ClientSource__c> sources, String clientID) {
        
        System.debug('*** sources ***: '+sources);
        System.debug('*** clientID ***: '+clientID);
        Map<String, List<ClientSource__c>> clientSourceBySourceMap = new Map<String, List<ClientSource__c>>();
        List<ClientSource__c> srcListToBeUpdated = new List<ClientSource__c>();
        List<ClientSource__c> srcListToBeCreated = new List<ClientSource__c>();
        Database.SaveResult[] srList;
        // Get the SObject describe result
		Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('ClientSourceFields__c').getDescribe();
        Map<String, SObjectField> fieldsMap = describeResult.fields.getMap();
        
        List<ClientSource__c> retrievedClientSources = [SELECT Id, Client__c, Source__c, SourceCode__c, SourceCreationDate__c, SourceLastUpdateDate__c
                                                        FROM ClientSource__c WHERE Client__c =: clientID];
        System.debug('*** retrievedClientSources ***: '+retrievedClientSources);
        for(ClientSource__c src : retrievedClientSources) {
            if(clientSourceBySourceMap.containsKey(src.Source__c)) {
                clientSourceBySourceMap.get(src.Source__c).add(src);
            }else {
                List<ClientSource__c> clientSourceList = new List<ClientSource__c>();
                clientSourceList.add(src);
                clientSourceBySourceMap.put(src.Source__c, clientSourceList);
            }
        }
        System.debug('*** clientSourceBySourceMap ***: '+clientSourceBySourceMap);
        for(ClientSource__c src : sources) {
            System.debug('*** src ***: '+src);
            if(clientSourceBySourceMap.containsKey(src.Source__c)) {
                for(ClientSource__c clientSource : clientSourceBySourceMap.get(src.Source__c)) {
                    Boolean isExisted = (src.Source__c == clientSource.Source__c) 
                        && (src.SourceCode__c == clientSource.SourceCode__c)?true : false;
                    if(isExisted) {
                        clientSource.SourceCreationDate__c = src.SourceCreationDate__c;
                        clientSource.SourceLastUpdateDate__c = src.SourceLastUpdateDate__c;
                        srcListToBeUpdated.add(clientSource);
                    }
                } 
            }else {
                src.Client__c = clientID;
                srcListToBeCreated.add(src);
            }
            
        }
        
        if(!srcListToBeUpdated.isEmpty()) {
            System.debug('*** srcListToBeUpdated ***: '+srcListToBeUpdated);
            srList = Database.update(srcListToBeUpdated);
            System.debug('*** srList ***: '+srList);
        }
        if(!srcListToBeCreated.isEmpty()) {
            System.debug('*** srcListToBeCreated ***: '+srcListToBeCreated);
            srList = Database.insert(srcListToBeCreated);
            System.debug('*** srList ***: '+srList);
        }
        return srList;
    }
    
    public static List<Database.SaveResult> upsertClientAddresses(List<ClientAddress__c> addresses, String clientID) {
        
        Map<String, ClientAddress__c> clientAddressBySourceMap = new Map<String, ClientAddress__c>();
        List<ClientAddress__c> addrListToBeUpdated = new List<ClientAddress__c>();
        List<ClientAddress__c> addrListToBeCreated = new List<ClientAddress__c>();
        Database.SaveResult[] srList;
        Boolean isAlreadyExisted = false;
        // Get the SObject describe result
		Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('ClientAddressFields__c').getDescribe();
        Map<String, SObjectField> fieldsMap = describeResult.fields.getMap();
        
        List<ClientAddress__c> retrievedClientAddresses = [SELECT Id, Address1__c, Address2__c, Address3__c, City__c, Country__c,
                                                           PostalCode__c, State__c, AddressTypology__c, IsValid__c 
                                                           FROM ClientAddress__c WHERE Client__c =: clientID];
        System.debug('*** retrievedClientAddresses ***: '+retrievedClientAddresses);
        for(ClientAddress__c receivedAddr : addresses) {
            if(!retrievedClientAddresses.isEMpty()) {
            	for(ClientAddress__c addr : retrievedClientAddresses) {
                    System.debug('*** current addr ***: '+addr);
                    System.debug('*** current receivedAddr ***: '+receivedAddr);
                    isAlreadyExisted = (receivedAddr.Address1__c == addr.Address1__c) && (receivedAddr.Address2__c == addr.Address2__c) 
                        && (receivedAddr.Address3__c == addr.Address3__c) && (receivedAddr.City__c == addr.City__c) && (receivedAddr.Country__c == addr.Country__c) 
                        && (receivedAddr.PostalCode__c == addr.PostalCode__c) && (receivedAddr.State__c == addr.State__c) && (receivedAddr.AddressTypology__c == addr.AddressTypology__c) 
                        && (receivedAddr.IsValid__c == addr.IsValid__c)? true : false;
                    System.debug('*** isAlreadyExisted ***: '+isAlreadyExisted);
                    if(isAlreadyExisted)break;
                }
                if(!isAlreadyExisted) {
                	receivedAddr.Client__c = clientID;
                   	addrListToBeCreated.add(receivedAddr);
                }
            }else {
                receivedAddr.Client__c = clientID;
            	addrListToBeCreated.add(receivedAddr);
        	}
        }
        
        if(!addrListToBeCreated.isEmpty()) {
            System.debug('*** addrListToBeCreated ***: '+addrListToBeCreated);
            srList = Database.insert(addrListToBeCreated);
        }
        
        
        return srList;
    }
    
    public static void upsertClientDetails(Account acc) {
    	List<Store__c> retrievedStore = acc.OriginStore__pr!=null?[SELECT Id FROM Store__c WHERE SourceStoreId__c =: acc.OriginStore__pr.SourceStoreId__c]: null;
        System.debug('*** retrievedStore ***: '+retrievedStore);
        List<Store__c> retrievedPreferredStore = acc.PreferredStore__pr!=null?[SELECT Id FROM Store__c WHERE SourceStoreId__c =: acc.PreferredStore__pr.SourceStoreId__c] : null;
        System.debug('*** retrievedPreferredStore ***: '+retrievedPreferredStore);
        List<Store__c> retrievedMainStore = acc.MainStore__pr!=null?[SELECT Id FROM Store__c WHERE SourceStoreId__c =: acc.MainStore__pr.SourceStoreId__c] : null;
        System.debug('*** retrievedMainStore ***: '+retrievedMainStore);
        acc.OriginStore__pc = (retrievedStore!=null && !retrievedStore.isEmpty())?retrievedStore[0].Id : null;
        acc.MainStore__pc = (retrievedMainStore!=null && !retrievedMainStore.isEmpty())?retrievedMainStore[0].Id : null;
        acc.PreferredStore__pc = (retrievedPreferredStore!=null && !retrievedPreferredStore.isEmpty())?retrievedPreferredStore[0].Id : null;
        acc.OriginStore__pr = null;
        acc.MainStore__pr = null;
        acc.PreferredStore__pr = null;
        System.debug('*** acc ***: '+acc);
        update acc; 
    }

}