unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientAddress__c/fields/AddressTypology__c.field-meta.xml
<CustomField>
    <fullName>AddressTypology__c</fullName>
    <label>Address Typology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>BILLING</fullName>
            </value>
            <value>
                <fullName>DELIVERY</fullName>
            </value>
            <value>
                <fullName>TEMPORARY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Addresses</relationshipLabel>
    <relationshipName>ClientAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AFG</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AGO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AIA</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>ALA</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>ALB</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AND</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>ANT</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>ARE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>ARG</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>ARM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>ASM</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>ATA</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>ATF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>ATG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AUS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AUT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZE</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BDI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BEL</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BEN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BFA</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BGD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BGR</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BHR</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BHS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BIH</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BLM</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BLR</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BLZ</fullName>
                <label>Belize</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/SourceLastUpdateDate__c.field-meta.xml
<CustomField>
    <fullName>SourceLastUpdateDate__c</fullName>
    <label>Source Last Update Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Cegid</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Ecommerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCreationDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreationDate__c</fullName>
    <label>Source Creation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Store__c/fields/Address1__c.field-meta.xml
<CustomField>
    <fullName>Address1__c</fullName>
    <label>Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <label>Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Address3__c.field-meta.xml
<CustomField>
    <fullName>Address3__c</fullName>
    <label>Address 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Netherlands Antilles</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa States</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>TF</fullName>
                <label>French Southern Territories</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Store__c/fields/SourceStoreId__c.field-meta.xml
<CustomField>
    <fullName>SourceStoreId__c</fullName>
    <externalId>true</externalId>
    <label>Source Store Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/WS_ClientKPI_TST.cls
/**
 * @description       : 
 * @author            : Ulrich M. NDONG NGOMO
 * @group             : 
 * @last modified on  : 29-08-2023
 * @last modified by  : Ulrich M. NDONG NGOMO
**/
@IsTest(SeeAllData=false)
public without sharing class WS_ClientKPI_TST {

    @isTest
    static void testCreateClientAddress() {
        
        Test.StartTest();
        // Create test data for the JSON payload
        Map<String, Object> jsonData = new Map<String, Object>();
        List<Account> accList = TestDataFactory.createSObjectList('Account', 1);
        List<Store__c> storeList = TestDataFactory.createSObjectList('Store__c', 1, false);
        storeList[0].SourceStoreId__c = 'FR01';
        insert storeList;
        Account acc = new Account(
        	id= accList[0].Id,
            OriginStore__pr = storeList[0],
            PreferredStore__pr = storeList[0],
            MainStore__pr = storeList[0]
        );
        
        jsonData.put('Client__c', accList[0].Id);
        jsonData.put('client', acc);
        
        List<ClientSource__c> clientSources = new List<ClientSource__c>();
        List<ClientAddress__c> clientAddresses = new List<ClientAddress__c>();
        ClientSource__c source1 = new ClientSource__c(
            Source__c = 'SF',
            SourceCode__c = accList[0].Id,
            SourceCreationDate__c = Date.valueOf('2021-05-17'),
            SourceLastUpdateDate__c = DateTime.valueOf('2021-10-16 15:20:41.990679+00:00')
        );
        
        ClientAddress__c address1 = new ClientAddress__c(
            Address1__c = '7007 FRIARS RD STE 513',
            City__c = 'SAN DIEGO',
            Country__c = 'US',
            PostalCode__c = '92108-1142',
            State__c = 'CA',
            AddressTypology__c = 'STANDARD',
            IsValid__c = false
        );
        clientAddresses.add(address1);
        clientSources.add(source1);
        
        jsonData.put('client_Sources', clientSources);
        jsonData.put('client_Adresses', clientAddresses);
        
        // Convert the test data to JSON
        String requestBody = JSON.serialize(jsonData);
        
        // Simulate the HTTP request
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/ClientKPI';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(requestBody);
        RestContext.request = request;
        
        // Call the REST endpoint
        String response = WS_ClientKPI.upsertClientInformation();
        
		List<ClientAddress__c> retrievedAddress = [SELECT Id FROM ClientAddress__c WHERE Client__c =: accList[0].Id]; 
        Test.StopTest();
        // Verify the response or perform assertions as needed
        System.assertEquals(false, retrievedAddress.isEmpty());
    }
    
    
    @isTest
    static void testUpdateClientAddress() {
        // Create test data for the JSON payload
        Map<String, Object> jsonData = new Map<String, Object>();
        List<Account> accList = TestDataFactory.createSObjectList('Account',1);
        List<Store__c> storeList = TestDataFactory.createSObjectList('Store__c', 1, false);
        storeList[0].SourceStoreId__c = 'FR01';
        insert storeList;
        Account acc = new Account(
        	id= accList[0].Id,
            OriginStore__pr = storeList[0],
            PreferredStore__pr = storeList[0],
            MainStore__pr = storeList[0]
        );
        jsonData.put('Client__c', accList[0].Id);
        jsonData.put('client', acc);
        
        List<ClientSource__c> clientSources = new List<ClientSource__c>();
        List<ClientAddress__c> clientAddresses = new List<ClientAddress__c>();
       
        ClientSource__c source1 = new ClientSource__c(
            Source__c = 'SF',
            SourceCode__c = accList[0].Id,
            SourceCreationDate__c = Date.valueOf('2021-05-17'),
            SourceLastUpdateDate__c = DateTime.valueOf('2021-10-16 15:20:41.990679+00:00'),
            Client__c = accList[0].Id
        );
        ClientAddress__c address1 = new ClientAddress__c(
            Address1__c = '7007 FRIARS RD STE 513',
            City__c = 'SAN DIEGO',
            Country__c = 'US',
            PostalCode__c = '92108-1142',
            State__c = 'CA',
            AddressTypology__c = 'STANDARD',
            IsValid__c = false
        );        
        ClientAddress__c address2 = new ClientAddress__c(
            Address1__c = '7007 FRIARS RD STE 503',
            Address2__c = 'Test Address 2',
            Address3__c = 'Test Address 3',
            City__c = 'SAN DIEGO',
            Country__c = 'US',
            PostalCode__c = '92108-1142',
            State__c = 'CA',
            AddressTypology__c = 'STANDARD',
            IsValid__c = false,
            Client__c = accList[0].Id
        );
        insert address2;
        
        clientSources.add(source1);
        clientAddresses.add(address1);
        insert clientSources;
        
        jsonData.put('client_Sources', clientSources);
        jsonData.put('client_Adresses', clientAddresses);
                
        // Convert the test data to JSON
        String requestBody = JSON.serialize(jsonData);
        
        // Simulate the HTTP request
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/ClientKPI';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(requestBody);
        RestContext.request = request;
        
        // Call the REST endpoint
        String response = WS_ClientKPI.upsertClientInformation();
        
		List<ClientAddress__c> retrievedAddress = [SELECT Id FROM ClientAddress__c WHERE Client__c =: accList[0].Id];       
        // Verify the response or perform assertions as needed
        System.assertEquals(false, retrievedAddress.isEmpty());
    }
}