unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientAddress__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Addresses</relationshipLabel>
    <relationshipName>ClientAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientAddress__c/fields/IsMain__c.field-meta.xml
<CustomField>
    <fullName>IsMain__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Sources</relationshipLabel>
    <relationshipName>ClientSources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>Cegid</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Ecommerce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClientSource__c/fields/SourceCode__c.field-meta.xml
<CustomField>
    <fullName>SourceCode__c</fullName>
    <description>Customer ID from providing system (CEGID, Ecom, etc;)</description>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/due__Diduenjoy_Answer__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Answer</label>
    <nameField>
        <label>Diduenjoy Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/fields/due__Diduenjoy_Feedback__c.field-meta.xml
<CustomField>
    <fullName>due__Diduenjoy_Feedback__c</fullName>
    <label>Diduenjoy Feedback</label>
    <referenceTo>due__Diduenjoy_Feedback__c</referenceTo>
    <relationshipLabel>Diduenjoy Answers</relationshipLabel>
    <relationshipName>Diduenjoy_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/TransactionDate__c.field-meta.xml
<CustomField>
    <fullName>TransactionDate__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>TransactionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/WishlistItem__c.object-meta.xml
<CustomObject>
    <label>Wishlist Item</label>
    <nameField>
        <displayFormat>WI-{0000000}</displayFormat>
        <label>WishlistItem Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WishlistItem__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wishlist Items</relationshipLabel>
    <relationshipName>Wishlist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WishlistItem__c/fields/removedItem__c.field-meta.xml
<CustomField>
    <fullName>removedItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>keep track of deleted items =&gt; instead of deleting the item of the wishlit when the user delete this item from the app, this checbox turns to true and we don&#39;t send it to the app anymore</description>
    <label>removedItem</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CLT_Utils_ClientDetails.cls
///*
// * Created by Israel Zygelboim on 28/02/2019.
// */
public class CLT_Utils_ClientDetails {

    public static Map<String, Object> getClientFields(String clientId) {
        Map<String, Object> clients = CLT_Utils_Mapping.getStandardWrapperList('Account', 'ClientFields', 'FROM Account WHERE Id = \'' + clientId + '\'')[0];
        return clients;
    }

    public static Map<String, Object> getClientIds(String clientId) {
        Map<String, Object> clientIds = new Map<String, Object>();

        list<ClientSource__c> clientSources = [SELECT Id, SourceCode__c, Source__c FROM ClientSource__c where Client__c =: clientId];
        
        for(ClientSource__c clientSource: clientSources){
            if(clientSource.Source__c == '001'){
                clientIds.put('clientCegidId', clientSource.SourceCode__c);
            }else if(clientSource.Source__c == '002'){
                clientIds.put('clientEcomId', clientSource.SourceCode__c);
            }
        }
        
        return clientIds;
    } 
    
    public static  List<Map<String, Object>> getPurchases(String clientId){
        return CLT_Utils_Mapping.getStandardWrapperList('TransactionItem__c', 'OrderItem',
                        'FROM TransactionItem__c WHERE Transaction__r.Client__c =  \''+ clientId + '\' ORDER BY Transaction__r.TransactionDate__c DESC');
    }

    public static List<Object> getClientTimeline(String clientId) {
        List<Object> objects = new List<Object>();

        List<Object> tasks = CLT_Utils_Mapping.getStandardWrapperList('Task', 'Task',
                        'FROM Task WHERE WhatId = \'' + clientId + '\' AND (ActivityDate >= LAST_N_YEARS:5 OR (ActivityDate = NULL AND CreatedDate >= LAST_N_YEARS:5))  ORDER BY ActivityDate, CreatedDate DESC');
        
        objects.addAll(tasks);

        List<Object> events = CLT_Utils_Mapping.getStandardWrapperList('Event', 'Event',
                        'FROM Event WHERE WhatId = \'' + clientId + '\' AND (ActivityDate >= LAST_N_YEARS:5 OR (ActivityDate = NULL AND CreatedDate >= LAST_N_YEARS:5))  ORDER BY ActivityDate, CreatedDate DESC');

        objects.addAll(events);

        List<Object> nps = CLT_Utils_Mapping.getStandardWrapperList('due__Diduenjoy_Answer__c','DiduenjoyAnswer',
                        'FROM due__Diduenjoy_Answer__c WHERE due__Diduenjoy_Feedback__r.due__Account__c = \'' + clientId + '\' ORDER BY due__Diduenjoy_Feedback__r.due__CreatedAt__c, CreatedDate DESC');
        objects.addAll(nps);

        return objects;
    }

    public static List<Map<String, Object>> getClientNotes(String clientId) {
        string userId = UserInfo.getUserId();

        return CLT_Utils_Mapping.getStandardWrapperList('Note__c','Note',
                        ' FROM Note__c WHERE Client__c = \'' + clientId + '\' ORDER BY LastModifiedDate DESC');
    }
    public static List<Map<String, Object>> getClientWishList(String clientId) {
        //string userId = UserInfo.getUserId();

        return CLT_Utils_Mapping.getStandardWrapperList('WishlistItem__c','WishListItem',
                        ' FROM WishlistItem__c WHERE Client__c = \'' + clientId + '\' AND removedItem__c = FALSE ORDER BY LastModifiedDate DESC');
    }

    public static List<Map<String, Object>> getClientAddresses(String clientId) {

        return CLT_Utils_Mapping.getStandardWrapperList('ClientAddress__c','ClientAddress',
                        ' FROM ClientAddress__c WHERE Client__c = \'' + clientId + '\' ORDER BY IsMain__c DESC');
    }
}