unpackaged/main/default/objects/ClientAddress__c/ClientAddress__c.object-meta.xml
<CustomObject>
    <label>Client Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Client Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientProduct__c/ClientProduct__c.object-meta.xml
<CustomObject>
    <label>Client Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Client Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ClientSource__c/ClientSource__c.object-meta.xml
<CustomObject>
    <label>Client Source</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Client Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/due__Diduenjoy_Answer__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Answer</label>
    <nameField>
        <label>Diduenjoy Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/due__Diduenjoy_Answer__c/fields/due__Diduenjoy_Feedback__c.field-meta.xml
<CustomField>
    <fullName>due__Diduenjoy_Feedback__c</fullName>
    <label>Diduenjoy Feedback</label>
    <referenceTo>due__Diduenjoy_Feedback__c</referenceTo>
    <relationshipLabel>Diduenjoy Answers</relationshipLabel>
    <relationshipName>Diduenjoy_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/TransactionItem__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TRI-{0000000000}</displayFormat>
        <label>Transaction Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionItem__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TransactionPayment__c/TransactionPayment__c.object-meta.xml
<CustomObject>
    <label>Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Transaction Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TransactionPayment__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions Payments</relationshipLabel>
    <relationshipName>TransactionsPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/DeleteRecordsBatch.cls
global class DeleteRecordsBatch implements Database.Batchable<sObject> {
    
    Map<Integer, String> objMap;
    
    String query;
    String objectName;
    Integer i;
    
    
    public DeleteRecordsBatch(String objName) {
        i = 0;
        objectName = objName;
        System.debug('objectName ' + objectName);
       
        query = 'SELECT Id FROM ' + objectName;
    }
    
    public DeleteRecordsBatch(Integer objNum) {
        i = objNum;
        
        objMap = new Map<Integer, String> ();
       /* objMap.put(1,'Task');
        objMap.put(2, 'Event');
        objMap.put(3, 'ClientAddress__c');
        objMap.put(4, 'ClientSource__c');
        objMap.put(5, 'due__Diduenjoy_Answer__c');
        objMap.put(6, 'due__Diduenjoy_Feedback__c');
        objMap.put(7, 'Case');
        objMap.put(8, 'TransactionPayment__c');
        objMap.put(9, 'TransactionItem__c');
        objMap.put(10, 'Transaction__c');
        objMap.put(11, 'ClientProduct__c');
        objMap.put(12, 'Note__c');
        objMap.put(13, 'Contact');
        objMap.put(14, 'Account');
        objMap.put(15, 'Product2');*/
        objMap.put(1,'Task');
        objMap.put(2, 'due__Diduenjoy_Answer__c');
        objMap.put(3, 'due__Diduenjoy_Feedback__c');
        objMap.put(4, 'Note__c');

        objectName = objMap.get(i);
        
        System.debug('objectName ' + objectName);
        
        query = 'SELECT Id FROM ' + objectName;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        Database.delete(scope, false);
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug(objectName + ' deleted!!!!!');
       // if(i > 0 && i < 15) {
        if(i > 0 && i < 4) {
            i++;
            DeleteRecordsBatch b = new DeleteRecordsBatch(i);
			Database.executeBatch(b,2000);
        }

    }
}