unpackaged/main/default/objects/Activity/fields/Hub_Origin__c.field-meta.xml
<CustomField>
    <fullName>Hub_Origin__c</fullName>
    <label>Hub Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hub_Origin__c.field-meta.xml
<CustomField>
    <fullName>Hub_Origin__c</fullName>
    <label>Hub Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>JAPOS1</fullName>
            </value>
            <value>
                <fullName>USANY1</fullName>
            </value>
            <value>
                <fullName>USATO1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/WebCountry__c.field-meta.xml
<CustomField>
    <fullName>WebCountry__c</fullName>
    <label>Web Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hub_Origin__mdt/Hub_Origin__mdt.object-meta.xml
<CustomObject>
    <label>Hub Origin</label>
    <pluralLabel>Hub Origins</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Log__c/recordTypes/Log.recordType-meta.xml
<RecordType>
    <fullName>Log</fullName>
    <active>true</active>
    <label>Log</label>
</RecordType>

unpackaged/main/default/objects/WS_Case__mdt/WS_Case__mdt.object-meta.xml
<CustomObject>
    <label>WS_Case</label>
    <pluralLabel>WS_Cases</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/WS_Case__mdt/fields/API_Name_Field__c.field-meta.xml
<CustomField>
    <fullName>API_Name_Field__c</fullName>
    <label>API Name Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WS_Case__mdt/fields/Json_Field__c.field-meta.xml
<CustomField>
    <fullName>Json_Field__c</fullName>
    <label>Json Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/WS_Case.cls
@RestResource(urlMapping='/Cases/*')
global with sharing class WS_Case {

    @HttpPost
    global static void caseCreation() {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String theJsonString = req.requestBody.toString();
        Map<String, Object> theJsonObject = (Map<String, Object>) JSON.deserializeUntyped(theJsonString);
        List<WS_Case__mdt> fieldMappings = [SELECT Json_Field__c, API_Name_Field__c FROM WS_Case__mdt];
        String hubOrigin = '';
        system.debug('^^^^ 1: hubOrigin ' + hubOrigin);
		hubOrigin = getHubOrigin(theJsonObject);
        system.debug('^^^^ 2: hubOrigin ' + hubOrigin);
        system.debug('^^^^ 3: getHubOrigin(theJsonObject) ' + getHubOrigin(theJsonObject));
        
        // LOG INITIALIZATION
        Log__c myLog = new Log__c();
        myLog.Class_Name__c = 'WS_Case';
        myLog.Method__c = 'caseCreation';
        myLog.Request__c = theJsonString;

        Case newCase = new Case();
        newCase.CurrencyIsoCode = 'EUR';
        newCase.Status = 'New';
        newCase.Origin = 'Web';
        newCase.Hub_Origin__c = hubOrigin;
        
		if (fieldMappings.size() > 0){
            for (WS_Case__mdt mapping : fieldMappings) {
                String jsonFieldName = mapping.Json_Field__c;
                String salesforceFieldName = mapping.API_Name_Field__c;
                
                if (theJsonObject.containsKey(jsonFieldName)) {
                    String fieldValue = (String)theJsonObject.get(jsonFieldName);
                    newCase.put(salesforceFieldName, fieldValue);
                }
            }
        }

        JSONGenerator body = JSON.createGenerator(true);
        body.writeStartArray();
        body.writeStartObject();
        try{
            insert newCase;
            
            body.writeStringField('Status:', 'Success');
            if (!Test.isRunningTest() && newCase.Id != null) 
                body.writeStringField('CaseId:', newCase.Id); 
        } 
        catch (Exception e){
            
            body.writeStringField('Status:', 'Failed');
            body.writeObjectField('ErrorMessage:', e.getMessage());
            myLog.Response__c = body.getAsString();
            myLog.Error_Message__c = e.getMessage();
            myLog.Has_Error__c = true;
        }
        body.writeEndObject();
        body.writeEndArray();
        res.responseBody = Blob.valueOf(body.getAsString());
        
        myLog.Response__c = body.getAsString();
        insert myLog;
    }
    
    public static String getHubOrigin(Map<String, Object> objMap) {
        String webCountry = (String) objMap.get('WebCountry__c');
        String activity = (String) objMap.get('csc_activity__c');
        String region = (String) objMap.get('Region__c');
        String hubOrigin;
        if (webCountry == null || activity == null)
            return '';
        hubOrigin = (webCountry == 'US' && activity == 'CC' && region != null) 
                    ? (webCountry + region + activity).replaceAll(' |-', '')
                    : (webCountry + activity).replaceAll(' |-', '');

        system.debug('***** hubOrigin: ' + hubOrigin);
        
        Hub_Origin__mdt[] hubOrigins = [SELECT Label FROM Hub_Origin__mdt WHERE DeveloperName = :hubOrigin LIMIT 1];
		system.debug('***** hubOrigins: ' + hubOrigins);
        system.debug('***** hubOrigins[0].Label: ' + hubOrigins[0].Label);
        
        return (hubOrigins.isEmpty()) ? '' : hubOrigins[0].Label;
    }

    public static String removeSpaces(String inputString) {
        return inputString.replaceAll(' ', '');
    }
}